export interface DiffItem {
  slug: string;
  title: string;
  desc: string;
  external?: boolean;
  url?: string;
  highlights: string[];
  intro?: string;
  about?: string;
  facilities?: string[];
  outcomes?: string[];
  partners?: string[];
}

export interface DiffCategory {
  id: string;
  label: string;
  icon: string;
  heroImage: string;
  items: DiffItem[];
}

export const categories: DiffCategory[] = [
  {
    id: 'innovation',
    label: 'Innovation & Entrepreneurship',
    icon: '🚀',
    heroImage: 'https://images.unsplash.com/photo-1553877522-43269d4ea984?w=1920&q=80',
    items: [
      {
        slug: 'vishnu-tbi',
        title: 'Vishnu Technology Business Incubator (TBI)',
        desc: 'NSTEDB-recognised incubator (VISHVA) fostering student and faculty startups with mentorship, seed funding, and industry connect to transform ideas into enterprises.',
        external: true,
        url: 'https://www.vishva.co/',
        highlights: [
          'NSTEDB-recognised Technology Business Incubator',
          'Mentorship, seed funding, and industry connect',
          'Fosters student and faculty startups',
          'Transforms ideas into viable enterprises',
        ],
      },
      {
        slug: 'sti-hub',
        title: 'Science Technology & Innovation Hub (STI Hub)',
        desc: 'A state-of-the-art interdisciplinary hub for cutting-edge research, prototype development, and student-driven technology innovations.',
        external: true,
        url: 'https://svecwstihub.com/',
        highlights: [
          'State-of-the-art interdisciplinary research hub',
          'Prototype development facilities',
          'Student-driven technology innovations',
          'Cross-departmental collaboration space',
        ],
      },
      {
        slug: 'aicte-idea-lab',
        title: 'AICTE IDEA Lab',
        desc: "AICTE's Idea Development, Evaluation & Application Lab — a 'learn while make' facility that transforms ideas into functional prototypes with a focus on green initiatives.",
        highlights: [
          'Application ID: IDEA202000128',
          'Headed by Dr. G. Srinivasa Rao',
          'Faculty Coordinators: Dr. P. Srinivasa Raju and Dr. S. Hanumanth Rao',
          'Emphasis on GREEN initiatives across all operations',
          'Project-based learning for all engineering branches',
          'Fosters cooperative learning and institutional collaboration',
        ],
        intro: 'The IDEA Lab at Vishnu Womens University provides comprehensive facilities for converting student and faculty ideas into functional prototypes. Located in Bhimavaram, West Godavari District, this AICTE-funded initiative fosters creative thinking and problem-solving skills. It operates under the philosophy of "learn while make," enabling students to develop imaginative capabilities beyond conventional laboratory settings.',
        about: "The lab's mission centers on transforming engineering education by exposing all students to practical innovation spaces, supporting project-based learning while training faculty to integrate creative methodologies into teaching and research. It aims to provide an agile platform for students to convert ideas into working prototypes, build networks between institutes, and foster cooperative learning cultures. The facility also emphasizes faculty engagement in proof-of-concept development and knowledge dissemination, with a strong focus on GREEN initiatives across all operations.",
        facilities: [],
        outcomes: [],
        partners: ['AICTE (All India Council for Technical Education)'],
      },
      {
        slug: 'institution-innovation-cell',
        title: 'Institution Innovation Cell',
        desc: "MoE IIC-recognised cell fostering innovation and entrepreneurship. Rated 4/5 stars in IIC 5.0 and ranked in the 151–300 band for NIRF Innovation 2023.",
        highlights: [
          'Registered for IIC in Academic Year 2018–2019',
          '4 out of 5 star rating in IIC 5.0',
          'NIRF Innovation 2023 — band 151–300',
          'Works alongside VISHVA TBI and EDC',
          'Organises workshops, idea contests, and project exhibitions',
          'Implements MoE National Innovation and Startup Policy',
        ],
        intro: 'The Institution Innovation Cell (IIC) at VWU operates as part of the Ministry of Education\'s National Innovation and Startup Policy framework. It fosters an environment where innovation and entrepreneurship flourish among faculty and students through structured initiatives and mentorship programs. The cell works synergistically with VISHVA TBI (supported by NIDHI) and the Entrepreneurship Development Cell to cultivate entrepreneurial mindsets across campus.',
        about: "The IIC was established to implement the MHRD's National Innovation and Startup Policy, creating pathways for transforming creative ideas into viable products and services. The cell organizes workshops, seminars, and networking sessions with entrepreneurs and investors; conducts idea contests and project exhibitions; and provides mentorship to translate concepts into market-ready solutions. Its vision is to establish the institution as a leading hub for innovation while developing students and faculty as job creators rather than job seekers.",
        facilities: [
          'Vishnu Technology Business Incubator (VISHVA TBI)',
          'Science Technology & Innovation Hub (STI Hub)',
          'AICTE IDEA Lab',
          'Vehicle Design Lab',
          'Assistive Technology Lab',
          'Vishnu Space Application Center (VSAC)',
        ],
        outcomes: [],
        partners: [
          'Ministry of Education (MoE), Government of India',
          'AICTE',
          'NASSCOM',
          'HCL Technologies',
          'Microchip',
          'Texas Instruments',
        ],
      },
      {
        slug: 'tedxsvecw',
        title: 'TEDxVWU',
        desc: 'Licensed independently organised TED event. Inaugural "Sea of Voices" (December 14, 2024) featured eleven speakers spanning healthcare, entrepreneurship, and food technology.',
        highlights: [
          'Inaugural event: "Sea of Voices" — December 14, 2024',
          'Eleven speakers from diverse fields',
          'Topics: eye care, dental health, entrepreneurship, food innovation',
          'Curated by Mr. Akash Rao Mallareddy',
          'Faculty coordinators: Dr. G.J.V. Prasad and Dr. G. Ratnakanth',
          'Fosters intellectual growth and innovation culture',
        ],
        intro: 'Vishnu Womens University launched its inaugural TEDx event series with the theme "Sea of Voices" on December 14, 2024. The platform brings together thought leaders and innovators to share ideas spanning diverse fields including business, healthcare, and technology. TEDxVWU serves as an intellectual forum for fostering innovation and collaboration among students and faculty.',
        about: 'The inaugural TEDxVWU event featured 11 speakers delivering talks on topics ranging from eye and dental care to business practices and food technology, reflecting the college\'s commitment to interdisciplinary discourse. The event was curated by Mr. Akash Rao Mallareddy under the guidance of Chairman Shri K.V. Vishnu Raju and Principal Dr. G. Srinivasa Rao, leaving attendees with a treasure trove of ideas and inspiration.',
        facilities: [],
        outcomes: ['Attendees inspired with interdisciplinary ideas spanning healthcare, business, and technology'],
        partners: ['TED (TEDx programme)'],
      },
    ],
  },
  {
    id: 'industry',
    label: 'Industry Centres of Excellence',
    icon: '🏭',
    heroImage: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=1920&q=80',
    items: [
      {
        slug: 'meda-plm-coe',
        title: 'MEDA & PLM CoE',
        desc: 'Capgemini-partnered CoE for Mechanical Engineering Design Automation and Product Life Cycle Management. Trains students on CATIA, Siemens NX, and ANSYS with placement opportunities.',
        highlights: [
          'MoU partnership with Capgemini',
          'MEDA: 3D modelling, parametric design, FEA, GD&T, design for manufacturing',
          'PLM: product structure, BOM, CAD-PLM integration, Siemens Teamcenter',
          'Training tools: CATIA, Siemens NX CAD, ANSYS, Siemens Teamcenter',
          'Graduates eligible for Capgemini internships and placements',
          'Industry-ready credentials upon completion',
        ],
        intro: 'Vishnu Womens University has partnered with Capgemini through a Memorandum of Understanding to equip Mechanical Engineering students with industry-relevant skills in design automation and product lifecycle management. The MEDA (Mechanical Engineering Design Automation) track trains students in core design and analysis roles using professional engineering software, while the PLM (Product Life Cycle Management) track focuses on managing product data throughout development cycles.',
        about: 'The MEDA programme covers 3D modeling, assembly design, parametric techniques, finite element analysis for structural and thermal validation, geometric dimensioning and tolerancing (GD&T), and design for manufacturing and assembly optimization. The PLM programme addresses product structure, bill of materials, configuration control, CAD-PLM tool integration, and workflow collaboration using Siemens Teamcenter. Students completing these modules receive mentorship from Capgemini, gain industry-ready credentials, and qualify for internship and placement opportunities.',
        facilities: ['CATIA', 'Siemens NX CAD', 'ANSYS', 'Siemens Teamcenter'],
        outcomes: [
          'Students receive industry-ready credentials upon completion',
          'Mentorship from Capgemini industry experts',
          'Internship and placement opportunities with Capgemini',
        ],
        partners: ['Capgemini'],
      },
      {
        slug: 'nasscom-embedded',
        title: 'NASSCOM Embedded Systems Training',
        desc: 'NASSCOM-partnered programme aligned with FutureSkills Prime (MeitY). Trains ECE students in embedded C, RTOS, device drivers, and software validation.',
        highlights: [
          'Aligned with NASSCOM FutureSkills Prime framework (MeitY, GoI)',
          'Curriculum: embedded C, RTOS, device drivers, software validation',
          'Six dedicated faculty members overseeing the programme',
          'Industry clients: MicroChip Technologies and KPIT Technologies',
          'Prepares students for embedded software engineer and IoT developer roles',
        ],
        intro: 'The Department of Electronics and Communication Engineering at Vishnu Womens University has partnered with NASSCOM to deliver comprehensive embedded systems instruction aligned with the FutureSkills Prime framework. This programme equips students with industry-relevant competencies and practical experience in embedded systems development, bridging the gap between academic learning and industry requirements.',
        about: 'The NASSCOM-certified curriculum covers embedded C programming, real-time operating systems (RTOS), device driver design, and software validation methodologies. The initiative supports India\'s digital transformation goals by aligning training with the FutureSkills Prime framework developed jointly by NASSCOM and MeitY. Six dedicated faculty members oversee curriculum delivery, with additional collaboration from MicroChip Technologies and KPIT Technologies.',
        facilities: [
          'Embedded development boards',
          'RTOS platforms',
          'Microcontroller boards',
          'Real-world project environments (IoT, automotive, consumer electronics)',
        ],
        outcomes: [
          'Graduates proficient in embedded C, RTOS implementation, and firmware debugging',
          'Improved understanding of software quality validation',
          'Students prepared for core embedded sector positions',
        ],
        partners: ['NASSCOM', 'MeitY', 'MicroChip Technologies', 'KPIT Technologies'],
      },
      {
        slug: 'hcl-vlsi-training',
        title: 'HCL Tech VLSI Training',
        desc: 'HCL Tech-partnered VLSI design and verification training covering ASIC/FPGA design flows through SDL modules, VILT sessions, and chip design puzzles.',
        highlights: [
          'Partnership with HCL Technologies for semiconductor training',
          'Covers digital design, analog design, verification, and physical design',
          'Chip puzzles and hands-on ASIC/FPGA design workflows',
          'Virtual instructor-led training (VILT) by HCL subject matter experts',
          'Industry-recognised certification upon completion',
          'Faculty leads: Mrs. K Swathi and Mrs. B Vaisalini',
        ],
        intro: 'The Electronics and Communication Engineering department at Vishnu Womens University has partnered with HCL Tech to deliver comprehensive VLSI design and verification training. The programme equips students with cutting-edge knowledge and hands-on expertise in VLSI design, bridging the gap between academia and semiconductor sector expectations.',
        about: 'The curriculum is structured around self-directed learning modules with assignments and chip puzzles, virtual instructor-led training (VILT) sessions with HCL subject matter experts, formative assessments, and hands-on lab experiments. Students build a strong foundation in digital design, analog design, verification, and physical design while developing competencies aligned with semiconductor industry standards.',
        facilities: [
          'ASIC/FPGA design workflow tools',
          'Virtual lab environment for VLSI experiments',
          'Chip design puzzle platform',
        ],
        outcomes: [
          'Strong foundation in VLSI concepts and ASIC/FPGA design workflows',
          'Industry-recognised VLSI design certification',
          'Practical chip design skills through puzzles and lab experiments',
        ],
        partners: ['HCL Technologies'],
      },
      {
        slug: 'microchip-embedded',
        title: 'Microchip Embedded System',
        desc: 'Centre of Excellence with Eduskills — PIC microcontroller training (8-bit to 32-bit) covering IoT, automation, and communication protocols for ECE, EEE, and CSE students.',
        highlights: [
          'Covers 8-bit, 16-bit, and 32-bit PIC microcontroller platforms',
          'Applications in IoT, automation, and sensor-based systems',
          'Online certification programmes via Eduskills platform',
          'AICTE ATAL–EduSkills Faculty Development Programme conducted',
          'Serves ECE, EEE, and CSE disciplines',
          'Faculty team led by E. R. Praveen Kumar',
        ],
        intro: 'The Microchip Embedded System Centre at VWU is a cutting-edge facility aimed at bridging the gap between academic knowledge and industry-relevant skills in embedded systems. Established through collaboration with Eduskills, the centre equips students with practical experience in designing, programming, and testing real-time embedded applications using PIC microcontroller-based development boards.',
        about: 'The centre enables students to work with 8-bit, 16-bit, and 32-bit PIC microcontrollers across applications including IoT, automation, and sensor-based systems. Faculty mentorship and online certification programmes through Eduskills enhance student employability and technical competencies. Key objectives include advancing research in microchip design and testing, developing skilled talent through hands-on training, and promoting sustainable, energy-efficient microchip solutions.',
        facilities: [
          'Wide range of PIC microcontroller variants',
          'Development tools and hardware debugging kits',
          'Real-world project environments',
          'Eduskills online certification platform',
        ],
        outcomes: [
          'Hands-on skills in embedded C and microcontroller programming',
          'Online certifications via Eduskills improving employability',
          'AICTE ATAL faculty development programme conducted',
        ],
        partners: ['Eduskills', 'AICTE (ATAL programme)'],
      },
      {
        slug: 'ti-dsp-coe',
        title: 'TI-DSP Centre of Excellence',
        desc: 'Texas Instruments DSP CoE advancing research in telecommunications, audio, video, and image processing. DST-sponsored research (Rs. 53 lakhs) on speech enhancement for hearing-impaired individuals.',
        highlights: [
          'Rs. 10 lakh MODROBS funding from AICTE for lab modernisation',
          'Campus MATLAB licence — unlimited student access',
          '233 students trained across 60 batches',
          'Winners: TI India Analog Maker Competition 2014',
          'DST research grant: Rs. 53 lakhs for telephony speech enhancement',
          '21 project batches registered for IICDC 2019',
        ],
        intro: 'The Texas Instruments Digital Signal Processing Centre of Excellence at VWU is a pioneering research facility dedicated to advancing DSP innovation across telecommunications, audio, video, and image processing. The centre facilitates collaborations between academic institutions and industry partners while empowering students with practical expertise in signal processing technology.',
        about: 'The facility aims to transform academia through pioneering research, collaboration, and education in digital signal processing. Its core mission encompasses advancing DSP research via interdisciplinary partnerships, preparing students for industry roles, and developing solutions addressing societal challenges. Research focus areas include speech processing, medical imaging, assistive technology for hearing-impaired individuals, robotic systems, and environmental monitoring.',
        facilities: [
          'TI DSP Starter Kits',
          'TMS320C6713 DSK kits',
          'Analog Starter Kits',
          'MSP430F microcontroller boards and LaunchPads',
          'RFID Evaluation Kits',
          'Bluetooth Transceivers',
          'Medical imaging platforms',
          'Campus MATLAB licence',
        ],
        outcomes: [
          'Winners of TI India Analog Design Contest and Analog Maker Competition 2014',
          '21 project batches registered for IICDC 2019',
          'DST-sponsored research on assistive technology for hearing-impaired individuals',
        ],
        partners: ['Texas Instruments, India'],
      },
      {
        slug: 'ultratech-coe',
        title: 'UltraTech CoE',
        desc: 'UltraTech Cement Ltd partnership (est. March 2024) advancing sustainable construction practices through R&D, education, training, industry collaboration, and consultancy.',
        highlights: [
          'MoU signed with UltraTech Cement Ltd — March 20, 2024',
          '50 students enrolled from 2nd and 3rd year cohorts',
          'Three expert technical sessions on cement, concrete, and mix design',
          'Focus: R&D, Training, Industry Collaboration, Technology Transfer',
          'Promotes women in sustainable civil engineering',
        ],
        intro: 'The Centre of Excellence for Sustainable Construction Practices and Materials (CSCPM) operates within the Department of Civil Engineering at VWU in partnership with UltraTech Cement Ltd. This collaborative initiative advances sustainable practices in the construction industry by combining academic expertise with industrial resources. The MoU was signed on March 20, 2024.',
        about: "The centre strives to be a beacon of excellence, shaping a world where sustainable construction materials lead the way in creating environmentally conscious built environments. Key focus areas include empowering civil engineering students — particularly women — with comprehensive education on sustainable materials, Research and Development, Education and Training, Industry Collaboration, Technology Transfer, and Consultancy Services.",
        facilities: [],
        outcomes: [
          '50 students benefited from industry expert sessions',
          'Collaborative research on sustainable construction materials',
        ],
        partners: ['UltraTech Cement Ltd'],
      },
      {
        slug: 'chips-to-startup',
        title: 'Chips to Startup (C2S)',
        desc: "MEITy-funded programme (Rs. 64.5 Lakhs) under India's semiconductor self-reliance mission. Project: Memory Optimised Co-Processor for Edge AI. Patent already filed.",
        highlights: [
          'Funded by MeitY — Rs. 64.5 Lakhs over 5 years',
          'Project: Memory Optimised Co-Processor for Enhanced Edge AI',
          'Patent filed based on preliminary research outcomes',
          'EDA tools: AMD Xilinx, Cadence, Synopsys, Siemens, Silvaco, Ansys, Keysight',
          'FPGA boards: PynqZ2, Xilinx Ultrascale, Zynq, Kria',
          'Chief Investigator: Dr. K. Padma Vasavi',
        ],
        intro: "The Chips to Startup (C2S) programme at VWU aligns with the Government of India's vision for making India self-reliant in electronics system design, aiming to train 85,000 specialised professionals over five years in VLSI and Embedded System Design. It is funded by the Ministry of Electronics and Information Technology (MeitY) with a project budget of Rs. 64.5 Lakhs.",
        about: 'The C2S programme fosters a system-on-chip culture across educational levels and establishes an ASIC/IC design ecosystem. It emphasises industry-led translational research, reusable IP core development, startup incubation, and creating industry-ready manpower in system and SOC design. The college obtained advanced EDA tools from major vendors and modern FPGA boards through this programme.',
        facilities: [
          'AMD Xilinx EDA tools',
          'Cadence EDA tools',
          'Synopsys EDA tools',
          'Siemens EDA tools',
          'Silvaco, Ansys, and Keysight EDA tools',
          'PynqZ2 FPGA boards',
          'Xilinx Ultrascale, Zynq, and Kria FPGA boards',
        ],
        outcomes: [
          'Patent filed: Memory Optimised Co-Processor for Enhanced Edge AI',
          'Industry-ready professionals in VLSI and SOC design',
          'Startup incubation and IP protection culture established',
        ],
        partners: ['Ministry of Electronics and Information Technology (MeitY)'],
      },
    ],
  },
  {
    id: 'research',
    label: 'Research & Specialised Labs',
    icon: '🔬',
    heroImage: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=1920&q=80',
    items: [
      {
        slug: 'vsac',
        title: 'Vishnu Space Application Center (VSAC)',
        desc: 'S-band ground station with Dhruva Space Pvt Ltd. 3-metre parabolic antenna at 2200–2290 MHz (35.4 dBi gain). Satellite data acquisition, CubeSat design, and HAB payload training.',
        highlights: [
          'S-band ground station — 2200–2290 MHz, 35.4 dBi gain',
          '21 students obtained HAM radio licences (July 2023)',
          '28 students completed Morse code training',
          'CubeSat design and HAB payload development training',
          'Collaboration with Dhruva Space (National Award winner)',
          'Satellite data analysis and payload design projects',
        ],
        intro: 'The Vishnu Space Application Center (VSAC), established at the Department of Electronics and Communication Engineering at VWU, is a collaborative initiative between Sri Vishnu Educational Society and Dhruva Space Private Limited. This facility serves as an S-band ground station dedicated to satellite tracking and space technology research.',
        about: 'The center aims to acquire, decode, and analyze satellite data for scientific research, provide practical training in satellite tracking and CubeSat design, and conduct R&D projects improving satellite communication systems. It also supports HAM radio licensing and Morse code education to inspire students toward space technology careers. The facility features a 3-metre parabolic mesh reflector antenna operating at 2200–2290 MHz with 35.4 dBi gain.',
        facilities: [
          '3-metre parabolic mesh reflector antenna (2200–2290 MHz, 35.4 dBi gain)',
          'Advanced satellite tracking software',
          'S-band ground station infrastructure',
        ],
        outcomes: [
          '21 students obtained HAM radio licences (July 2023)',
          '28 students completed Morse code training',
          'Student involvement in satellite data analysis and CubeSat payload design',
        ],
        partners: ['Dhruva Space Private Limited'],
      },
      {
        slug: 'ar-vr-studio',
        title: 'AR / VR Studio',
        desc: 'CSE Centre of Excellence (est. August 7, 2024) with Meta Quest 3 devices, 30 Core i7 13th-gen PCs, dual 4K projectors. Supports AR/VR, XR, and Deep Learning development.',
        highlights: [
          'Established as Centre of Excellence — August 7, 2024',
          '2 Meta Quest 3 128GB VR devices',
          '30 high-performance PCs (Core i7, 16GB RAM, 4GB graphics)',
          'Dual projection: 2K and 4K projectors',
          'Sony 65-inch 4K display with 5.1 surround sound',
          'Development tools: Unity, Unreal Engine, Blender',
        ],
        intro: 'The AR/VR Studio at Vishnu Womens University is a state-of-the-art facility dedicated to exploring and developing augmented and virtual reality technologies. Established as a Centre of Excellence by the Department of Computer Science and Engineering on August 7, 2024, the studio creates a collaborative space for students, faculty, and researchers.',
        about: 'The studio aims to develop practical expertise in AR/VR development tools including Unity, Unreal Engine, and Blender while facilitating industry-oriented projects and workshops. It promotes applications in education, healthcare, and rural development, and establishes partnerships with industry leaders to provide internships and encourage research publications and patents.',
        facilities: [
          '2 Meta Quest 3 128GB VR devices',
          '30 high-performance PCs (Core i7 13th-gen, 16GB RAM, 512GB SSD, 4GB graphics)',
          '2 dedicated servers and 2 Mac OS systems',
          '2K and 4K projectors',
          'Sony 65-inch 4K display with 5.1 surround sound',
          'Unity licence for 30 systems (1 year)',
        ],
        outcomes: [],
        partners: [],
      },
      {
        slug: 'vehicle-design-lab',
        title: 'Vehicle Design Lab',
        desc: 'Mechanical Engineering CoE inaugurated by MD of Volvo India (March 2019). Prepares students for SAE BAJA-ATV, SUPRA-F1, Go-kart, and ESVC-Solar car competitions.',
        highlights: [
          'Inaugurated March 11, 2019 by Kamal Bali, MD of Volvo India',
          'National competitions: SAE BAJA-ATV, SUPRA-F1, Go-kart, ESVC-Solar car',
          'Covers BAJA, EFFICYCLE, REEV, SUPRA, and GOKART motorsport engineering',
          'Training in power-train systems, vehicle dynamics, and fabrication',
          'Sustainable vehicle design and fuel efficiency research',
        ],
        intro: 'The Vehicle Design Lab is a Centre of Excellence established by the Department of Mechanical Engineering at Vishnu Womens University, enabling students to design and fabricate vehicles for national-level competitions. Inaugurated on March 11, 2019 by Kamal Bali, Managing Director of Volvo India, the lab provides comprehensive facilities for automotive system development and research.',
        about: 'The lab combines computing resources with hands-on training to prepare mechanically-minded students for automotive industry challenges, covering motorsport engineering, vehicle power-train systems, vehicle stability and dynamics testing, and fabrication. It promotes interdisciplinary collaboration, innovation research in fuel efficiency and safety, industry partnerships, and sustainable vehicle design practices.',
        facilities: [
          'CAD/CAE software for modelling, analysis, and drafting',
          'Vehicle power-train systems',
          'Vehicle stability and dynamics testing equipment',
          'Fabrication and servicing facilities',
        ],
        outcomes: [
          'Student teams participate in national-level SAE BAJA-ATV, SUPRA-F1, Go-kart, and ESVC competitions',
        ],
        partners: ['Volvo India (inaugural partnership)'],
      },
      {
        slug: 'assistive-tech-lab',
        title: 'Assistive Technology Lab (ATL)',
        desc: 'Est. 2009 with UMass Lowell, USA. 70+ students and 15 faculty design prosthetics, mobility aids, currency detectors, and communication devices for the deaf, distributed to 6 partner organisations.',
        highlights: [
          'Established 2009 with UMass Lowell, USA',
          '70+ students and 10+ faculty mentors participate annually',
          'Annual collaboration visits from Prof. Alan Rux (UMass Lowell)',
          'Devices distributed to 6+ disability support organisations',
          'Exhibited at IIT Madras Makeathon and Telangana AT Summit',
          'Projects span mobility, prosthetics, and communication devices',
        ],
        intro: 'The Assistive Technology Lab at Vishnu Womens University develops innovative projects designed to benefit people with disabilities. Established in 2009 in collaboration with the University of Massachusetts Lowell, the ATL creates practical engineering solutions that help integrate differently-abled individuals into mainstream society.',
        about: 'The ATL emphasises collaborative projects and community partnerships that nurture social responsibility among participants, encouraging cross-disciplinary collaboration on real-world societal issues. Over 70 students participate annually from multiple institutions, guided by 10+ faculty mentors, with annual visits from Prof. Alan Rux (ATP Coordinator, UMass Lowell). Completed devices are distributed to disability support organisations across the region.',
        facilities: [],
        outcomes: [
          'Smart Sole mobility support device developed',
          'Currency Detector for visually impaired developed',
          'Prosthetic Forearm project completed',
          'Sign Language audio conversion device developed',
          'Vision Assist navigation device created',
          'Seizure Detection System and interactive games for blind children delivered',
        ],
        partners: [
          'University of Massachusetts, Lowell, USA',
          'Center for Visually Challenged, Bhimavaram',
          'Sri Venkateswara Deaf and Dumb School',
          'Zion School for Visually and Physically Challenged',
          'Anjali School for Physically and Mentally Challenged',
        ],
      },
      {
        slug: 'hpc-lab',
        title: 'High Performance Computing Lab',
        desc: 'GPU computing CoE (est. 2021) in the Department of AI. Research in ML, deep learning, stroke recognition, chronic disease prediction, and IoT-based ECG analysis.',
        highlights: [
          'Established 2021 — Department of Artificial Intelligence',
          'GPU computing for ML, deep learning, and computer vision',
          'DST-sponsored external research projects undertaken',
          'Research: stroke recognition, chronic disease prediction, IoT ECG, crop variety recognition',
          'Addresses skill gaps in advanced HPC adoption',
          'Led by Dr. A Senthil Kumar and Dr. G Durga Prasad',
        ],
        intro: 'The Centre of Excellence in High Performance Computing (HPC) Lab was established in 2021 at the Department of Artificial Intelligence at Vishnu Womens University. The facility accelerates research across cloud computing, drug development, and scientific applications by pooling computing capacity far beyond standard workstations.',
        about: "The lab's mission includes carrying out cutting-edge research with maximised synergy and exploring novel computational methods for scalable data mining and optimisation with complex datasets. It provides GPU computing resources for faculty and students building models with large real-world datasets, and addresses skill gaps through specialised training in advanced HPC adoption.",
        facilities: [
          'High-performance GPU computing infrastructure',
          'Large-scale dataset processing environment',
          'Cloud computing research platforms',
        ],
        outcomes: [
          'DST-sponsored external funded research projects completed',
          'Research publications in leaf disease identification and ECG signal analysis',
        ],
        partners: ['DST (Department of Science and Technology)'],
      },
      {
        slug: 'concrete-canoe-lab',
        title: 'Concrete Canoe Laboratory',
        desc: "Organised India's first National Concrete Canoe Competition for female civil engineers (August 2023). Team WAKA: iTIC BUILD winner at IIT Hyderabad. Five canoe projects completed.",
        highlights: [
          "Organised India's first National Concrete Canoe Competition for women — August 2023",
          'Team WAKA — iTIC BUILD winner, IIT Hyderabad, with seed funding',
          'Five canoe projects: WAKA, WAKA 1.0 & 2.0, KANU, AIKYAM, CANOA',
          'Multiple first-prize wins at regional and national technical festivals',
          'Current research: eco-friendly lightweight concrete boats for sustainable aquaculture',
        ],
        intro: 'The Concrete Canoe Laboratory at Vishnu Womens University enables students to apply theoretical knowledge by constructing functional canoes entirely from concrete. This hands-on facility combines structural design, materials science, and project management while fostering innovation and teamwork among civil engineering students.',
        about: "The lab aims to equip learners with specialised skills in concrete canoe design and construction, cultivating a research-focused culture that explores innovative materials and techniques. Current research investigates eco-friendly lightweight concrete boats for sustainable aquaculture, exploring durable, environmentally responsible vessel designs incorporating recycled materials and innovative concrete compositions. The lab also hosted India's first concrete canoe competition in Andhra Pradesh and Telangana.",
        facilities: [
          'Concrete fabrication and testing equipment',
          'Lightweight concrete materials laboratory',
        ],
        outcomes: [
          'Team WAKA: iTIC BUILD winner with seed funding from IIT Hyderabad TIC',
          'First-prize wins at regional and national technical festivals',
          'Five functional concrete canoe prototypes: WAKA, KANU, AIKYAM, CANOA variants',
        ],
        partners: [],
      },
      {
        slug: 'dream-house-lab',
        title: 'Dream House Construction Lab',
        desc: 'Sustainable construction research facility. Team SMB: iTIC BUILD winner at IIT Hyderabad (Rs. 1 lakh seed funding). 42+ students in active stabilised mud block research.',
        highlights: [
          'Team SMB — iTIC BUILD winner, IIT Hyderabad TIC, Rs. 1 lakh seed funding',
          '42+ students across years II–IV in active projects',
          'Research: stabilised mud blocks for eco-friendly construction',
          'Optimal mix proportions examined for compressive strength and water absorption',
          'Led by Mr. Ramgopal L., specialising in concrete technology',
        ],
        intro: 'The Dream House Construction Lab (DHCL) is a specialised facility at Vishnu Womens University designed to support research and innovation in construction technology. It functions as a collaborative space where faculty, students, and industry partners work together on projects addressing real-world challenges in the built environment.',
        about: 'Key objectives include conducting innovative research on construction technology, materials, and sustainable practices; offering workshops and training programmes for practical skill enhancement; and advancing knowledge in the construction industry while meeting societal needs. Current research investigates optimal mix proportions for stabilised mud blocks, examining compressive strength, flexural properties, and water absorption using locally available materials and stabilisers including lime and cement.',
        facilities: [
          'Stabilised mud block fabrication and testing equipment',
          'Construction materials laboratory',
        ],
        outcomes: [
          'iTIC BUILD award winner with Rs. 1 lakh seed funding from IIT Hyderabad TIC',
          'Ongoing research on stabilised mud blocks for sustainable construction',
        ],
        partners: ['IIT Hyderabad Technology Incubation Centre (iTIC)'],
      },
    ],
  },
  {
    id: 'global',
    label: 'International & Global Outreach',
    icon: '🌏',
    heroImage: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=1920&q=80',
    items: [
      {
        slug: 'vjoc',
        title: 'Vishnu Japan Outreach Centre – VJOC',
        desc: 'Strategic outreach centre fostering India-Japan academic and industrial partnerships — facilitating student exchange, Japanese language training, and joint research collaborations.',
        external: true,
        url: 'https://vjoc.in/',
        highlights: [
          'Strategic India-Japan academic partnership centre',
          'Student exchange programmes',
          'Japanese language training',
          'Joint research collaborations',
        ],
      },
      {
        slug: 'gsac',
        title: 'Graduate Study Abroad Center – GSAC',
        desc: 'Guides students on international higher education across 7 destinations: USA, Canada, UK, China, Germany, Australia, and Spain. Provides counselling, education loans, and pre-departure orientation.',
        highlights: [
          '7 destinations: USA, Canada, UK, China, Germany, Australia, Spain',
          'GRE, TOEFL, and IELTS training support',
          'Education loan facilitation through partner banks',
          'Scholarship identification and application support',
          'Pre-departure orientation: cultural adaptation and safety',
          'Alumni network support in destination countries',
        ],
        intro: 'The Graduate Study Abroad Center (GSAC) at Vishnu Womens University supports students pursuing higher education internationally by providing comprehensive guidance to identify suitable destinations, universities, and academic programmes. The center was established to reduce the financial and emotional burden on families by offering hand-holding in GRE/TOEFL/IELTS training and application processing.',
        about: 'GSAC provides counselling on international course options and destinations, education loan assistance through partner banks, scholarship identification and application support, and pre-departure orientation programmes covering cultural adaptation and safety. Students are also connected with alumni already studying or working in destination countries to ease their transition.',
        facilities: [],
        outcomes: [
          'Students successfully guided through international university applications',
          'Admitted students connected with alumni in destination countries',
        ],
        partners: [],
      },
      {
        slug: 'foreign-languages',
        title: 'Foreign Languages',
        desc: 'Since 2012 — 60-hour certified courses in French, German, Spanish, Japanese, and Korean by Global Language Solutions, Chennai. 2,500+ cumulative certifications.',
        highlights: [
          'Programme running since 2012',
          'Four languages: German, French, Japanese, Spanish',
          '2024–25 enrolment: German (395), French (260), Japanese (259), Spanish (130)',
          'Cumulative certifications: French (879), German (691), Spanish (508), Japanese (348), Korean (167)',
          '60-hour basic-level curriculum per language',
          'Delivered by Global Language Solutions, Chennai',
        ],
        intro: 'The Foreign Languages programme at Vishnu Womens University, launched in 2012, enables engineering students to develop foundational communication abilities in multiple international languages. The programme opens pathways to new cultures, perspectives, and career opportunities while fostering effective global communication.',
        about: 'Each language follows a 60-hour basic-level curriculum covering fundamental vocabulary, grammar structures, pronunciation, listening comprehension, speaking practice, cultural contexts, and everyday communication scenarios. Students receive graded certificates upon successful completion, supporting international careers, study abroad aspirations, and personal professional growth. As of 2024–25, the programme serves 1,044 students across four languages.',
        facilities: [],
        outcomes: [
          'Over 2,500 cumulative language certifications awarded since 2012',
          'Students prepared for international careers and study abroad programmes',
        ],
        partners: ['Global Language Solutions, Chennai'],
      },
    ],
  },
  {
    id: 'student',
    label: 'Student Development & Social Impact',
    icon: '🎓',
    heroImage: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=1920&q=80',
    items: [
      {
        slug: 'student-success-centre',
        title: 'Vishnu Student Success Centre',
        desc: 'Holistic student support hub offering academic counselling, mental wellness, career guidance, and skill development services under one roof for all VWU students.',
        external: true,
        url: 'https://vishnussc.in',
        highlights: [
          'Academic counselling and mentoring',
          'Mental wellness and student support services',
          'Career guidance and placement readiness',
          'Skill development programmes',
        ],
      },
      {
        slug: 'talentsprint-wise',
        title: 'TalentSprint – WISE',
        desc: "Women in Software Engineering programme with TalentSprint combining the ELITE Program, Microsoft Mentoring Program, and placement support for top MNC software roles.",
        highlights: [
          'Exclusive partnership with TalentSprint Private Limited',
          'Targets women engineers for DeepTech software careers',
          'Microsoft Mentoring Programme component',
          'ELITE Programme track for advanced learners',
          'Project-based learning with industry mentorship',
          'Placement success documented across multiple batches',
        ],
        intro: 'WISE is an exclusive collaborative programme between Vishnu Womens University and TalentSprint Private Limited (Hyderabad) designed to develop women engineering students into highly trusted DeepTech Software Engineers. The initiative operates alongside regular coursework, blending rigorous academics with industry experience to prepare students for global technology industries.',
        about: 'The programme includes a Microsoft Mentoring Programme component, an ELITE Programme track, and project-based learning curriculum supported by industry partnerships and a dedicated WISE Team. It enables students to develop mid-size software systems through experiential learning, build competitive resumes tailored for multinational software organisations, and cultivate industry-necessary skills for confidence and competence as professionals.',
        facilities: [],
        outcomes: [
          'Students placed at leading software organisations',
          'Women engineers equipped for global technology industry roles',
        ],
        partners: ['TalentSprint Private Limited', 'Microsoft', 'NSE (National Stock Exchange)'],
      },
      {
        slug: 'smart-interviews',
        title: 'Smart Interviews – C&DS Programme',
        desc: 'Data Structures & Algorithms training since 2017. 972 total placements across seven batches. 142 students placed at Amazon, Flipkart, Adobe, and Palo Alto Networks with 10–50 LPA packages.',
        highlights: [
          'Programme running since 2017',
          '972 total placements across seven batches (2014–2024)',
          'Max 400 students selected annually via HackerRank',
          'Highest performing batch: 209 placements (2017–2021)',
          'Packages ranging from 10 to 50 lakh annually',
          'Placements at Amazon, Flipkart, Adobe, and Palo Alto Networks',
        ],
        intro: 'Vishnu Womens University has collaborated with Smart Interviews to deliver specialised training in Problem Solving with Data Structures and Algorithms (C&DS) since 2017. The programme targets students for software development roles, as major tech companies increasingly recruit through coding contests and hackathons.',
        about: 'The curriculum spans three phases across three semesters: Phase 1 covers programming fundamentals and complexity analysis; Phase 2 addresses sorting, hashing, and string operations; Phase 3 focuses on advanced data structures including trees, dynamic programming, and graph theory. Up to 400 students are selected annually via HackerRank coding contests, and students are mentored by previously placed graduates.',
        facilities: [
          'HackerRank coding contest platform',
          'Leaderboard scoring and performance monitoring system',
        ],
        outcomes: [
          '972 placements across seven batches (2014–2024)',
          'Students placed at Amazon, Flipkart, Adobe, and Palo Alto Networks',
          'Participation in TCS Code Vita, Infosys Hack with Infy, CodeChef, and Codeforces',
        ],
        partners: ['Smart Interviews'],
      },
      {
        slug: 'rural-women-tech-park',
        title: 'Rural Women Technology Park – WTP',
        desc: 'Since 2015 — 1,200+ rural women trained in Bhimavaram across VCO production, CAD stitching, handloom weaving, food processing, and health & nutrition.',
        highlights: [
          '~1,200 rural women trained between 2015–2018',
          'Five training areas: VCO, CAD stitching, handloom, food processing, health',
          'Some trainees established their own businesses',
          'Beneficiaries employed in bakeries and tailoring operations',
          'Government-recognised technology park',
        ],
        intro: 'The Rural Women Technology Park (WTP) at Vishnu Womens University enhances rural women\'s access to technology and practical skills, having trained approximately 1,200 rural women between 2015 and 2018 in Bhimavaram. The initiative empowers women through knowledge, attitude, and practice development across multiple skill areas.',
        about: 'The programme examines linkages between women\'s roles, responsibilities, and their use of technology in rural communities, focusing on tools central to livelihoods at the household level. Training is organised across five intervention areas: Virgin Coconut Oil Production, Computer-Aided Design/Stitching/Handloom Weaving, Women Health and Nutrition, Food Processing and Value-Added Products, and Waste Paper Recycling.',
        facilities: [
          'Baking equipment and food processing tools',
          'Tailoring, embroidery, and pattern drafting setup',
          'Computer-Aided Design workstations',
          'Waste paper recycling materials and tools',
        ],
        outcomes: [
          '~1,200 rural women trained between 2015–2018',
          'Multiple trainees launched independent businesses',
          'Beneficiaries employed in bakeries and tailoring operations',
        ],
        partners: [],
      },
      {
        slug: 'radio-vishnu',
        title: 'Radio Vishnu 90.4',
        desc: 'Campus community radio station providing students real-world broadcasting experience in content creation, RJ skills, live production, and radio journalism.',
        external: true,
        url: 'http://radiovishnu.com/',
        highlights: [
          'Campus community radio station at 90.4 FM',
          'Real-world broadcasting experience',
          'Content creation and RJ skills training',
          'Live production and radio journalism',
        ],
      },
      {
        slug: 'nirvahana',
        title: 'Nirvahana',
        desc: 'MBA flagship leadership initiative with case competitions, daily business news hours, stock market sessions, union budget analyses, and industry networking under dedicated faculty mentorship.',
        highlights: [
          'Leadership initiative within the MBA/Management Studies dept.',
          'Daily business news hours and stock market education sessions',
          'Case competitions, entrepreneurial talks, and startup initiatives',
          'Industry immersion programmes and career-building workshops',
          'Budget analysis sessions and role-play simulations',
          'Three dedicated faculty across finance, operations, marketing, and HR',
        ],
        intro: 'Nirvahana is a dynamic leadership initiative within the MBA programme at Vishnu Womens University, functioning as a beacon of excellence within the Department of Management Studies. The programme cultivates strategic business acumen through workshops, seminars, and competitive case studies. Its vision is to establish a dynamic ecosystem where aspiring leaders harness strategic insights, embrace innovation, and champion ethical practices.',
        about: "Nirvahana's mission centres on developing forward-thinking business leaders equipped to address global challenges. Primary objectives include developing strategic thinking, facilitating industry networking and peer collaboration, providing career development resources, fostering an entrepreneurial mindset, and promoting community service and ethical leadership. Activities include storytelling in business, logo redesign projects, budget analysis sessions, role-play simulations, entrepreneurial talks, stock market education, and industry immersion programmes.",
        facilities: [],
        outcomes: [
          'MBA students developed as strategic, ethical business leaders',
          'Students gain practical experience through case competitions and startup initiatives',
        ],
        partners: [],
      },
      {
        slug: 'vishnu-school-of-music',
        title: 'Vishnu School of Music',
        desc: 'A dedicated school nurturing musical talent and providing professional music education, continuing the Vishnu tradition of holistic arts and cultural development alongside engineering excellence.',
        external: true,
        url: 'https://svesschoolofmusic.in/',
        highlights: [
          'Professional music education school',
          'Holistic arts and cultural development',
          'Part of the Sri Vishnu Educational Society family',
          'Nurturing musical talent alongside engineering excellence',
        ],
      },
    ],
  },
];

export function findItemBySlug(slug: string): { item: DiffItem; category: DiffCategory } | null {
  for (const cat of categories) {
    const item = cat.items.find((i) => i.slug === slug);
    if (item) return { item, category: cat };
  }
  return null;
}
