export interface UniversityTab {
  label: string;
  universities: string[];
}

export interface HigherEducationSection {
  title: string;
  /** Flat list, no sub-tabs (e.g. USA). */
  universities?: string[];
  /** Sub-tabs within this section (e.g. UK / Australia / Canada). */
  tabs?: UniversityTab[];
}

export const higherEducationSections: HigherEducationSection[] = [
  {
    title: 'The List of Universities/Colleges for Higher Studies in USA',
    universities: [
      'Adelphi University', 'Agnes Scott College', 'Albertson College',
      'Albion College', 'Alfred University', 'Allegheny College',
      'Alma College', 'Alverno College', 'American University',
      'Amherst College', 'Antioch College', 'Arizona State University',
      'Auburn University', 'Austin College', 'Babson College',
      'Bard College', 'Barnard College', 'Bates College',
      'Baylor University', 'Beloit College', 'Bennington College',
      'Birmingham-Southern College', 'Boston College', 'Boston University',
      'Bowdoin College', 'Bradford College', 'Brandeis University',
      'Brigham Young University', 'Brooklyn College', 'Brown University',
      'Bryn Mawr College', 'Bucknell University', 'California Institute of Technology',
      'Calvin College', 'Carleton College', 'Carnegie Mellon University',
      'Case Western Reserve University', 'Centre College', 'City College of New York',
      'City College Of The City University Of New York', 'Claremont McKenna College', 'Clark University',
      'Clarkson University', 'Clemson University', 'Colby College',
      'Colgate University', 'College of Charleston', 'College of the Atlantic',
      'College of the Holy Cross', 'College of William and Mary', 'Colorado College',
      'Colorado School of Mines', 'Colorado State University', 'Columbia College',
      'Columbia University', 'Connecticut College', 'Cooper Union',
      'Cornell College', 'Cornell University', 'Dartmouth College',
      'Davidson College', 'Denison University', 'DePaul University',
      'DePauw University', 'Dickinson College', 'Drew University',
      'Drexel University', 'Duke University', 'Earlham College',
      'Eckerd College', 'Emory University', 'Fairfield University',
      'Florida Institute of Technology', 'Florida State University', 'Fordham University',
      'Franklin & Marshall College', 'Furman University', 'George Mason University',
      'George Washington University', 'George Washington University', 'Georgetown University',
      'Georgia Institute of Technology', 'Gettysburg College', 'Gordon College',
      'Goucher College', 'Grinnell College', 'Guilford College',
      'Gustavus Adolphus College', 'Hamilton College', 'Hampden-Sydney College',
      'Hampshire College', 'Hartwick College', 'Harvard University',
      'Harvey Mudd College', 'Haverford College', 'Hendrix College',
      'Hiram College', 'Hobart and William Smith Colleges', 'Hofstra University',
      'Hollins University', 'Hood College', 'Hope College',
      'Houghton College', 'Howard University', 'Hunter College',
      'Illinois Institute of Technology', 'Illinois Wesleyan University', 'Indiana University',
      'Iowa State University', 'Ithaca College', 'James Madison University',
      'Johns Hopkins University', 'Kalamazoo College', 'Kansas State University',
      'Kenyon College', 'Knox College', 'Lafayette College',
      'Lake Forest College', 'Lawrence University', 'Lehigh University',
      'Lewis and Clark College', 'Louisiana State University', 'Loyola University New Orleans',
      'Macalester College', 'Manhattanville College', 'Marlboro College',
      'Marquette University', 'Mary Washington College', 'Massachusetts Institute of Technology',
      'Miami University (OH)', 'Michigan State University', 'Michigan Technological University',
      'Middlebury College', 'Mills College', 'Millsaps College',
      'Mississippi State University', 'Montana Tech of the University of Montana', 'Morehouse College',
      'Mount Holyoke College', 'Muhlenberg College', 'New College of the University of South Florida',
      'New Jersey Institute of Technology', 'New Mexico Institute of Mining and Technology', 'New Mexico State University',
      'New School for Social Research-Eugene Lang College', 'New York State College Of Ceramics At Alfred University', 'New York University',
      'North Carolina State University', 'Northeastern University', 'Northwestern University',
      'Oberlin College', 'Occidental College', 'Oglethorpe University',
      'Ohio State University', 'Ohio University', 'Ohio Wesleyan University',
      'Oklahoma State University', 'Oregon State University', 'Pennsylvania State University',
      'Pepperdine University', 'Pitzer College', 'Polytechnic University',
      'Pomona College', 'Presbyterian College', 'Prescott College',
      'Princeton University', 'Principia College', 'Purdue University',
      'Queens College', "Randolph-Macon Woman's College", 'Reed College',
      'Renesselaer Polytechnic Institute', 'Rensselaer Polytechnic Institute', 'Rhode Island School of Design',
      'Rhodes College', 'Rice University', 'Ripon College',
      'Rochester Institute of Technology', 'Rollins College', 'Rose-Hulman Institute of Technology',
      'Rutgers-The State University of New Jersey', 'Saint Louis University', 'Santa Clara University',
      'Sarah Lawrence College', 'Scripps College', 'Skidmore College',
      'Smith College', 'Southern Methodist University', 'Southwestern University',
      'Spelman College', "St. John's College", "St. John's University and College of St. Benedict",
      'St. Lawrence University', "St. Mary's College of Maryland", 'St. Olaf College',
      'Stanford University', 'State University of New York – Binghamton', 'State University of New York – Buffalo',
      'Stetson University', 'Stevens Institute of Technology', 'SUNY-Albany',
      'SUNY-Binghamton University', 'SUNY-Buffalo', 'SUNY-Geneseo',
      'SUNY-Purchase College', 'SUNY-Stony Brook', 'Susquehanna University',
      'Swarthmore College', 'Sweet Briar College', 'Syracuse University',
      'Texas A&M University', 'Texas Christian University', 'Texas Tech University',
      'The Catholic University of America', 'The College of New Jersey', 'The College of Wooster',
      'The Evergreen State College', 'The Johns Hopkins University', 'Trinity College',
      'Trinity University', 'Tufts University', 'Tulane University',
      'UC-Berkeley', 'UC-Davis', 'UC-Irvine',
      'UC-Los Angeles', 'UC-Riverside', 'UC-San Diego',
      'UC-Santa Barbara', 'UC-Santa Cruz', 'Union College',
      'University of Chicago', 'University of Alabama', 'University Of Albama',
      'University of Arizona', 'University of Arizona', 'University of Arkansas',
      'University of California – Berkeley', 'University of California – Davis', 'University of California – Irvine',
      'University of California – Los Angeles', 'University of California – San Diego', 'University of California – Santa Barbara',
      'University of Cincinnati', 'University of Colorado at Boulder', 'University of Connecticut',
      'University of Dallas', 'University of Dayton', 'University of Delaware',
      'University of Denver', 'University of Florida', 'University of Georgia',
      'University of Hawaii at Manoa', 'University of Houston', 'University of Illinois at Urbana-Champaign',
      'University of Iowa', 'University of Kansas', 'University of Kentucky',
      'University of Maine-Orono', 'University of Maryland, College Park', 'University of Massachusetts – Lowell',
      'University of Massachusetts-Amherst', 'University of Miami', 'University of Michigan',
      'University of Minnesota', 'University of Minnesota-Morris', 'University of Minnesota-Twin Cities',
      'University of Missouri – Rolla', 'University of Missouri-Columbia', 'University of Nebraska at Lincoln',
      'University of New Hampshire', 'University of New Mexico', 'University of North Carolina at Asheville',
      'University of North Carolina at Chapel Hill', 'University of North Carolina at Greensboro', 'University of Notre Dame',
      'University of Oklahoma', 'University of Oregon', 'University of Pennsylvania',
      'University of Pittsburgh', 'University of Puget Sound', 'University of Redlands',
      'University of Rhode Island', 'University of Richmond', 'University of Rochester',
      'University of San Francisco', 'University of South Carolina', 'University of Southern California',
      'University of Tennessee at Knoxville', 'University of Texas – Arlington', 'University of Texas – Austin',
      'University of the Pacific', 'University of the South (Sewanee)', 'University of Toledo',
      'University of Tulsa', 'University of Utah', 'University of Vermont',
      'University of Virginia', 'University of Washington', 'University of Wisconsin – Madison',
      'University of Louisville', 'Ursinus College', 'Utah State University',
      'Vanderbilt University', 'Vassar College', 'Villanova University',
      'Virginia Polytechnic Institute and State University', 'Wabash College', 'Wake Forest University',
      'Washington and Jefferson College', 'Washington and Lee University', 'Washington University in St. Louis',
      'Wayne State University', 'Wellesley College', 'Wells College',
      'Wesleyan University', 'West Virginia University', 'Wheaton College',
      'Wheaton College', 'Whitman College', 'Whittier College',
      'Willamette University', 'Williams College', 'Wittenberg University',
      'Wofford College', 'Worcester Polytechnic Institute', 'Xavier University of Louisiana',
      'Yale University',
    ],
  },
  {
    title: 'The List of Universities/Colleges for Higher Studies in UK Australia Canada',
    tabs: [
      {
        label: 'UK',
        universities: [
          'University of Aberdeen',
          'Birmingham University',
          'University of Brighton',
          'Liverpool University',
          'University of Wales',
          'University of Winchester',
        ],
      },
      {
        label: 'Australia',
        universities: [
          'Griffith University',
          'Northern Territory University',
          'University of Adelaide',
          'Victoria University of Technology',
          'University of Ballarat',
          'University of Canberra',
          'University of Melbourne',
          'University of Queensland',
          'University of Sydney',
          'University of Tasmania',
        ],
      },
      {
        label: 'Canada',
        universities: [
          'Alberta Bible College',
          'Canadian University College',
          'Northern Lakes College',
          'Kingston College',
        ],
      },
    ],
  },
];
