// Full batch-wise placement records, sourced from the SVECW placement
// details page (svecw.edu.in/placement-details). Company names and figures
// are kept exactly as published there — including inconsistent spelling
// (e.g. "Delloitte"/"Deloitte", "Diamler"/"Daimler") and repeated company
// rows for different roles/packages within the same batch — rather than
// normalised, since this is meant to be a faithful copy of the source
// records rather than an edited summary.
export interface PlacementRow {
  company: string;
  selects: number;
  salary: string;
}

export interface BranchOfferCount {
  branch: string;
  offers: number;
  /** No. of students eligible for placements in this branch — when set,
   *  this becomes the denominator for that branch's placement-rate tile/
   *  donut label (offers / eligible × 100) instead of the batch total.
   *  Left unset where this figure isn't available, in which case that
   *  branch falls back to the older "share of the batch's total offers"
   *  reading (offers / batch total × 100). */
  eligible?: number;
}

export interface StudentPlacementRow {
  regdNo: string;
  branch: string;
  studentName: string;
  company: string;
  salary: string;
  offers: number;
}

export interface PlacementYear {
  batch: string;
  total: number | null;
  salaryLabel: string;
  rows: PlacementRow[];
  note?: string;
  /** Extra detail shown only on the Placement Details sub-page's "enriched"
   *  view for this batch — companies visited, branch-wise offer counts, and
   *  named student records — sourced from the site owner's own screenshot
   *  of that batch's detail page. Optional since only 2022–2026 has this
   *  level of detail so far. */
  companiesVisited?: number;
  branchOffers?: BranchOfferCount[];
  students?: StudentPlacementRow[];
}

export const placementYearData: PlacementYear[] = [
  {
    batch: '2022–2026',
    total: 1078,
    salaryLabel: 'Salary (₹)',
    companiesVisited: 102,
    // Offer counts are unchanged from the original source; `eligible` is
    // each branch's own eligible-student count, added separately (see the
    // 2022–2026 branch-wise placement register) so the tiles/donut can show
    // a genuine per-branch placement rate instead of a share of the total.
    // AI&ML and Cyber Security are tracked as their own CSE sub-branches
    // (not folded into the plain CSE row) since they're distinct programs.
    // MBA has no eligible figure on record, so it keeps reading as its
    // original share-of-total percentage (see branchPercentage's fallback).
    branchOffers: [
      { branch: 'AI&DS Offers', offers: 193, eligible: 137 },
      { branch: 'Civil Offers', offers: 36, eligible: 45 },
      { branch: 'CSE Offers', offers: 268, eligible: 207 },
      { branch: 'CSE(AI&ML) Offers', offers: 137, eligible: 126 },
      { branch: 'CSE(Cyber Security) Offers', offers: 66, eligible: 60 },
      { branch: 'ECE Offers', offers: 97, eligible: 127 },
      { branch: 'EEE Offers', offers: 78, eligible: 57 },
      { branch: 'IT Offers', offers: 191, eligible: 193 },
      { branch: 'MBA Offers', offers: 16 },
      { branch: 'Mech. Offers', offers: 60, eligible: 47 },
    ],
    students: [
      { regdNo: '22B01A4501', branch: 'CSE(AI&DS)', studentName: 'Addanki Nikhita', company: 'Capgemini', salary: '₹4,25,000', offers: 1 },
      { regdNo: '22B01A4502', branch: 'CSE(AI&DS)', studentName: 'Andugala Pujitha', company: 'INFOSYS', salary: '₹3,60,000', offers: 1 },
      { regdNo: '22B01A4506', branch: 'CSE(AI&DS)', studentName: 'Bajinki Komali', company: 'Cerevyn Solutions', salary: '₹4,00,000', offers: 1 },
      { regdNo: '22B01A4507', branch: 'CSE(AI&DS)', studentName: 'Bandaru Pavani', company: 'Dhan.AI', salary: '₹5,00,000', offers: 1 },
      { regdNo: '22B01A4508', branch: 'CSE(AI&DS)', studentName: 'Bandi Yuga Sri', company: 'Dhan.AI', salary: '₹5,00,000', offers: 1 },
      { regdNo: '22B01A4510', branch: 'CSE(AI&DS)', studentName: 'Bezawada Meghana Nayudu', company: 'Cognizant GenC Next', salary: '₹6,75,000', offers: 1 },
      { regdNo: '22B01A4511', branch: 'CSE(AI&DS)', studentName: 'Bondada Susanthi', company: 'INFOSYS', salary: '₹3,60,000', offers: 1 },
      { regdNo: '22B01A4511', branch: 'CSE(AI&DS)', studentName: 'Bondada Susanthi', company: 'Capgemini', salary: '₹4,25,000', offers: 1 },
      { regdNo: '22B01A4511', branch: 'CSE(AI&DS)', studentName: 'Bondada Susanthi', company: 'Amazon', salary: '₹46,38,000', offers: 1 },
      { regdNo: '22B01A4512', branch: 'CSE(AI&DS)', studentName: 'Bulusu Tejaswini', company: 'INFOSYS', salary: '₹3,60,000', offers: 1 },
    ],
    rows: [
      { company: 'Google', selects: 3, salary: '₹59,14,620' },
      { company: 'Meeshow', selects: 1, salary: '₹57,52,910' },
      { company: 'Adobe', selects: 4, salary: '₹53,35,000' },
      { company: 'Microsoft', selects: 1, salary: '₹52,00,000' },
      { company: 'Amazon', selects: 17, salary: '₹46,38,000' },
      { company: 'Intuit', selects: 4, salary: '₹45,48,500' },
      { company: 'Godaddy', selects: 2, salary: '₹33,97,000' },
      { company: 'Flipkart GWC 6.0', selects: 1, salary: '₹32,72,000' },
      { company: 'VISA', selects: 15, salary: '₹32,02,000' },
      { company: 'Myntra', selects: 1, salary: '₹30,50,000' },
      { company: 'Goldman Sache', selects: 2, salary: '₹30,00,000' },
      { company: 'CISCO', selects: 2, salary: '₹24,73,633' },
      { company: 'Walmart', selects: 1, salary: '₹18,50,000' },
      { company: 'IDFC FIRST Bank', selects: 1, salary: '₹16,00,000' },
      { company: 'HSBC Bank', selects: 53, salary: '₹15,03,097' },
      { company: 'IVANTI', selects: 1, salary: '₹12,00,000' },
      { company: 'Zenoti', selects: 1, salary: '₹11,64,538' },
      { company: 'Infosys SP', selects: 3, salary: '₹11,00,000' },
      { company: 'A.P. Moller Maersk', selects: 6, salary: '₹10,84,000' },
      { company: 'OneBanc', selects: 1, salary: '₹10,00,000' },
      { company: 'Cummins India', selects: 3, salary: '₹10,00,000' },
      { company: 'Infosys SP', selects: 14, salary: '₹9,50,000' },
      { company: 'Providence', selects: 3, salary: '₹9,50,000' },
      { company: 'TCS Prime', selects: 2, salary: '₹9,09,360' },
      { company: 'TCS Prime', selects: 1, salary: '₹9,09,360' },
      { company: 'EPAM', selects: 1, salary: '₹8,00,000' },
      { company: 'TVS BAJA', selects: 2, salary: '₹8,00,000' },
      { company: 'DarwinBox', selects: 1, salary: '₹8,00,000' },
      { company: 'TVS Motors', selects: 1, salary: '₹8,00,000' },
      { company: 'State Street', selects: 5, salary: '₹8,00,000' },
      { company: 'Mahindra & Mahindra', selects: 5, salary: '₹8,00,000' },
      { company: 'Daimler Truck', selects: 2, salary: '₹7,50,000' },
      { company: 'Capgemini', selects: 1, salary: '₹7,25,000' },
      { company: 'TCS Digital', selects: 18, salary: '₹7,09,380' },
      { company: 'Infosys SP', selects: 7, salary: '₹7,00,000' },
      { company: 'Vedanta', selects: 12, salary: '₹7,00,000' },
      { company: 'Evernorth', selects: 1, salary: '₹7,00,000' },
      { company: 'Elythra Edufyi Tech Solutions', selects: 4, salary: '₹7,00,000' },
      { company: 'Alstom', selects: 5, salary: '₹6,80,000' },
      { company: 'Verolax LLC', selects: 1, salary: '₹6,80,000' },
      { company: 'Cognizant GenC NXT', selects: 13, salary: '₹6,75,000' },
      { company: 'Infosys DSE', selects: 45, salary: '₹6,50,000' },
      { company: 'Atlas Copco', selects: 15, salary: '₹6,30,000' },
      { company: 'Fractal Analytics', selects: 3, salary: '₹6,00,000' },
      { company: 'Bounteous x Accolite', selects: 1, salary: '₹6,00,000' },
      { company: 'Epiroc', selects: 6, salary: '₹6,00,000' },
      { company: 'Material Depot', selects: 5, salary: '₹6,00,000' },
      { company: 'Capgemini PLM', selects: 19, salary: '₹5,75,000' },
      { company: 'Capgemini', selects: 9, salary: '₹5,75,000' },
      { company: 'Siemens SPEL', selects: 1, salary: '₹5,50,000' },
      { company: 'JSW', selects: 5, salary: '₹5,50,000' },
      { company: 'Quentelli', selects: 27, salary: '₹5,50,000' },
      { company: 'Future Flex', selects: 1, salary: '₹5,40,000' },
      { company: 'Kyndryl', selects: 2, salary: '₹5,20,000' },
      { company: 'Dhan.AI', selects: 8, salary: '₹5,00,000' },
      { company: 'Tata Consulting Engineers', selects: 1, salary: '₹5,00,000' },
      { company: 'zeta', selects: 1, salary: '₹5,00,000' },
      { company: 'Simplotel', selects: 2, salary: '₹4,70,000' },
      { company: 'IBM', selects: 14, salary: '₹4,50,000' },
      { company: 'PalTech', selects: 1, salary: '₹4,50,000' },
      { company: 'Tata Consulting Engineers', selects: 9, salary: '₹4,50,000' },
      { company: 'Capgemini PLM', selects: 50, salary: '₹4,25,000' },
      { company: 'Capgemini MEDA', selects: 9, salary: '₹4,25,000' },
      { company: 'Sify', selects: 3, salary: '₹4,25,000' },
      { company: 'Capgemini', selects: 116, salary: '₹4,25,000' },
      { company: 'Accenture', selects: 2, salary: '₹4,25,000' },
      { company: 'Quest Global', selects: 4, salary: '₹4,00,000' },
      { company: 'Rhombuz Design Pvt Ltd', selects: 1, salary: '₹4,00,000' },
      { company: 'Cognizant GenC', selects: 63, salary: '₹4,00,000' },
      { company: 'Zodiac Life Sciences', selects: 1, salary: '₹4,00,000' },
      { company: 'Frugal Testing', selects: 1, salary: '₹4,00,000' },
      { company: 'Intrainz Innovation', selects: 1, salary: '₹4,00,000' },
      { company: 'Olectra Greentech Ltd.', selects: 9, salary: '₹4,00,000' },
      { company: 'Delloitte', selects: 10, salary: '₹4,00,000' },
      { company: 'Qualizeal', selects: 3, salary: '₹4,00,000' },
      { company: 'Bimazed Engineers Pvt Ltd.', selects: 1, salary: '₹4,00,000' },
      { company: 'Cerevyn Solutions', selects: 3, salary: '₹4,00,000' },
      { company: 'Amar Raja Batteries', selects: 2, salary: '₹4,00,000' },
      { company: 'Kantar', selects: 1, salary: '₹4,00,000' },
      { company: 'Infosys', selects: 279, salary: '₹3,60,000' },
      { company: 'ASIP Semiconductor', selects: 1, salary: '₹3,60,000' },
      { company: 'Renault Nissan', selects: 7, salary: '₹3,50,000' },
      { company: 'TTEC', selects: 10, salary: '₹3,48,000' },
      { company: 'TCS Ninja', selects: 15, salary: '₹3,46,277' },
      { company: 'Triveni Earth Movers', selects: 7, salary: '₹3,30,000' },
      { company: 'Movate', selects: 7, salary: '₹3,30,000' },
      { company: 'AquaSub', selects: 2, salary: '₹3,23,000' },
      { company: 'Sai Sindhura Constructions', selects: 1, salary: '₹3,09,000' },
      { company: 'Arshith Fresh', selects: 3, salary: '₹3,00,000' },
      { company: 'HBL', selects: 1, salary: '₹3,00,000' },
      { company: 'EASPL', selects: 1, salary: '₹3,00,000' },
      { company: 'SLV Interiors, Hyd', selects: 3, salary: '₹2,44,000' },
      { company: 'Kaynes-Manesar', selects: 7, salary: '₹2,40,000' },
      { company: 'Aaviza Electronics', selects: 23, salary: '₹2,40,000' },
      { company: 'BARSYL', selects: 6, salary: '₹2,40,000' },
      { company: 'NVLN Constructions', selects: 3, salary: '₹2,40,000' },
      { company: 'AquagenixPro Private Limited', selects: 4, salary: '₹2,40,000' },
      { company: 'Ultratech Cement', selects: 2, salary: '₹2,16,000' },
      { company: 'Formonic Technologies', selects: 1, salary: '₹2,16,000' },
      { company: 'PoloSoft Tech', selects: 15, salary: '₹2,00,000' },
      { company: 'TechWave', selects: 2, salary: '₹2,00,000' },
      { company: 'Sayantrik Engineer India Pvt. Ltd', selects: 1, salary: '₹1,44,000' },
    ],
  },
  {
    batch: '2021–2025',
    total: 1156,
    salaryLabel: 'Salary (LPA)',
    companiesVisited: 71,
    branchOffers: [
      { branch: 'AIDS Offers', offers: 193 },
      { branch: 'Civil Offers', offers: 43 },
      { branch: 'CSE Offers', offers: 310 },
      { branch: 'ECE Offers', offers: 129 },
      { branch: 'EEE Offers', offers: 56 },
      { branch: 'IT Offers', offers: 273 },
      { branch: 'MBA Offers', offers: 2 },
      { branch: 'Mech. Offers', offers: 59 },
    ],
    rows: [
      { company: 'GoDaddy', selects: 1, salary: '21.00' },
      { company: 'Adobe', selects: 4, salary: '45.00' },
      { company: 'Paypal', selects: 1, salary: '34.00' },
      { company: 'VISA', selects: 8, salary: '31.00' },
      { company: 'Goldmen Sach', selects: 1, salary: '24.00' },
      { company: 'Google', selects: 1, salary: '21.00' },
      { company: 'DarwinBox', selects: 1, salary: '16.00' },
      { company: 'Reltio', selects: 3, salary: '15.00' },
      { company: 'Infineon', selects: 4, salary: '11.00' },
      { company: 'Akriva HCM', selects: 1, salary: '12.00' },
      { company: 'IBM', selects: 4, salary: '11.00' },
      { company: 'OpenText', selects: 36, salary: '11.00' },
      { company: 'Providence', selects: 4, salary: '10.00' },
      { company: 'Infosys SP', selects: 30, salary: '9.00' },
      { company: 'Fidelity International', selects: 6, salary: '9.00' },
      { company: 'PG Alstom', selects: 5, salary: '8.00' },
      { company: 'Alstom', selects: 7, salary: '6.00' },
      { company: 'Publicis Sapient', selects: 4, salary: '8.00' },
      { company: 'TVS Motor', selects: 5, salary: '8.00' },
      { company: 'Diamler Truck', selects: 1, salary: '10.00' },
      { company: 'Diamler Truck', selects: 3, salary: '7.00' },
      { company: 'Anand-ANEVOLVE Head Springs', selects: 1, salary: '7.00' },
      { company: 'TCS Digital', selects: 1, salary: '7.00' },
      { company: 'Accenture Adv ASE', selects: 1, salary: '6.00' },
      { company: 'Bank of America', selects: 10, salary: '6.00' },
      { company: 'Infosys Digtal Specialist Engineer', selects: 15, salary: '6.00' },
      { company: 'Worley', selects: 2, salary: '5.00' },
      { company: 'Capgemini PLM', selects: 9, salary: '5.00' },
      { company: 'Capgemini Senior Software Engineer', selects: 33, salary: '7.00' },
      { company: 'Capgemini Sofware Engineer', selects: 50, salary: '5.00' },
      { company: 'Capgemini Wireless', selects: 3, salary: '5.00' },
      { company: 'Capgemini PLM', selects: 25, salary: '4.00' },
      { company: 'Capgemini MEDA', selects: 12, salary: '4.00' },
      { company: 'Capgemini Sofware Engineer', selects: 297, salary: '4.00' },
      { company: 'Siemens', selects: 3, salary: '5.00' },
      { company: 'TechMahindra (CoE)', selects: 27, salary: '5.00' },
      { company: 'Atlas Copco', selects: 4, salary: '5.00' },
      { company: 'Siemens SPEL', selects: 2, salary: '5.00' },
      { company: 'Qentelli', selects: 2, salary: '5.00' },
      { company: 'KPMG', selects: 1, salary: '5.00' },
      { company: 'Dhan.AI', selects: 2, salary: '5.00' },
      { company: 'JSW', selects: 1, salary: '4.00' },
      { company: 'Accenture ASE', selects: 250, salary: '4.00' },
      { company: 'KPIT', selects: 55, salary: '4.00' },
      { company: 'Tata Consulting Engineer(TCE)', selects: 6, salary: '4.00' },
      { company: 'Renault Nissan Baja', selects: 3, salary: '4.00' },
      { company: 'Renault Nissan', selects: 11, salary: '4.00' },
      { company: 'Cognizant GenC', selects: 47, salary: '4.00' },
      { company: 'Infosys Systems Engineer', selects: 49, salary: '3.00' },
      { company: 'IBM CIC', selects: 8, salary: '3.00' },
      { company: 'Amazon Quality Specialsit', selects: 4, salary: '3.00' },
      { company: 'D-Mart (MBA)', selects: 1, salary: '3.00' },
      { company: 'Movate(Enterprise Product Services)', selects: 1, salary: '3.00' },
      { company: 'Frugal Testing (MBA)', selects: 1, salary: '3.00' },
      { company: 'Cadsystech', selects: 3, salary: '3.00' },
      { company: 'Clove Technologies', selects: 13, salary: '2.00' },
      { company: 'Gowra Ventures', selects: 4, salary: '2.00' },
      { company: 'SHAA Associates Infrastructure India Pvt.Ltd', selects: 2, salary: '2.00' },
      { company: 'NXP', selects: 3, salary: '17.00' },
      { company: 'Mahindra & Mahindra', selects: 15, salary: '8.00' },
      { company: 'Synopsys', selects: 1, salary: '8.00' },
      { company: 'Flipkart', selects: 2, salary: '32.00' },
      { company: 'Athena Health', selects: 6, salary: '11.00' },
      { company: 'MRF Tires', selects: 25, salary: '2.00' },
      { company: 'Flipkart Neev', selects: 2, salary: '13.00' },
      { company: 'Amazon', selects: 5, salary: '46.00' },
      { company: 'Tata Electronics', selects: 1, salary: '6.00' },
      { company: 'Prodapt', selects: 1, salary: '8.00' },
      { company: 'A.P. Mollar Maersk', selects: 4, salary: '10.00' },
      { company: 'Target', selects: 1, salary: '13.00' },
      { company: 'Zeta', selects: 1, salary: '16.00' },
    ],
  },
  {
    batch: '2020–2024',
    total: 818,
    salaryLabel: 'Salary (LPA)',
    companiesVisited: 70,
    branchOffers: [
      { branch: 'AIDS Offers', offers: 90 },
      { branch: 'Civil Offers', offers: 14 },
      { branch: 'CSE Offers', offers: 239 },
      { branch: 'ECE Offers', offers: 136 },
      { branch: 'EEE Offers', offers: 81 },
      { branch: 'IT Offers', offers: 204 },
      { branch: 'MBA Offers', offers: 3 },
      { branch: 'Mech. Offers', offers: 51 },
    ],
    rows: [
      { company: 'Intuit', selects: 1, salary: '41.54' },
      { company: 'VISA', selects: 11, salary: '32.70' },
      { company: 'Analog Devices', selects: 1, salary: '25.43' },
      { company: 'Walmart', selects: 1, salary: '22.27' },
      { company: 'D.E.Shaw', selects: 1, salary: '21.00' },
      { company: 'NXP', selects: 1, salary: '16.48' },
      { company: 'Target Corp', selects: 2, salary: '13.50' },
      { company: 'Flipkart Neev', selects: 1, salary: '13.00' },
      { company: 'Publicis Sapient', selects: 7, salary: '12.47' },
      { company: 'IBM ISDL', selects: 3, salary: '12.00' },
      { company: 'Flipkart', selects: 3, salary: '11.00' },
      { company: 'Providence', selects: 2, salary: '10.50' },
      { company: 'Infosys', selects: 6, salary: '9.50' },
      { company: 'Hero Motocorp', selects: 9, salary: '9.00' },
      { company: 'Wabtec Corp', selects: 2, salary: '8.50' },
      { company: 'Sales Force', selects: 2, salary: '8.25' },
      { company: 'Hyundai Motors', selects: 8, salary: '8.05' },
      { company: 'TVS Motors', selects: 6, salary: '8.00' },
      { company: 'Schlumberger', selects: 1, salary: '8.00' },
      { company: 'Michelin', selects: 2, salary: '8.00' },
      { company: 'Infineon', selects: 7, salary: '8.00' },
      { company: 'Mahindra & Mahindra', selects: 21, salary: '8.00' },
      { company: 'Daimler Truck', selects: 4, salary: '7.50' },
      { company: 'Hitachi Energy', selects: 1, salary: '7.50' },
      { company: 'Health Edge', selects: 1, salary: '7.50' },
      { company: 'MG Motors', selects: 2, salary: '7.00' },
      { company: 'Saint Gobain', selects: 2, salary: '7.00' },
      { company: 'TCS Digital', selects: 11, salary: '7.00' },
      { company: 'Verizon', selects: 10, salary: '6.60' },
      { company: 'Accenture', selects: 1, salary: '6.50' },
      { company: 'Schlumberger Cameron', selects: 1, salary: '6.50' },
      { company: 'Bank of America', selects: 31, salary: '6.45' },
      { company: 'Cognizant', selects: 1, salary: '6.40' },
      { company: 'Sify', selects: 30, salary: '6.00' },
      { company: 'ADP', selects: 3, salary: '6.00' },
      { company: 'ZF Motor Vehicle Control Systems', selects: 1, salary: '6.00' },
      { company: 'Epiroc', selects: 1, salary: '6.00' },
      { company: 'Grindwell Norton', selects: 1, salary: '5.70' },
      { company: 'Siemens Energy', selects: 2, salary: '5.50' },
      { company: 'Schnider Electric', selects: 7, salary: '5.50' },
      { company: 'Cognizant', selects: 9, salary: '5.40' },
      { company: 'Health Edge Technologies', selects: 4, salary: '5.20' },
      { company: 'Worley', selects: 1, salary: '5.15' },
      { company: 'Dhan.Ai', selects: 3, salary: '5.00' },
      { company: 'Persistent Systems', selects: 11, salary: '5.00' },
      { company: 'Delliotte', selects: 16, salary: '5.00' },
      { company: 'SuperGAS', selects: 2, salary: '4.75' },
      { company: 'Accenture', selects: 137, salary: '4.50' },
      { company: 'KPIT', selects: 90, salary: '4.50' },
      { company: 'TATA Technologies', selects: 2, salary: '4.50' },
      { company: 'Kellog Brown & Roots Engineering and Construction (KBR)', selects: 1, salary: '4.50' },
      { company: 'IBM CIC', selects: 6, salary: '4.50' },
      { company: 'Cyient', selects: 1, salary: '4.50' },
      { company: 'Tata Consulting Engineer', selects: 5, salary: '4.50' },
      { company: 'Cognizant GenC', selects: 7, salary: '4.50' },
      { company: 'Renault Nissan', selects: 39, salary: '4.25' },
      { company: 'Genpact', selects: 33, salary: '4.17' },
      { company: 'Qualizeal', selects: 43, salary: '4.00' },
      { company: 'Capgemini', selects: 122, salary: '4.00' },
      { company: 'Endurance Technologies', selects: 1, salary: '3.75' },
      { company: 'Vem Technologies', selects: 1, salary: '3.50' },
      { company: 'Amazon Non Technical', selects: 5, salary: '3.50' },
      { company: 'TCS Ninja', selects: 2, salary: '3.50' },
      { company: 'TCS NQT', selects: 17, salary: '3.50' },
      { company: 'Tech Mahindra', selects: 39, salary: '3.25' },
      { company: 'Chart Industries', selects: 2, salary: '3.25' },
      { company: 'Movate', selects: 6, salary: '2.40' },
      { company: 'Formonic', selects: 2, salary: '2.16' },
      { company: 'Amara Raja Batteries(MBA)', selects: 1, salary: '4.00' },
      { company: 'D-Mart (MBA)', selects: 2, salary: '3.00' },
    ],
  },
  {
    batch: '2019–2023',
    total: 1474,
    salaryLabel: 'Salary (LPA)',
    companiesVisited: 82,
    branchOffers: [
      { branch: 'CSE Offers', offers: 476 },
      { branch: 'IT Offers', offers: 261 },
      { branch: 'ECE Offers', offers: 347 },
      { branch: 'EEE Offers', offers: 200 },
      { branch: 'Civil Offers', offers: 72 },
      { branch: 'Mechanical Offers', offers: 102 },
      { branch: 'MBA Offers', offers: 16 },
    ],
    rows: [
      { company: 'Adobe', selects: 1, salary: '41.00' },
      { company: 'NXP', selects: 1, salary: '23.00' },
      { company: 'Lowei', selects: 1, salary: '19.40' },
      { company: 'DarwinBox', selects: 1, salary: '16.30' },
      { company: 'Target Corporation', selects: 2, salary: '13.84' },
      { company: 'Flipkart Neev Internship', selects: 2, salary: '13.52' },
      { company: 'Publics Sapiant', selects: 20, salary: '12.47' },
      { company: 'Athena Health', selects: 3, salary: '12.00' },
      { company: 'Amadeus', selects: 2, salary: '11.77' },
      { company: 'Optum', selects: 69, salary: '11.77' },
      { company: 'IBM(ISDL)', selects: 1, salary: '11.77' },
      { company: 'State Street', selects: 10, salary: '11.77' },
      { company: 'Caterpillar', selects: 3, salary: '11.77' },
      { company: 'Brillio', selects: 10, salary: '11.77' },
      { company: 'Providence', selects: 3, salary: '9.50' },
      { company: 'General Motors', selects: 1, salary: '9.45' },
      { company: 'Applied Materials', selects: 2, salary: '9.10' },
      { company: 'DBS', selects: 6, salary: '9.00' },
      { company: 'Michelin', selects: 1, salary: '8.90' },
      { company: 'Caterpillar', selects: 1, salary: '8.89' },
      { company: 'Zenoti', selects: 12, salary: '8.64' },
      { company: 'Tiger Analytics', selects: 19, salary: '8.50' },
      { company: 'Hero Motocorp (R&D)(Plant)', selects: 11, salary: '8.50' },
      { company: 'Sales Force', selects: 2, salary: '8.25' },
      { company: 'EPAM', selects: 26, salary: '8.00' },
      { company: 'Sterilite Technologies', selects: 24, salary: '8.00' },
      { company: 'Mercedus Benz', selects: 8, salary: '8.00' },
      { company: 'Mahindra & Mahindra', selects: 3, salary: '8.00' },
      { company: 'Capgemini Senior Analyst', selects: 5, salary: '7.50' },
      { company: 'Forbes Marshall', selects: 1, salary: '7.50' },
      { company: 'Verizon', selects: 8, salary: '7.20' },
      { company: 'TCS NQT', selects: 12, salary: '7.00' },
      { company: 'HPE', selects: 2, salary: '7.00' },
      { company: 'Technip FMC', selects: 3, salary: '6.91' },
      { company: 'Cognizant GenC Next - Select', selects: 10, salary: '6.75' },
      { company: 'Latent View', selects: 5, salary: '6.70' },
      { company: 'Accenture AASE', selects: 5, salary: '6.50' },
      { company: 'Kaar Technologies', selects: 2, salary: '6.50' },
      { company: 'Bank of America', selects: 29, salary: '6.45' },
      { company: 'Saint Gobian', selects: 4, salary: '6.30' },
      { company: 'Hack with Infy (HWI)', selects: 7, salary: '6.25' },
      { company: 'Persistent', selects: 9, salary: '6.00' },
      { company: 'Hexaware', selects: 2, salary: '6.00' },
      { company: 'Stellantis', selects: 1, salary: '6.00' },
      { company: 'Epiroc', selects: 5, salary: '6.00' },
      { company: 'Capgemini Analyst', selects: 20, salary: '5.75' },
      { company: 'Faurecia', selects: 3, salary: '5.50' },
      { company: 'Copart', selects: 1, salary: '5.50' },
      { company: 'Amdocs', selects: 4, salary: '5.30' },
      { company: 'Torry Harris', selects: 57, salary: '5.00' },
      { company: 'PwC', selects: 91, salary: '5.00' },
      { company: 'Lennox', selects: 1, salary: '5.00' },
      { company: 'Mu Sigma', selects: 23, salary: '5.00' },
      { company: 'Renew Power', selects: 28, salary: '5.00' },
      { company: 'Accenture ASE', selects: 149, salary: '4.50' },
      { company: 'PIE Infocomm', selects: 2, salary: '4.50' },
      { company: 'Dhan.Ai', selects: 1, salary: '4.50' },
      { company: 'Delloite', selects: 8, salary: '4.50' },
      { company: 'Capgemini Analyst', selects: 218, salary: '4.25' },
      { company: 'HCL', selects: 13, salary: '4.25' },
      { company: 'Cognizant GenC - Select', selects: 181, salary: '4.00' },
      { company: 'Urjanet', selects: 2, salary: '4.00' },
      { company: 'L & T Technologies', selects: 42, salary: '4.00' },
      { company: 'TeachNook', selects: 64, salary: '4.00' },
      { company: 'Qualizeal', selects: 8, salary: '4.00' },
      { company: 'CGI', selects: 43, salary: '3.93' },
      { company: 'Infytq', selects: 8, salary: '3.60' },
      { company: 'Genpact', selects: 14, salary: '3.60' },
      { company: 'Infosys', selects: 15, salary: '3.60' },
      { company: 'My Capitan', selects: 1, salary: '3.50' },
      { company: 'Codevita#10', selects: 5, salary: '3.36' },
      { company: 'Tech Mahindra', selects: 27, salary: '3.20' },
      { company: 'CADSYS', selects: 1, salary: '3.00' },
      { company: 'Focus Edumatics', selects: 52, salary: '2.50' },
      { company: 'TropoLeap', selects: 3, salary: '4.00' },
      { company: 'Cleartrip via Flipkart', selects: 1, salary: '32.57' },
      { company: 'Bank of America', selects: 8, salary: '6.00' },
      { company: 'CITTA Solutions(MBA)', selects: 2, salary: '5.00' },
      { company: 'NJ Group(MBA)', selects: 2, salary: '5.50' },
      { company: 'FACTSET(MBA)', selects: 8, salary: '3.25' },
      { company: 'LQube(MBA)', selects: 2, salary: '3.00' },
      { company: 'ESAF', selects: 1, salary: '3.00' },
    ],
  },
  {
    batch: '2018–2022',
    total: 1892,
    salaryLabel: 'Salary (LPA)',
    rows: [
      { company: 'Paloalto', selects: 2, salary: '49.00' },
      { company: 'Microsoft', selects: 1, salary: '44.30' },
      { company: 'Adobe', selects: 1, salary: '41.00' },
      { company: 'Expedia', selects: 4, salary: '37.40' },
      { company: 'Myntra', selects: 5, salary: '27.00' },
      { company: 'Flipkart', selects: 5, salary: '26.57' },
      { company: 'Cloudera', selects: 1, salary: '22.70' },
      { company: 'Walmart', selects: 1, salary: '22.39' },
      { company: 'Deshaw', selects: 1, salary: '20.00' },
      { company: 'Wells Fargo', selects: 2, salary: '20.00' },
      { company: 'VMWare', selects: 3, salary: '19.97' },
      { company: 'Experian', selects: 2, salary: '15.12' },
      { company: 'JP Morgan', selects: 1, salary: '14.00' },
      { company: 'NCR', selects: 6, salary: '14.00' },
      { company: 'BNY MELLON', selects: 2, salary: '14.00' },
      { company: 'F5', selects: 2, salary: '14.00' },
      { company: 'Amazon', selects: 3, salary: '13.00' },
      { company: 'Providence', selects: 2, salary: '12.00' },
      { company: 'Zenoti – Software Engineer', selects: 5, salary: '11.73' },
      { company: 'NAVIS – Associate Software Engineer', selects: 1, salary: '11.60' },
      { company: 'Athena Health', selects: 8, salary: '11.00' },
      { company: 'Optum', selects: 54, salary: '10.00' },
      { company: 'NAVIS – Associate Consultant', selects: 1, salary: '10.00' },
      { company: 'HPE', selects: 3, salary: '10.00' },
      { company: 'Providence – Service Engineer', selects: 1, salary: '9.00' },
      { company: 'FactSet', selects: 6, salary: '8.91' },
      { company: 'Halliburton', selects: 1, salary: '8.68' },
      { company: 'Intellipaat Software Solutions', selects: 1, salary: '8.65' },
      { company: 'State Street Corp', selects: 12, salary: '8.60' },
      { company: 'DBS Bank', selects: 3, salary: '8.50' },
      { company: 'Caterpillar', selects: 6, salary: '8.05' },
      { company: 'OpenText', selects: 28, salary: '8.00' },
      { company: 'Delhivery', selects: 3, salary: '8.00' },
      { company: 'Persistent – Higer Package(Viveka)', selects: 6, salary: '7.50' },
      { company: 'CAPGEMINI – Senior Analyst', selects: 7, salary: '7.50' },
      { company: 'Informatica', selects: 2, salary: '7.40' },
      { company: 'Zenoti – Implementation Cosnsultant', selects: 8, salary: '7.23' },
      { company: 'IBM-CIO', selects: 14, salary: '7.20' },
      { company: 'Aptean – Bangalore', selects: 15, salary: '7.02' },
      { company: 'Dell', selects: 2, salary: '7.00' },
      { company: 'TCS Digital', selects: 10, salary: '7.00' },
      { company: 'Zemoso', selects: 3, salary: '6.89' },
      { company: 'Cognizant – GenC Next', selects: 13, salary: '6.75' },
      { company: 'Accenture – Advanced ASE', selects: 53, salary: '6.60' },
      { company: 'Publicis Sapient', selects: 6, salary: '6.50' },
      { company: 'Kaar Technologies', selects: 3, salary: '6.50' },
      { company: 'Verizon', selects: 16, salary: '6.50' },
      { company: 'Latent view', selects: 7, salary: '6.50' },
      { company: 'Mahindra & Mahindra', selects: 18, salary: '6.50' },
      { company: 'Saint Gobain', selects: 10, salary: '6.30' },
      { company: 'Infosys – HWI Digital Specialist Engineer', selects: 16, salary: '6.25' },
      { company: 'Bank of America', selects: 10, salary: '6.00' },
      { company: 'Price Water Coopers (PwC)', selects: 21, salary: '6.00' },
      { company: 'EPAM', selects: 6, salary: '6.00' },
      { company: 'Tek Systems – Trainee Engineer', selects: 4, salary: '6.00' },
      { company: 'MAQ', selects: 8, salary: '6.00' },
      { company: 'XPO', selects: 3, salary: '6.00' },
      { company: 'SS&C', selects: 3, salary: '6.00' },
      { company: 'Epiroc', selects: 5, salary: '6.00' },
      { company: 'Rockwell Automation', selects: 4, salary: '6.00' },
      { company: 'Aptean – Madurai', selects: 11, salary: '5.94' },
      { company: 'Cameron Schlumberger', selects: 4, salary: '5.94' },
      { company: 'TA Digital', selects: 7, salary: '5.70' },
      { company: 'Zoho', selects: 5, salary: '5.60' },
      { company: 'GEP', selects: 2, salary: '5.50' },
      { company: 'JSW', selects: 4, salary: '5.50' },
      { company: 'Seneca Global', selects: 6, salary: '5.25' },
      { company: 'Amdocs', selects: 5, salary: '5.20' },
      { company: 'ProKarma Global', selects: 5, salary: '5.00' },
      { company: 'Accolite', selects: 6, salary: '5.00' },
      { company: 'Harman – A Samsung Company', selects: 15, salary: '5.00' },
      { company: 'Technovert – Full Stack Developer', selects: 2, salary: '5.00' },
      { company: 'Hexaware', selects: 4, salary: '5.00' },
      { company: 'Lumen', selects: 4, salary: '5.00' },
      { company: 'Persistent – Base Package(Navayauga)', selects: 82, salary: '4.71' },
      { company: 'ATKINS', selects: 3, salary: '4.57' },
      { company: 'Accenture – ASE', selects: 201, salary: '4.50' },
      { company: 'Technovert (Software Engineer – Data & Analytics)', selects: 4, salary: '4.50' },
      { company: 'Faurecia', selects: 9, salary: '4.50' },
      { company: 'Aizen Algo', selects: 1, salary: '4.50' },
      { company: 'Brillio', selects: 6, salary: '4.50' },
      { company: 'Hyundai Mobis', selects: 2, salary: '4.50' },
      { company: 'Symphony Retail', selects: 7, salary: '4.50' },
      { company: 'IBM', selects: 1, salary: '4.50' },
      { company: 'Flexibility', selects: 1, salary: '4.40' },
      { company: 'Capgemini – Analyst', selects: 146, salary: '4.00' },
      { company: 'Virtusa – Neural Hack', selects: 54, salary: '4.00' },
      { company: 'Virtusa – Campus Hiring', selects: 7, salary: '4.00' },
      { company: 'Hexaware', selects: 20, salary: '4.00' },
      { company: 'Zensar', selects: 10, salary: '4.00' },
      { company: 'Sunera', selects: 28, salary: '4.00' },
      { company: 'Verzeo', selects: 4, salary: '4.00' },
      { company: 'Cognizant – GenC', selects: 74, salary: '4.00' },
      { company: 'Cognizant – GenC Elevate (4 LPA+ Skill Bonus)', selects: 24, salary: '4.00' },
      { company: 'LTTS', selects: 29, salary: '4.00' },
      { company: 'Frugal Testing', selects: 1, salary: '4.00' },
      { company: 'Infosys – HWI Systems Engineer', selects: 5, salary: '3.60' },
      { company: 'Infosys – Infytq', selects: 7, salary: '3.60' },
      { company: 'Infosys', selects: 92, salary: '3.60' },
      { company: 'HCL', selects: 3, salary: '3.60' },
      { company: 'WIPRO', selects: 265, salary: '3.50' },
      { company: 'MuSigma', selects: 84, salary: '3.50' },
      { company: 'Mindtree', selects: 1, salary: '3.50' },
      { company: 'TCS Ninja', selects: 142, salary: '3.36' },
      { company: 'CSS Corp', selects: 9, salary: '3.20' },
      { company: 'Teachnook', selects: 15, salary: '3.00' },
      { company: 'Quest Global', selects: 1, salary: '3.00' },
      { company: 'ARI', selects: 3, salary: '3.00' },
      { company: 'FACE', selects: 6, salary: '3.00' },
      { company: 'Skolar', selects: 5, salary: '2.20' },
      { company: 'FactSet', selects: 2, salary: '3.22' },
      { company: 'SS&C', selects: 3, salary: '6.00' },
      { company: 'Sobha Constructions, Dubai', selects: 1, salary: '48,000 AED' },
      { company: 'Intellipaat Software Solutions', selects: 4, salary: '9.00' },
    ],
  },
  {
    batch: '2017–2021',
    total: 933,
    salaryLabel: 'Salary (LPA)',
    rows: [
      { company: 'Paloalto', selects: 2, salary: '41.00' },
      { company: 'Amazon', selects: 3, salary: '24.05' },
      { company: 'Flipkart', selects: 6, salary: '26.57' },
      { company: 'F5', selects: 1, salary: '23.00' },
      { company: 'Adobe', selects: 1, salary: '22.74' },
      { company: 'Walmart', selects: 1, salary: '20.00' },
      { company: 'BNY Mellon', selects: 2, salary: '18.00' },
      { company: 'Providence', selects: 2, salary: '16.00' },
      { company: 'Cisco', selects: 2, salary: '15.00' },
      { company: 'Expedia', selects: 2, salary: '13.00' },
      { company: 'American Express', selects: 2, salary: '12.00' },
      { company: 'Target Corporation', selects: 2, salary: '11.73' },
      { company: 'Caterpillar', selects: 5, salary: '10.30' },
      { company: 'Athena Health', selects: 4, salary: '9.60' },
      { company: 'HackwithInfy – Power Programmer', selects: 2, salary: '8.00' },
      { company: 'HackwithInfy – System Engineer', selects: 13, salary: '5.00' },
      { company: 'HackwithInfy', selects: 3, salary: '3.60' },
      { company: 'Infy TQ', selects: 2, salary: '5.00' },
      { company: 'Infy TQ', selects: 17, salary: '3.60' },
      { company: 'Delhivery', selects: 4, salary: '8.00' },
      { company: 'DBS Bank', selects: 5, salary: '8.00' },
      { company: 'Wiley', selects: 6, salary: '8.00' },
      { company: 'Smart Interviews', selects: 1, salary: '8.00' },
      { company: 'Amadeus', selects: 1, salary: '7.75' },
      { company: 'Micron Technology', selects: 1, salary: '7.40' },
      { company: 'Informatica', selects: 1, salary: '7.45' },
      { company: 'TCS Digital', selects: 19, salary: '7.00' },
      { company: 'NCR', selects: 2, salary: '7.00' },
      { company: 'IVY Comptech', selects: 5, salary: '6.95' },
      { company: 'Capgemini', selects: 4, salary: '6.80' },
      { company: 'Capegemini-2', selects: 90, salary: '3.80' },
      { company: 'Accenture', selects: 7, salary: '6.50' },
      { company: 'Accenture-2', selects: 114, salary: '4.50' },
      { company: 'Saint Gobain', selects: 1, salary: '6.30' },
      { company: 'Accolite', selects: 2, salary: '6.00' },
      { company: 'EPAM', selects: 7, salary: '6.00' },
      { company: 'MAQ Software', selects: 1, salary: '6.00' },
      { company: 'Edgeverve', selects: 2, salary: '6.00' },
      { company: 'Epiroc', selects: 4, salary: '6.00' },
      { company: 'Thermax', selects: 1, salary: '5.75' },
      { company: 'Seneca Global', selects: 4, salary: '5.25' },
      { company: 'Tata Electronics', selects: 2, salary: '5.25' },
      { company: 'Urjanet', selects: 1, salary: '5.00' },
      { company: 'Urjanet-2', selects: 3, salary: '3.50' },
      { company: 'Lumen Technologies', selects: 1, salary: '5.00' },
      { company: 'Frugal Testing', selects: 1, salary: '5.00' },
      { company: 'Ops Ramp', selects: 1, salary: '4.90' },
      { company: 'ZOHO', selects: 1, salary: '4.60' },
      { company: 'Grindwell Norton (SAint Gobian)', selects: 4, salary: '4.60' },
      { company: 'Deloitte', selects: 1, salary: '4.50' },
      { company: 'Delhivery', selects: 1, salary: '4.50' },
      { company: 'Vodafone Idea', selects: 2, salary: '4.50' },
      { company: 'Amdocs', selects: 14, salary: '4.20' },
      { company: 'L&T Technology Services', selects: 20, salary: '4.00' },
      { company: 'Virtusa', selects: 1, salary: '4.00' },
      { company: 'Faurecia', selects: 4, salary: '4.00' },
      { company: 'Serendebyte', selects: 5, salary: '4.00' },
      { company: 'Cognizant', selects: 2, salary: '4.00' },
      { company: 'Continental AG', selects: 1, salary: '4.00' },
      { company: 'edWisor', selects: 23, salary: '4.00' },
      { company: 'L&T Technology Services', selects: 2, salary: '4.00' },
      { company: 'MindTree', selects: 4, salary: '3.80' },
      { company: 'Capgemini', selects: 4, salary: '3.80' },
      { company: 'TA Digital', selects: 2, salary: '3.75' },
      { company: 'DXC', selects: 50, salary: '3.60' },
      { company: 'TCS Ninja', selects: 212, salary: '3.60' },
      { company: 'Infosys', selects: 107, salary: '3.60' },
      { company: 'KPIT Sparkle', selects: 3, salary: '3.60' },
      { company: 'Wipro', selects: 30, salary: '3.60' },
      { company: 'Hexaware', selects: 2, salary: '3.50' },
      { company: 'CGI', selects: 42, salary: '3.50' },
      { company: 'NTT Data', selects: 3, salary: '3.50' },
      { company: 'HCL', selects: 2, salary: '3.50' },
      { company: 'RANE', selects: 1, salary: '3.50' },
      { company: 'MyCaptain', selects: 4, salary: '3.50' },
      { company: 'Atos Syntel', selects: 7, salary: '3.50' },
      { company: 'Mphasis', selects: 1, salary: '3.50' },
      { company: 'Evoke Technologies', selects: 2, salary: '3.50' },
      { company: 'Quest Global', selects: 1, salary: '3.00' },
      { company: 'TeachNook', selects: 7, salary: '3.00' },
      { company: 'Delievery SCM', selects: 4, salary: '2.75' },
      { company: 'ZENQ', selects: 1, salary: '2.40' },
    ],
  },
  {
    batch: '2016–2020',
    total: 789,
    salaryLabel: '',
    note: 'Detailed per-company package figures were not published for this batch on the source site — only company names and select counts.',
    rows: [
      { company: 'Accenture', selects: 207, salary: '' },
      { company: 'Capgemini', selects: 224, salary: '' },
      { company: 'EPAM', selects: 19, salary: '' },
      { company: 'Hyundai Mobis', selects: 1, salary: '' },
      { company: 'Infosys', selects: 16, salary: '' },
      { company: 'TCS', selects: 90, salary: '' },
      { company: 'Thermax', selects: 2, salary: '' },
      { company: 'Seneca Global', selects: 2, salary: '' },
      { company: 'TechnipFMC', selects: 1, salary: '' },
      { company: 'GGK Tech', selects: 2, salary: '' },
      { company: 'NTT Data', selects: 13, salary: '' },
      { company: 'Hexaware', selects: 8, salary: '' },
      { company: 'IBM', selects: 9, salary: '' },
      { company: 'Mind Tree', selects: 1, salary: '' },
      { company: 'HCL', selects: 36, salary: '' },
      { company: 'Expedia', selects: 1, salary: '' },
      { company: 'Zemoso Labs', selects: 1, salary: '' },
      { company: 'Urjanet', selects: 11, salary: '' },
      { company: 'Faurecia', selects: 1, salary: '' },
      { company: 'Flipkart', selects: 1, salary: '' },
      { company: 'Soctronics', selects: 1, salary: '' },
      { company: 'NCR', selects: 8, salary: '' },
      { company: 'Cognizant', selects: 38, salary: '' },
      { company: 'State Street', selects: 1, salary: '' },
      { company: 'Quest Global', selects: 10, salary: '' },
      { company: 'Milekal', selects: 11, salary: '' },
      { company: 'Wipro', selects: 8, salary: '' },
      { company: 'Bank of America', selects: 17, salary: '' },
      { company: 'Renault Nissan', selects: 5, salary: '' },
      { company: 'E Construct', selects: 2, salary: '' },
      { company: 'Mahindra Mahindra', selects: 3, salary: '' },
      { company: 'DBS Bank', selects: 1, salary: '' },
      { company: 'Adobe', selects: 2, salary: '' },
      { company: 'Anand', selects: 1, salary: '' },
      { company: 'CADeploy', selects: 11, salary: '' },
      { company: 'Hero', selects: 2, salary: '' },
      { company: 'L&T', selects: 12, salary: '' },
      { company: 'Epiroc', selects: 5, salary: '' },
      { company: 'Miracle', selects: 3, salary: '' },
      { company: 'Accolite', selects: 1, salary: '' },
      { company: 'Amazon', selects: 1, salary: '' },
    ],
  },
  {
    batch: '2015–2019',
    total: 633,
    salaryLabel: '',
    note: 'Detailed per-company package figures were not published for this batch on the source site — only company names and select counts.',
    rows: [
      { company: 'IBM', selects: 97, salary: '' },
      { company: 'Infosys', selects: 176, salary: '' },
      { company: 'Mahindra & Mahindra', selects: 9, salary: '' },
      { company: 'Kony Labs', selects: 3, salary: '' },
      { company: 'Thermax', selects: 1, salary: '' },
      { company: 'L&T Technology Services', selects: 2, salary: '' },
      { company: 'Host Analytics', selects: 2, salary: '' },
      { company: 'TiVo', selects: 7, salary: '' },
      { company: 'John Deere (GET)', selects: 1, salary: '' },
      { company: 'Hansa Solutions', selects: 2, salary: '' },
      { company: 'Value Labs', selects: 10, salary: '' },
      { company: 'Honda', selects: 1, salary: '' },
      { company: 'TCS Code Vita', selects: 44, salary: '' },
      { company: 'Hack with Infy', selects: 10, salary: '' },
      { company: 'Milople', selects: 1, salary: '' },
      { company: 'MAQ', selects: 3, salary: '' },
      { company: 'EPAM', selects: 2, salary: '' },
      { company: 'Adobe', selects: 3, salary: '' },
      { company: 'Soctronics', selects: 2, salary: '' },
      { company: 'NCR', selects: 1, salary: '' },
      { company: 'GGK Technologies', selects: 3, salary: '' },
      { company: 'GoSpeedyGo', selects: 9, salary: '' },
      { company: 'TCS Ninja', selects: 49, salary: '' },
      { company: 'Seneca Global', selects: 1, salary: '' },
      { company: 'Tricad', selects: 6, salary: '' },
      { company: 'Expedia', selects: 2, salary: '' },
      { company: 'Coviam', selects: 2, salary: '' },
      { company: 'Urjanet', selects: 14, salary: '' },
      { company: 'IBM – ISL', selects: 1, salary: '' },
      { company: 'OpenText', selects: 4, salary: '' },
      { company: 'ValueMomentum', selects: 1, salary: '' },
      { company: 'Brewed@The Lab', selects: 11, salary: '' },
      { company: 'Wipro', selects: 13, salary: '' },
      { company: 'Torry Harris', selects: 7, salary: '' },
      { company: 'Renault Nissan', selects: 5, salary: '' },
      { company: 'Talent Sprint', selects: 2, salary: '' },
      { company: 'Kreeti Technologies', selects: 1, salary: '' },
      { company: 'John Deere (PGET)', selects: 2, salary: '' },
      { company: 'Mindtree', selects: 2, salary: '' },
      { company: 'Ashok Leyland', selects: 5, salary: '' },
      { company: 'HCL', selects: 42, salary: '' },
      { company: 'DBS Bank', selects: 5, salary: '' },
      { company: 'NTT Data', selects: 1, salary: '' },
      { company: 'Basix Sub-K', selects: 3, salary: '' },
      { company: 'Cognizant', selects: 32, salary: '' },
      { company: 'Amazon', selects: 1, salary: '' },
      { company: 'Ferns N Petals', selects: 3, salary: '' },
      { company: 'Atos Syntel', selects: 5, salary: '' },
      { company: 'Broadridge', selects: 8, salary: '' },
      { company: 'GreEdge', selects: 1, salary: '' },
      { company: 'Tecnicas Reunidas', selects: 1, salary: '' },
      { company: 'Haritha Techserve', selects: 8, salary: '' },
      { company: 'Amazon (HR)', selects: 1, salary: '' },
      { company: 'Ven-Tech India Pvt Ltd', selects: 3, salary: '' },
      { company: 'Athena Health', selects: 2, salary: '' },
    ],
  },
  {
    batch: '2014–2018',
    total: 391,
    salaryLabel: '',
    note: 'Detailed per-company package figures were not published for this batch on the source site — only company names and select counts.',
    rows: [
      { company: 'Imaginate', selects: 1, salary: '' },
      { company: 'John Deere', selects: 14, salary: '' },
      { company: 'Kony Labs', selects: 2, salary: '' },
      { company: 'Thomson Reuters', selects: 2, salary: '' },
      { company: 'Latent View', selects: 1, salary: '' },
      { company: 'GGK Technologies', selects: 2, salary: '' },
      { company: 'Frenustech', selects: 14, salary: '' },
      { company: 'Urjanet', selects: 9, salary: '' },
      { company: 'Milople', selects: 5, salary: '' },
      { company: 'TCS', selects: 2, salary: '' },
      { company: 'Whirl Data', selects: 1, salary: '' },
      { company: 'Infosys', selects: 32, salary: '' },
      { company: 'Cap Gemini', selects: 103, salary: '' },
      { company: 'NTT Data', selects: 9, salary: '' },
      { company: 'Torry Harris', selects: 5, salary: '' },
      { company: 'Ndot', selects: 6, salary: '' },
      { company: 'Host Analytics', selects: 1, salary: '' },
      { company: 'Accenture', selects: 1, salary: '' },
      { company: 'Seneca Global', selects: 3, salary: '' },
      { company: 'Thermax', selects: 1, salary: '' },
      { company: 'OpsRamp', selects: 4, salary: '' },
      { company: 'Vyshnavi Information Technologies', selects: 1, salary: '' },
      { company: 'Smarketers', selects: 1, salary: '' },
      { company: 'Renault Nissan', selects: 2, salary: '' },
      { company: 'CADeploy', selects: 9, salary: '' },
      { company: 'Zoho', selects: 3, salary: '' },
      { company: 'Ashok Leyland', selects: 2, salary: '' },
      { company: 'Sankalp Semiconductor', selects: 2, salary: '' },
      { company: 'Siliconus', selects: 7, salary: '' },
      { company: 'Softronics', selects: 1, salary: '' },
      { company: 'Caterpillar', selects: 1, salary: '' },
      { company: 'Vtiger', selects: 9, salary: '' },
      { company: 'VWR', selects: 6, salary: '' },
      { company: 'AMD', selects: 1, salary: '' },
      { company: 'RDC', selects: 1, salary: '' },
      { company: 'Capital Via', selects: 21, salary: '' },
      { company: 'SCII', selects: 4, salary: '' },
      { company: 'Amazon', selects: 2, salary: '' },
      { company: 'MAQ Software', selects: 1, salary: '' },
      { company: 'Haritha Tech Serve', selects: 4, salary: '' },
      { company: 'Virtusa', selects: 2, salary: '' },
      { company: 'Mphasis', selects: 9, salary: '' },
      { company: 'Infovity', selects: 1, salary: '' },
      { company: 'HCL', selects: 3, salary: '' },
      { company: 'QSpiders', selects: 20, salary: '' },
      { company: 'Cattain IT Labs', selects: 4, salary: '' },
      { company: 'ADP', selects: 1, salary: '' },
      { company: 'IBM', selects: 47, salary: '' },
      { company: 'Talent Sprint', selects: 1, salary: '' },
      { company: 'Block Chain Beyond', selects: 1, salary: '' },
      { company: 'PEOL Technologies', selects: 2, salary: '' },
      { company: 'Eureka Forbes', selects: 1, salary: '' },
      { company: 'RGC Software Solutions', selects: 1, salary: '' },
      { company: 'Cognizant', selects: 2, salary: '' },
    ],
  },
  {
    batch: '2013–2017',
    total: 560,
    salaryLabel: '',
    note: 'Detailed per-company package figures were not published for this batch on the source site — only company names and select counts.',
    rows: [
      { company: 'IBM', selects: 179, salary: '' },
      { company: 'Tech Mahindra', selects: 82, salary: '' },
      { company: 'Infosys', selects: 54, salary: '' },
      { company: 'John Deere', selects: 7, salary: '' },
      { company: 'Thermax', selects: 2, salary: '' },
      { company: 'Kony India Pvt. Ltd.', selects: 6, salary: '' },
      { company: 'TalentSprint', selects: 3, salary: '' },
      { company: 'Capgemini', selects: 167, salary: '' },
      { company: 'NTT Data', selects: 2, salary: '' },
      { company: 'Seneca Global', selects: 7, salary: '' },
      { company: 'Zoho', selects: 1, salary: '' },
      { company: 'In22 Labs', selects: 1, salary: '' },
      { company: 'Mindtree', selects: 7, salary: '' },
      { company: 'MyTaxFiler', selects: 1, salary: '' },
      { company: 'Kewill', selects: 1, salary: '' },
      { company: 'D Square', selects: 1, salary: '' },
      { company: 'Virtusa', selects: 1, salary: '' },
      { company: 'Urjanet', selects: 3, salary: '' },
      { company: 'HCL', selects: 3, salary: '' },
      { company: 'Kotak Mahindra Bank', selects: 2, salary: '' },
      { company: 'Nestle', selects: 2, salary: '' },
      { company: 'Avakash Homes', selects: 2, salary: '' },
      { company: 'Netafim', selects: 2, salary: '' },
      { company: 'Haritha Techserv Ltd', selects: 4, salary: '' },
      { company: 'QSpiders', selects: 15, salary: '' },
      { company: 'Siliconus', selects: 2, salary: '' },
      { company: 'Bosch', selects: 3, salary: '' },
    ],
  },
  {
    batch: '2012–2016',
    total: 532,
    salaryLabel: '',
    rows: [
      { company: 'Tech Mahindra', selects: 68, salary: '' },
      { company: 'IBM', selects: 161, salary: '' },
      { company: 'Infosys', selects: 76, salary: '' },
      { company: 'John Deere', selects: 3, salary: '' },
      { company: 'NTT Data', selects: 1, salary: '' },
      { company: 'Tera Data', selects: 1, salary: '' },
      { company: 'Mindtree', selects: 16, salary: '' },
      { company: 'Seneca Global', selects: 6, salary: '' },
      { company: 'Virtusa', selects: 98, salary: '' },
      { company: 'Rane', selects: 1, salary: '' },
      { company: 'FSS', selects: 1, salary: '' },
      { company: 'Cigital', selects: 1, salary: '' },
      { company: 'Gowra Bits & Bytes', selects: 4, salary: '' },
      { company: 'Kony India Pvt. Ltd.', selects: 1, salary: '' },
      { company: 'Lumeris', selects: 2, salary: '' },
      { company: 'Mphasis', selects: 2, salary: '' },
      { company: 'Gate Forum', selects: 1, salary: '' },
      { company: 'Genpact', selects: 3, salary: '' },
      { company: 'HCL', selects: 75, salary: '' },
      { company: 'Persistent', selects: 9, salary: '' },
      { company: 'Peak Point Technologies', selects: 7, salary: '' },
      { company: 'Midas Touch', selects: 2, salary: '' },
      { company: 'SAP Labs', selects: 5, salary: '' },
      { company: 'NTL', selects: 8, salary: '' },
      { company: 'Capital IQ', selects: 6, salary: '' },
      { company: 'BIM Expertz IT', selects: 3, salary: '' },
      { company: 'Biz Time IT Solutions', selects: 12, salary: '' },
      { company: 'TCS', selects: 3, salary: '' },
      { company: 'FACE', selects: 1, salary: '' },
      { company: 'Aagna Global Solutions', selects: 5, salary: '' },
      { company: 'Polaris', selects: 3, salary: '' },
      { company: 'Trianz', selects: 1, salary: '' },
      { company: 'Schneider Electric', selects: 19, salary: '' },
      { company: 'International Paper', selects: 1, salary: '' },
      { company: 'Syntel', selects: 2, salary: '' },
      { company: 'Bosch', selects: 4, salary: '' },
    ],
  },
  {
    batch: '2011–2015',
    total: 463,
    salaryLabel: '',
    rows: [
      { company: 'Infosys', selects: 123, salary: '' },
      { company: 'Tech Mahindra', selects: 133, salary: '' },
      { company: 'John Deere', selects: 2, salary: '' },
      { company: 'Angelique International Limited', selects: 1, salary: '' },
      { company: 'IBM', selects: 122, salary: '' },
      { company: 'Cyient', selects: 1, salary: '' },
      { company: 'Mindtree Ltd.', selects: 4, salary: '' },
      { company: 'AccelQ', selects: 1, salary: '' },
      { company: 'Kony Labs', selects: 3, salary: '' },
      { company: 'Thought Works', selects: 1, salary: '' },
      { company: 'Wipro', selects: 1, salary: '' },
      { company: 'Virtusa', selects: 10, salary: '' },
      { company: 'Thermax', selects: 1, salary: '' },
      { company: 'NTT Data', selects: 8, salary: '' },
      { company: 'CSC', selects: 14, salary: '' },
      { company: 'Mphasis', selects: 5, salary: '' },
      { company: 'Osmosys', selects: 2, salary: '' },
      { company: 'Sonata', selects: 5, salary: '' },
      { company: 'Omega Health Care', selects: 14, salary: '' },
      { company: 'Capital IQ', selects: 3, salary: '' },
      { company: 'Renault Nissan', selects: 3, salary: '' },
      { company: 'Bosch', selects: 6, salary: '' },
    ],
  },
  {
    batch: '2010–2014',
    total: null,
    salaryLabel: '',
    rows: [
      { company: 'Infosys', selects: 65, salary: '' },
      { company: 'Infotech Enterprises', selects: 8, salary: '' },
      { company: 'Mphasis', selects: 4, salary: '' },
      { company: 'The Trainline.com', selects: 4, salary: '' },
      { company: 'NTT Data', selects: 26, salary: '' },
      { company: 'Virtusa', selects: 9, salary: '' },
      { company: 'IBM', selects: 46, salary: '' },
      { company: 'SAP Labs', selects: 4, salary: '' },
      { company: 'CSC', selects: 30, salary: '' },
      { company: 'TCS', selects: 3, salary: '' },
      { company: 'CTS', selects: 4, salary: '' },
      { company: 'Iatros Healthcare Solutions', selects: 2, salary: '' },
      { company: 'Tech Mahindra', selects: 10, salary: '' },
      { company: 'L&T Infotech', selects: 2, salary: '' },
      { company: 'HCL Technologies', selects: 2, salary: '' },
      { company: 'Miracle Software Systems, Inc.', selects: 9, salary: '' },
      { company: 'Capital IQ', selects: 3, salary: '' },
      { company: 'Ikya Human Capital Solutions Limited', selects: 3, salary: '' },
      { company: 'Syntel', selects: 4, salary: '' },
      { company: 'Accenture', selects: 9, salary: '' },
      { company: 'ING Vysya Bank', selects: 2, salary: '' },
    ],
  },
  {
    batch: '2009–2013',
    total: null,
    salaryLabel: '',
    rows: [
      { company: 'CSC', selects: 17, salary: '' },
      { company: 'TCS', selects: 72, salary: '' },
      { company: 'Pramathi Technologies', selects: 5, salary: '' },
      { company: 'Infotech Enterprises', selects: 8, salary: '' },
      { company: 'NTT Data', selects: 9, salary: '' },
      { company: 'Foursoft', selects: 6, salary: '' },
      { company: 'India Healthcare Solutions', selects: 18, salary: '' },
      { company: 'Cadsys', selects: 11, salary: '' },
      { company: 'LIC Life Plus', selects: 6, salary: '' },
      { company: 'NetEnrich', selects: 6, salary: '' },
      { company: 'ING Vysya', selects: 3, salary: '' },
      { company: 'Voltech', selects: 8, salary: '' },
      { company: 'Midas Touch Infrastructure', selects: 3, salary: '' },
      { company: 'Strateology', selects: 2, salary: '' },
      { company: 'Tech Mahindra', selects: 17, salary: '' },
      { company: 'Racewin Technologies', selects: 11, salary: '' },
    ],
  },
  {
    batch: '2008–2012',
    total: null,
    salaryLabel: '',
    rows: [
      { company: 'TCS', selects: 109, salary: '' },
      { company: 'GE Healthcare', selects: 1, salary: '' },
      { company: 'MAQ Software', selects: 1, salary: '' },
      { company: 'Oracle', selects: 5, salary: '' },
      { company: 'Syntel', selects: 20, salary: '' },
      { company: 'ADP', selects: 1, salary: '' },
      { company: 'HCL', selects: 6, salary: '' },
      { company: 'Sasken', selects: 2, salary: '' },
      { company: 'Explore Pvt Ltd', selects: 14, salary: '' },
      { company: 'SAP Labs', selects: 2, salary: '' },
      { company: 'Sonata', selects: 7, salary: '' },
      { company: 'Sure IT', selects: 1, salary: '' },
      { company: 'Rennaissance', selects: 5, salary: '' },
      { company: 'Anjani Cement Ltd.', selects: 4, salary: '' },
      { company: 'Met Life', selects: 5, salary: '' },
      { company: 'Quardant 4', selects: 1, salary: '' },
      { company: 'IBM', selects: 2, salary: '' },
      { company: 'GGK Technologies', selects: 2, salary: '' },
      { company: 'Accenture', selects: 11, salary: '' },
    ],
  },
  {
    batch: '2007–2011',
    total: null,
    salaryLabel: '',
    rows: [
      { company: 'TCS', selects: 101, salary: '' },
      { company: 'Mahindra Satyam', selects: 80, salary: '' },
      { company: 'Syntel', selects: 25, salary: '' },
      { company: 'Computer Associates', selects: 2, salary: '' },
    ],
  },
  {
    batch: '2006–2010',
    total: null,
    salaryLabel: '',
    rows: [
      { company: 'TCSL', selects: 49, salary: '' },
      { company: 'Miracle Software Systems, (I) Pvt. Ltd.', selects: 8, salary: '' },
      { company: 'ROFOUS Software Pvt Ltd', selects: 16, salary: '' },
      { company: 'Tech Mahindra', selects: 21, salary: '' },
      { company: 'Infotech Enterprises', selects: 3, salary: '' },
      { company: 'Mahindra Satyam', selects: 4, salary: '' },
      { company: 'CSC', selects: 4, salary: '' },
      { company: 'Solar Semi Conductor', selects: 1, salary: '' },
      { company: 'NTPC', selects: 1, salary: '' },
      { company: 'Leisux', selects: 3, salary: '' },
    ],
  },
  {
    batch: '2005–2009',
    total: null,
    salaryLabel: '',
    rows: [
      { company: 'TCSL', selects: 45, salary: '' },
      { company: 'Infosys', selects: 9, salary: '' },
      { company: 'Intelligroup', selects: 7, salary: '' },
    ],
  },
  {
    batch: '2004–2008',
    total: null,
    salaryLabel: '',
    rows: [
      { company: 'Satyam Computers Ltd.', selects: 38, salary: '' },
      { company: 'IBM', selects: 16, salary: '' },
      { company: 'Infosys Technologies Ltd.', selects: 27, salary: '' },
      { company: 'Accenture', selects: 26, salary: '' },
      { company: 'Syntel', selects: 8, salary: '' },
      { company: 'L & T Infotech', selects: 1, salary: '' },
      { company: 'Wipro', selects: 10, salary: '' },
      { company: 'Sify', selects: 2, salary: '' },
      { company: 'Cosmic Circuits', selects: 2, salary: '' },
    ],
  },
  {
    batch: '2003–2007',
    total: null,
    salaryLabel: '',
    rows: [
      { company: 'Satyam Computers Ltd.', selects: 9, salary: '' },
      { company: 'IBM', selects: 21, salary: '' },
      { company: 'Infosys Technologies Ltd.', selects: 3, salary: '' },
      { company: 'Wipro', selects: 14, salary: '' },
      { company: 'CTS', selects: 3, salary: '' },
      { company: 'Computech', selects: 5, salary: '' },
      { company: 'Elico', selects: 2, salary: '' },
      { company: 'Efftronics', selects: 10, salary: '' },
    ],
  },
];
