export interface TableRow {
  [key: string]: string | number;
}

export interface PlacementItem {
  slug: string;
  title: string;
  desc: string;
  icon: string;
  external?: boolean;
  url?: string;
  intro?: string;
  about?: string;
  highlights?: string[];
  outcomes?: string[];
  partners?: string[];
  tableData?: TableRow[];
}

export const placementItems: PlacementItem[] = [
  {
    slug: 'placement-details',
    title: 'Placement Details',
    icon: '📊',
    desc: 'VWU consistently delivers outstanding campus placement results, with over 8,000 students placed since 2003 across 200+ companies. Recent batches have seen packages as high as 49 LPA, with global tech giants like Amazon, Adobe, Microsoft, and Palo Alto Networks among top recruiters.',
    intro: "VWU's placement record reflects years of sustained industry engagement and student preparation. Each batch sees hundreds of students placed across IT services, product companies, core engineering, and financial services sectors. The college's strong ties with both mass recruiters and premium employers ensure diverse opportunities at every salary band.",
    about: 'Recent batches illustrate the breadth of placement outcomes: the 2021–2025 batch saw 1,156 placements with a highest package of 46 LPA (Amazon), while the 2018–2022 batch achieved 1,892 placements with a peak of 49 LPA (Palo Alto Networks). Mega recruiters such as Capgemini, Accenture, Infosys, TCS, IBM, and Wipro routinely select 100+ students per cycle, while premium companies like Adobe, PayPal, VISA, D.E. Shaw, and Flipkart offer packages in the 25–45 LPA range.\n\nThe placement ecosystem spans IT services, semiconductor firms, automotive and manufacturing companies, and global financial institutions. Regular engagement with 200+ companies annually ensures students from all departments—CSE, ECE, EEE, IT, ME, and CE—find relevant opportunities.',
    highlights: [
      '8,000+ total placements documented from 2003 to 2025',
      'Highest package: 49 LPA (Palo Alto Networks, 2018–2022 batch)',
      '1,892 students placed in a single batch (2018–2022)',
      '200+ companies engage for recruitment annually',
      'Top recruiters include Amazon, Adobe, Microsoft, Google, and Flipkart',
      'Mass recruiters: Capgemini, Accenture, Infosys, TCS, IBM, Wipro',
      'Packages range from 2–3 LPA (entry-level) to 45+ LPA (premium)',
      'Ranked among top private institutions in Andhra Pradesh for placements',
    ],
    outcomes: [
      '2021–2025 batch: 1,156 placements, highest 46 LPA (Amazon)',
      '2020–2024 batch: 818 placements, highest 41.54 LPA (Intuit)',
      '2019–2023 batch: 1,464 placements, highest 41 LPA (Adobe)',
      '2018–2022 batch: 1,892 placements, highest 49 LPA (Palo Alto Networks)',
      '2017–2021 batch: 933 placements',
      '2016–2020 batch: 789 placements',
      '2015–2019 batch: 633 placements',
    ],
    partners: [
      'Amazon', 'Adobe', 'Microsoft', 'Google', 'Flipkart', 'PayPal', 'VISA',
      'Palo Alto Networks', 'Capgemini', 'Accenture', 'Infosys', 'TCS', 'Wipro',
      'IBM', 'HCL', 'Cognizant', 'Intuit', 'D.E. Shaw', 'Walmart', 'NXP',
      'Expedia', 'Myntra', 'Optum', 'Providence', 'Publicis Sapient',
      'State Street', 'Mahindra & Mahindra', 'Hyundai Motors', 'TVS Motors',
      'Hero MotoCorp', 'Renault Nissan', 'Caterpillar', 'EPAM', 'DBS Bank',
      'Zenoti', 'Persistent Systems', 'OpenText',
    ],
    tableData: [
      { Batch: '2021–2025', 'Total Placements': 1156, 'Highest Package': '46 LPA', 'Top Recruiter': 'Amazon' },
      { Batch: '2020–2024', 'Total Placements': 818,  'Highest Package': '41.54 LPA', 'Top Recruiter': 'Intuit' },
      { Batch: '2019–2023', 'Total Placements': 1464, 'Highest Package': '41 LPA', 'Top Recruiter': 'Adobe' },
      { Batch: '2018–2022', 'Total Placements': 1892, 'Highest Package': '49 LPA', 'Top Recruiter': 'Palo Alto Networks' },
      { Batch: '2017–2021', 'Total Placements': 933,  'Highest Package': '—', 'Top Recruiter': '—' },
      { Batch: '2016–2020', 'Total Placements': 789,  'Highest Package': '—', 'Top Recruiter': '—' },
      { Batch: '2015–2019', 'Total Placements': 633,  'Highest Package': '—', 'Top Recruiter': '—' },
      { Batch: '2014–2018', 'Total Placements': 391,  'Highest Package': '—', 'Top Recruiter': '—' },
      { Batch: '2013–2017', 'Total Placements': 560,  'Highest Package': '—', 'Top Recruiter': '—' },
      { Batch: '2012–2016', 'Total Placements': 532,  'Highest Package': '—', 'Top Recruiter': '—' },
      { Batch: '2011–2015', 'Total Placements': 463,  'Highest Package': '—', 'Top Recruiter': '—' },
    ],
  },
  {
    slug: 'success-stories',
    title: 'Success Stories',
    icon: '🌟',
    desc: "Inspiring journeys of VWU graduates who have secured positions at some of the world's leading technology, engineering, and financial services firms — from first-generation engineers to students achieving 40+ LPA packages.",
    intro: "The success stories section celebrates VWU graduates who have gone on to build remarkable careers at top national and international organizations. Enabled by rigorous campus recruitment training, mentorship from the TPO Cell, and a strong industry liaison network, these graduates exemplify the college's commitment to holistic career development.",
    about: "VWU's placement ecosystem — comprising the TPO Cell, Industry Liaison Offices, Career Guidance Cell, and Campus Recruitment Training programmes — has been instrumental in shaping student success. Graduates have secured positions at companies such as Amazon, Adobe, Microsoft, Palo Alto Networks, Flipkart, and PayPal, with packages ranging from competitive entry-level offers to premium packages exceeding 45 LPA.\n\nBeyond corporate placements, many VWU alumni have pursued higher education at universities in the USA, UK, Australia, Canada, and Germany, with support from the Graduate Study Abroad Center (GSAC). Others have pursued advanced research and R&D roles through Mission R&D, working at multinational product companies and innovative startups.",
    highlights: [
      'Graduates placed at Amazon, Adobe, Microsoft, Google, Flipkart, and PayPal',
      'Packages up to 49 LPA achieved by recent alumni',
      '8,000+ total placements documented since 2003',
      'Alumni working across IT, core engineering, R&D, and financial services globally',
      'Many graduates pursue higher education in USA, UK, Australia, Canada, and Germany',
      'Mission R&D alumni selected directly by MNCs and startups for product roles',
      'Consistent top placement rank among private institutions in Andhra Pradesh',
    ],
    outcomes: [
      'Highest individual package: 49 LPA (Palo Alto Networks)',
      'Notable packages: 46 LPA (Amazon), 41 LPA (Adobe), 41.54 LPA (Intuit)',
      'Over 1,892 students placed in a single batch (2018–2022)',
      'Alumni present at top global firms across USA, Europe, and Asia-Pacific',
    ],
    partners: [
      'Amazon', 'Adobe', 'Microsoft', 'Google', 'Flipkart', 'PayPal',
      'Palo Alto Networks', 'Infosys', 'TCS', 'Capgemini', 'Accenture', 'IBM',
    ],
    tableData: [],
  },
  {
    slug: 'tpo-cell',
    title: 'TPO Cell',
    icon: '🏢',
    desc: 'The Training and Placement Office (TPO) Cell at VWU is the central hub for student career development, coordinating campus recruitment, industrial training, and career counseling. VWU has topped AP private institution placement rankings for 7+ consecutive years.',
    intro: "The TPO Cell at VWU orchestrates a comprehensive suite of career development services — from organising campus interviews with 200+ companies to facilitating industrial internships and competitive exam preparation. The office's mandate extends to entrepreneurship development, industry interaction, and project sourcing for both students and faculty.",
    about: "Key activities of the TPO Cell include arranging in-plant industrial training during summer and intra-semester breaks, conducting Entrepreneurship Development Programs, and organising corporate executive lectures for career guidance. The cell also prepares students for competitive examinations such as GATE, GRE, GMAT, and TOEFL, broadening outcomes beyond campus placements to higher education and research pathways.\n\nThe cell operates with institutional-wide reach, recently expanding its mandate to include industry liaison duties through regional offices in Hyderabad, Chennai, Bengaluru, Pune, and Vadodara.",
    highlights: [
      'VWU has topped AP private institution placement rankings for 7+ consecutive years',
      'Coordinates recruitment with 200+ companies annually',
      'Facilitates in-plant industrial training during semester and summer breaks',
      'Runs Entrepreneurship Development Programs for aspiring founders',
      'Prepares students for GATE, GRE, GMAT, and TOEFL examinations',
      'Full-time Dean and permanent placement staff dedicated to the cell',
      'Regional industry liaison network across Hyderabad, Chennai, Bengaluru, Pune, and Vadodara',
    ],
    outcomes: [
      '8,000+ students placed since 2003',
      'Consistent top-rank placement performance among AP private institutions',
    ],
    partners: [],
    tableData: [],
  },
  {
    slug: 'tpo-team',
    title: 'TPO Team',
    icon: '👥',
    desc: 'Meet the dedicated Training and Placement team at VWU — led by Mr. Satish Paruchuri, Director of Industry Relations — with regional liaison officers in Pune, Chennai, Bengaluru, and Delhi ensuring continuous industry outreach.',
    intro: "VWU's TPO Team combines deep industry expertise with academic insight to deliver exceptional placement outcomes. The team's leadership has overseen the placement of over 20,000 students across 200 engineering colleges and has negotiated MoUs with global companies including Microsoft, IBM, CSC, and Infosys on behalf of the government.",
    about: "The team is structured across four tiers: directorial leadership, management-level coordinators, Training and Placement Officers drawn from faculty, and regional Industry Liaison Officers. Dr. K Vamshi Krishna Varma brings 23.5 years of combined industry and training experience, while Ms. Venkata Swathi R contributes 16 years of teaching and placement expertise. Regional officers in Pune (since 2012), Chennai, Bengaluru, and Delhi maintain active relationships with manufacturing, IT, and service sector employers in their respective regions.",
    highlights: [
      'Director Satish Paruchuri facilitated placement of 20,000 students across 200 engineering colleges',
      'MoUs signed with Microsoft, IBM, CSC, and Infosys on behalf of Government of AP',
      '400+ recruitment events coordinated across the state',
      '15,000+ JKC students placed at MNCs and Indian companies',
      'Regional liaison offices in Pune, Chennai, Bengaluru, and Delhi',
      'Dr. K Vamshi Krishna Varma: 23.5 years combined industry and training experience',
      'Team includes Ph.D.-qualified faculty with specialisations in CSE, EEE, and AI',
    ],
    outcomes: [
      '20,000 students placed across 200 engineering colleges under IEG programme',
      '400+ recruitment events organised statewide',
      '15,000+ JKC students placed at MNCs',
    ],
    partners: ['Microsoft', 'IBM', 'CSC', 'Infosys'],
    tableData: [
      { Name: 'Mr. Satish Paruchuri', Role: 'Director, Industry Relations', Experience: 'Former Programme Manager IEG; negotiated MoUs with Microsoft, IBM, CSC, Infosys' },
      { Name: 'Mr. Ravikiran Saili', Role: 'Manager, Industry Relations', Experience: '8+ years HR & operations; coordinated 400+ recruitment events' },
      { Name: 'Dr. K Vamshi Krishna Varma', Role: 'Associate Director, Industry Relations', Experience: '23.5 years total (13.5 industry + 10 training & placements); Ph.D. EEE' },
      { Name: 'Ms. D. Pushpa', Role: 'Assistant Director, Industry Relations', Experience: '7 years HR & administration; former HR at Atlanta Systems' },
      { Name: 'Ms. Venkata Swathi R', Role: 'Training and Placement Officer', Experience: '16 years teaching; Ph.D. pursuing in CSE; Assistant Professor CSE' },
      { Name: 'Mr. K. P. Swaroop', Role: 'Asst. Training & Placement Officer', Experience: '15 years teaching; Ph.D. pursuing; Assistant Professor EEE' },
      { Name: 'Dr. C. P. Pavan Kumar Hota', Role: 'Asst. Training & Placement Officer', Experience: '10+ years teaching; Ph.D. CSE; specialises in Educational Data Mining' },
      { Name: 'Mr. Atul Kirdant', Role: 'Industry Liaison Officer – Pune', Experience: 'MBA Marketing (IIPM); stationed in Pune since 2012' },
      { Name: 'Mr. Arokiadoss', Role: 'Industry Liaison Officer – Tamil Nadu', Experience: 'B.E. + MBA (Alagappa); 6+ years industrial experience' },
      { Name: 'Mr. Ramesh T.S', Role: 'Industry Liaison Officer – Bangalore', Experience: 'B.E. Mechanical; P.G. Diploma Business Administration' },
      { Name: 'Mr. Saurabh Mishra', Role: 'Industry Liaison Officer – Delhi', Experience: 'MBA (Welinker); former roles at Vodafone, Times of India, Sharda & Amity University' },
    ],
  },
  {
    slug: 'industry-liaison-offices',
    title: 'Industry Liaison Offices',
    icon: '🤝',
    desc: "VWU's Industry Liaison Offices across Hyderabad, Chennai, Bengaluru, Pune, and Vadodara facilitate 3,000+ student hires annually and drive deep industry-academia collaboration through MoUs, curriculum development, and joint programmes with 30+ global partners.",
    intro: 'The Industry Liaison Offices (ILO) operate as VWU\'s front-line engagement with the corporate world, maintaining active relationships with IT giants, automotive manufacturers, and global R&D organisations. By positioning VWU as an exclusive partner for sector-leading companies, the ILO secures consistent placement and internship pipelines for students across all engineering disciplines.',
    about: 'Beyond placements, the ILOs have cultivated landmark academic collaborations: 12,000+ students and faculty completed 50,000+ online courses on Coursera, edX, and NASSCOM Future Skills. VWU accounts for roughly 10% of TCS CodeVita results from the AP/Telangana region. The Women in Data Science (WiDS-Hyderabad) conference, organised in partnership with Stanford University, has drawn 60+ organisations.\n\nEach regional office is strategically positioned: Chennai serves the automotive hub (BMW, Ford) with 400+ alumni, Pune targets automobile manufacturing (est. 2012), Bengaluru focuses on IT sector recruitment, and Vadodara covers Gujarat-based industries.',
    highlights: [
      '3,000+ students hired annually through the liaison network',
      'Regional offices in Hyderabad, Chennai, Bengaluru, Pune, and Vadodara',
      '12,000 students and faculty completed 50,000+ online courses',
      '10% of TCS CodeVita results in AP/Telangana come from VWU',
      'WiDS-Hyderabad conference (Stanford University partnership) with 60+ organisations',
      '400+ VWU alumni based in Chennai',
      'Exclusive industry partner for companies across IT, core, and R&D sectors',
    ],
    outcomes: [
      '3,000+ students placed annually via ILO network',
      '50,000+ online courses completed by 12,000 students and faculty',
      '10% of TCS CodeVita AP/Telangana results from VWU',
    ],
    partners: [
      'Microsoft', 'Amazon', 'Flipkart', 'TCS', 'Infosys', 'Wipro', 'EPAM',
      'BNY', 'NCR', 'ServiceNow', 'Salesforce', 'PEGA', 'Caterpillar',
      'Mahindra & Mahindra', 'Renault Nissan', 'Ashok Leyland', 'Hyundai',
      'BMW', 'Ford', 'Siemens', 'Robert Bosch', 'JCB', 'Bajaj', 'Tata',
      'HCL', 'Microchip', 'NASSCOM', 'CII', 'Stanford University',
    ],
    tableData: [
      { Office: 'Bengaluru', Address: 'VEDIC, New Airport Road, Tarabanahalli, Chickkajala Post – 562157', 'Key Focus': 'IT sector recruitment hub' },
      { Office: 'Chennai', Address: 'Thapar House, 37 Monteith Road, Egmore – 600008', 'Key Focus': 'Core manufacturing & automotive (BMW, Ford); 400+ alumni base' },
      { Office: 'Pune', Address: 'Landmark Avenue, Deepa Society, Banner Pashan Link Road – 411045', 'Key Focus': 'Automobile manufacturing; established 2012' },
      { Office: 'Vadodara', Address: 'Anjani Avenue, Tower B, Flat 502, Jambua JakatNaka – 390014', 'Key Focus': 'Regional coverage for Gujarat-based industries' },
    ],
  },
  {
    slug: 'career-guidance-cell',
    title: 'Career Guidance Cell',
    icon: '🧭',
    desc: "VWU's Career Guidance Cell empowers students with structured career counseling, GRE/TOEFL/GATE coaching, and personality development programmes. Purpose-built with mock interview rooms and dedicated training spaces, it serves every career pathway — corporate, postgraduate, and civil services.",
    intro: "VWU's Career Guidance Cell serves as a comprehensive career development hub, addressing the diverse aspirations of engineering students — whether they aim for corporate careers, postgraduate education abroad, or competitive government examinations. The cell hosts senior corporate executives and visiting professors for seminars on interview skills, leadership, and communication.",
    about: "The cell's infrastructure is purpose-built for career readiness: air-conditioned training rooms, mock interview facilities, and individual counselling spaces ensure students can practice and prepare in a professional environment. The GRE/TOEFL programme covers verbal and quantitative reasoning, analytical writing, and test strategy, while the GATE programme offers progressive training that has resulted in improving student rankings over successive years.\n\nA recently launched initiative prepares students for IES, IFS, and IAS examinations, reflecting the cell's expanding scope beyond engineering placements. By integrating with the TPO Cell, Industry Liaison Offices, and Campus Recruitment Training programmes, the Career Guidance Cell ensures students benefit from a seamless, institution-wide support system.",
    highlights: [
      'Dedicated air-conditioned conference and training room',
      'Separate well-furnished mock interview rooms for interview practice',
      'Full-time Dean and permanent training staff',
      'GRE/TOEFL preparation: verbal, quantitative, reasoning, and AWA',
      'GATE coaching with progressive improvement in student rankings',
      'IES, IFS, and IAS preparation programme recently launched',
      'Seminars on interview skills, personality development, and leadership',
      'Corporate executive lectures and visiting professor sessions',
    ],
    outcomes: [
      'Progressive improvement in GATE student rankings over successive years',
      'Students successfully placed in overseas universities after GRE/TOEFL guidance',
    ],
    partners: [],
    tableData: [],
  },
  {
    slug: 'campus-recruitment-training',
    title: 'Campus Recruitment Training',
    icon: '🎯',
    desc: "VWU's CRT programme is a faculty-led, in-house initiative augmented by partnerships with Elephos, Productivity Reach, and Gate Forum. Structured programmes for II B.Tech (C programming) and III B.Tech (Career Development Programme) ensure all students are placement-ready before entering the recruitment cycle.",
    intro: 'The CRT programme at VWU takes a holistic approach to placement preparation, combining in-house faculty expertise with external training partnerships. Students receive structured coaching in both soft and technical skills — from aptitude and group discussions to core programming languages and database fundamentals.',
    about: 'The Career Development Programme (CDP), targeted at III B.Tech students, covers aptitude, reasoning, English, C language, DBMS, and core subject modules through a structured curriculum. A separate C-Programme is run on a continuous basis for II B.Tech students in circuit branches, ensuring early and sustained exposure to programming fundamentals.\n\nExternal partners Elephos, Productivity Reach, and Gate Forum bring specialised expertise in competitive exam training and aptitude coaching, supplementing the in-house faculty team drawn from engineering, English, mathematics, and management departments.',
    highlights: [
      'In-house training centre staffed by faculty from engineering, English, maths, and management',
      'Partnerships with Elephos, Productivity Reach, and Gate Forum',
      'Career Development Programme (CDP) for all III B.Tech students',
      'C-Programme for all II B.Tech circuit-branch students on continuous basis',
      'Training covers aptitude, reasoning, verbal, GD, interviews, C, C++, Java, DBMS',
      'Aims to boost confidence, conceptual knowledge, and overall employability',
    ],
    outcomes: [],
    partners: ['Elephos', 'Productivity Reach', 'Gate Forum'],
    tableData: [],
  },
  {
    slug: 'our-recruiters',
    title: 'Our Recruiters',
    icon: '🏭',
    desc: 'VWU partners with 200+ companies annually — from premium tech employers like Amazon, Adobe, and Microsoft (35+ LPA) to mass recruiters like TCS, Infosys, and Capgemini, plus core engineering and BFSI sector companies.',
    intro: "VWU's recruiter network is the result of sustained investment in industry relationships through its TPO Cell and regional Industry Liaison Offices. Companies return year after year to hire from VWU, recognising the quality of graduates produced by its rigorous academic and training programmes.",
    about: "The recruiter portfolio is organised across multiple tiers. Premium tech companies — including Amazon, Adobe, Microsoft, Google, Flipkart, PayPal, and Palo Alto Networks — consistently offer packages in the 25–49 LPA range. High-value employers like VISA, D.E. Shaw, Walmart, NXP, Expedia, and Myntra offer 20–35 LPA packages, while mid-level employers like Optum, IBM, Providence, and Publicis Sapient recruit in the 10–20 LPA range. Mass recruiters including TCS, Infosys, Capgemini, Accenture, HCL, and Cognizant ensure broad placement coverage at competitive entry-level packages.\n\nCore engineering and automotive companies — Mahindra & Mahindra, Hyundai Motors, TVS Motors, Hero MotoCorp, Renault Nissan, Caterpillar, and Robert Bosch — provide opportunities for ME, EEE, and CE graduates.",
    highlights: [
      '200+ companies engage for recruitment annually',
      'Premium tier (35+ LPA): Amazon, Adobe, Microsoft, Flipkart, PayPal, Palo Alto Networks',
      'High value tier (20–35 LPA): VISA, D.E. Shaw, Walmart, NXP, Expedia, Myntra',
      'Mid tier (10–20 LPA): IBM, Optum, Providence, Publicis Sapient, State Street',
      'Mass recruiters: TCS, Infosys, Capgemini, Accenture, HCL, Cognizant',
      'Core & automotive: Mahindra, Hyundai, TVS, Hero MotoCorp, Caterpillar, Bosch',
      'BFSI sector: DBS Bank, State Street, Athena Health',
    ],
    outcomes: [
      '8,000+ students placed since 2003 across the recruiter network',
      '3,000+ students hired annually via industry liaison offices',
    ],
    partners: [
      'Amazon', 'Adobe', 'Microsoft', 'Google', 'Flipkart', 'PayPal',
      'Palo Alto Networks', 'VISA', 'D.E. Shaw', 'Walmart', 'NXP', 'Expedia',
      'Myntra', 'Optum', 'IBM', 'Providence', 'Publicis Sapient', 'State Street',
      'Athena Health', 'TCS', 'Infosys', 'Capgemini', 'Accenture', 'HCL',
      'Cognizant', 'Mahindra & Mahindra', 'Hyundai Motors', 'TVS Motors',
      'Hero MotoCorp', 'Renault Nissan', 'Daimler Truck', 'Caterpillar',
      'Robert Bosch', 'DBS Bank', 'EPAM', 'Zenoti', 'Persistent Systems',
      'Intuit', 'OpenText', 'F5 Networks', 'Cloudera', 'Verizon',
    ],
    tableData: [],
  },
  {
    slug: 'employability-skills',
    title: 'Employability Skills',
    icon: '💡',
    desc: "VWU's Employability Skills programme develops seven core competency domains — foundational habits, interpersonal skills, communication, problem-solving, teamwork, ethics, and professional development — to ensure graduates are work-ready from day one.",
    intro: 'Employability skills — also called soft skills or work-readiness skills — are the behavioural and interpersonal competencies that determine how effectively a person works within an organisation. VWU\'s structured programme addresses these systematically, helping students communicate with clarity, resolve conflicts calmly, take initiative, and adapt to diverse workplace settings.',
    about: "The programme's seven-domain framework covers: (1) Foundational skills — organisation, punctuality, dependability, adaptability, and professionalism; (2) Interpersonal skills — politeness, respect, feedback receptiveness, and conflict resolution; (3) Communication skills — active listening, written and verbal expression; (4) Problem-solving and critical thinking — change adaptability, self-initiation, and calm functioning under pressure; (5) Teamwork — collaborative contribution and personal accountability; (6) Ethics and legal responsibilities — honesty, trustworthiness, and policy adherence; and (7) Professional development — leadership, mentoring, negotiation, and industry knowledge.\n\nThe employability skills curriculum is integrated with Campus Recruitment Training, Career Guidance Cell programmes, and industry interaction sessions to ensure students develop these competencies through both structured instruction and practical exposure.",
    highlights: [
      'Seven-domain skill framework covering foundational to leadership competencies',
      'Foundational skills: punctuality, dependability, adaptability, professionalism',
      'Interpersonal skills: conflict resolution, feedback receptiveness, respectfulness',
      'Communication skills: active listening, verbal and written clarity',
      'Problem-solving: self-initiation, calm under pressure, change adaptability',
      'Teamwork: cross-cultural collaboration and personal accountability',
      'Leadership skills: mentoring, negotiation, team motivation, partnership building',
    ],
    outcomes: [],
    partners: [],
    tableData: [],
  },
  {
    slug: 'mission-rd',
    title: 'Mission R&D',
    icon: '🔬',
    desc: "Mission R&D is an intensive 40-day summer programme taught by R&D professionals with 10+ years of global experience. Students get 2 hours of instruction + 6 hours of hands-on product development daily, culminating in a 10-day real-world sprint. Graduates are directly interviewed by MNCs and startups for R&D roles.",
    intro: 'Mission R&D addresses the gap between conventional engineering education and the demands of product-focused R&D roles at global technology companies. The programme selects students who demonstrate strong logical thinking, perseverance, and genuine interest in product development, and immerses them in computer science fundamentals, professional development tools, and cutting-edge platforms.',
    about: 'The 40-day curriculum is structured around three pillars: computer science foundations (data structures, algorithms, design patterns, OS, OOP), professional development tooling (Visual Studio/Eclipse, source control, debugging), and emerging technology platforms (cloud computing, touch interfaces, HTML5/UX). The final 10 days shift entirely to real-world application development, allowing students to demonstrate applied competency before employer interviews.\n\nThe programme was piloted at BVRIT Hyderabad (6 students, 2012) and expanded to IIIT-Hyderabad (12 students, 2013), with major MNCs and startups signing up to interview graduates immediately upon completion.',
    highlights: [
      '40-day intensive summer programme with structured daily schedule',
      '2 hours instruction + 6 hours hands-on development daily',
      'Final 10 days dedicated to real-world application development',
      'Taught by R&D professionals with 10+ years of global experience',
      'Covers CS fundamentals, professional dev tools, and emerging platforms (cloud, HTML5)',
      'Graduates directly interviewed by MNCs and startups for R&D roles',
      'Mission: increase women\'s representation in global R&D careers',
    ],
    outcomes: [
      'MNCs and startups signed up to interview graduates directly upon programme completion',
      'Programme expanded from 6 students (2012) to 12+ students (2013) at IIIT-Hyderabad',
    ],
    partners: [],
    tableData: [],
  },
  {
    slug: 'gsac',
    title: 'Graduate Study Abroad Center – GSAC',
    icon: '🌏',
    desc: 'GSAC provides end-to-end guidance for students aspiring to study at international universities — GRE/TOEFL/IELTS preparation, education loan facilitation, scholarship support, and pre-departure orientation across 7 destinations: USA, Canada, UK, Germany, Australia, Spain, and China.',
    intro: 'GSAC was established to democratise access to overseas higher education by providing students with structured, institution-backed guidance at no additional cost. The centre empowers students to make informed decisions about courses, universities, and destinations aligned with their academic profiles and career goals.',
    about: "The centre's service portfolio covers the full admissions journey: counselling for course and university selection, standardised test preparation (GRE, TOEFL, IELTS), education loan facilitation through partner banks, scholarship application support, and pre-departure programmes covering cultural adaptation, financial management, safety, and social integration. Admitted students are also connected with senior VWU alumni already studying or working abroad.\n\nGSAC operates from the SVES Head Office with a centralised coordination model and designated Single Points of Contact (SPOCs) at each SVES college.",
    highlights: [
      'End-to-end overseas admissions guidance: counselling, test prep, loans, scholarships, pre-departure',
      'Target destinations: USA, Canada, UK, Germany, Australia, Spain, China',
      'GRE, TOEFL, and IELTS preparation offered in-house',
      'Education loan facilitation through partner banking institutions',
      'Scholarship identification and application support provided',
      'Pre-departure orientation: cultural adaptation, financial management, safety',
      'Admitted students connected with VWU alumni abroad for mentorship',
      'Centralised GSAC Cell with SPOCs at every SVES institution',
    ],
    outcomes: [
      'Students successfully guided through international university applications',
      'Admitted students connected with alumni in destination countries',
    ],
    partners: [],
    tableData: [],
  },
  {
    slug: 'higher-education',
    title: 'Higher Education',
    icon: '🎓',
    desc: 'VWU offers M.Tech (CSE, VLSI, Power Electronics, Software Engineering), MBA, and Ph.D. programmes on campus, plus GSAC-supported pathways to 300+ international universities across the USA, UK, Australia, and Canada.',
    intro: 'Higher education at VWU extends well beyond undergraduate studies, with structured pathways for students seeking M.Tech specialisations, MBA degrees, doctoral research, or graduate programmes at international universities. The institution\'s NAAC approval, NBA Accreditation, and UGC recognition provide a strong academic foundation recognised by universities worldwide.',
    about: "VWU's on-campus postgraduate offerings include M.Tech programmes in Computer Science & Engineering, VLSI Design, Power Electronics, and Software Engineering, alongside an MBA programme and Ph.D. research tracks in CSE, ECE, and EEE. The institution operates 30+ specialised facilities — including the Technology Business Incubator, Space Application Center, AR/VR Studio, and AICTE IDEA Lab — all supporting advanced research.\n\nFor students seeking international opportunities, the Graduate Study Abroad Center maintains a directory of 300+ universities across the USA, UK, Australia, and Canada, with targeted support for GRE/TOEFL/IELTS preparation, visa guidance, and pre-departure orientation. The Career Guidance Cell's GATE coaching programme has progressively improved student rankings year on year.",
    highlights: [
      'M.Tech programmes: CSE, VLSI Design, Power Electronics, Software Engineering',
      'Ph.D. programmes in CSE, ECE, and EEE',
      'MBA programme offered on campus',
      'NAAC approved, NBA Accredited, UGC 12B & 2f recognised',
      'GSAC maintains directory of 300+ international universities',
      '30+ specialised research and innovation facilities on campus',
      'GATE coaching with progressive year-on-year improvement in student rankings',
    ],
    outcomes: [
      'Students successfully admitted to graduate programmes in USA, UK, Australia, Canada, and Germany',
      'Progressive improvement in GATE rankings through structured coaching',
    ],
    partners: [],
    tableData: [],
  },
];

export function findPlacementItemBySlug(slug: string): PlacementItem | null {
  return placementItems.find((i) => i.slug === slug) ?? null;
}
