export interface ProgramData {
  slug: string;
  name: string;
  shortName: string;
  icon: string;
  category: 'btech' | 'mtech' | 'mba' | 'phd';
  intake: number;
  established: string;
  accreditation: string;
  hod?: string;
  heroImage: string;
  about: string;
  highlights: string[];
  labs: string[];
  outcomes: string[];
  semesters?: { label: string; subjects: string[] }[];
}

export const programs: ProgramData[] = [
  // ── B.Tech ──────────────────────────────────────────────────────────────
  {
    slug: 'cse',
    name: 'Computer Science & Engineering',
    shortName: 'B.Tech CSE',
    icon: '💻',
    category: 'btech',
    intake: 180,
    established: '2001-02',
    accreditation: 'NBA Tier-I Accredited',
    hod: 'Dr. Pokkuluri Kiran Sree',
    heroImage: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1920&q=80',
    about:
      'The Department of Computer Science & Engineering, established in 2001–02, is one of the oldest and most prestigious departments at VWU. With NBA Tier-I accreditation, the department offers a rigorous 4-year B.Tech programme focused on core computing, software development, artificial intelligence, and emerging technologies. Students benefit from industry-grade laboratories, expert faculty, and a strong placement record with top IT companies.',
    highlights: [
      'NBA Tier-I Accredited undergraduate programme',
      'Established in 2001–02 with 20+ years of academic excellence',
      'State-of-the-art computing labs with latest hardware and software',
      'Industry partnerships with TCS, Infosys, Wipro, Microsoft, and Google',
      'Active student chapters: IEEE, ACM, CSI',
      'Strong placement record — 95%+ students placed in top IT firms',
      'Expert faculty with PhDs from premier institutes',
      'Research publications in Scopus-indexed and SCI journals',
    ],
    labs: [
      'Advanced Computing Lab',
      'Data Structures & Algorithms Lab',
      'Database Management Systems Lab',
      'Operating Systems Lab',
      'Web Technologies Lab',
      'Machine Learning & AI Lab',
      'Network Security Lab',
      'Software Engineering Lab',
    ],
    outcomes: [
      'Software Engineer / Developer',
      'Data Scientist / ML Engineer',
      'Cloud Solutions Architect',
      'Full-Stack Web Developer',
      'Systems Analyst',
      'Research Scientist / Ph.D. Scholar',
      'Product Manager',
      'Cybersecurity Analyst',
    ],
    semesters: [
      { label: 'Semester I', subjects: ['Engineering Mathematics I', 'Engineering Physics', 'Programming for Problem Solving', 'Engineering Drawing', 'English for Communication'] },
      { label: 'Semester II', subjects: ['Engineering Mathematics II', 'Engineering Chemistry', 'Data Structures', 'Digital Logic Design', 'Environmental Science'] },
      { label: 'Semester III', subjects: ['Discrete Mathematics', 'Computer Organization', 'Object-Oriented Programming', 'Database Management Systems', 'Operating Systems'] },
      { label: 'Semester IV', subjects: ['Design & Analysis of Algorithms', 'Theory of Computation', 'Computer Networks', 'Software Engineering', 'Web Technologies'] },
      { label: 'Semester V', subjects: ['Compiler Design', 'Artificial Intelligence', 'Machine Learning', 'Cloud Computing', 'Elective I'] },
      { label: 'Semester VI', subjects: ['Distributed Systems', 'Information Security', 'Big Data Analytics', 'Elective II', 'Mini Project'] },
      { label: 'Semester VII', subjects: ['Deep Learning', 'IoT & Embedded Systems', 'Elective III', 'Elective IV', 'Project Phase I'] },
      { label: 'Semester VIII', subjects: ['Project Phase II', 'Internship / Industrial Training', 'Professional Ethics', 'Elective V'] },
    ],
  },
  {
    slug: 'ai-ml',
    name: 'CSE – Artificial Intelligence & Machine Learning',
    shortName: 'B.Tech AI & ML',
    icon: '🤖',
    category: 'btech',
    intake: 180,
    established: '2020-21',
    accreditation: '—',
    hod: 'Dr. Pokkuluri Kiran Sree',
    heroImage: 'https://images.unsplash.com/photo-1555255707-c07966088b7b?w=1920&q=80',
    about:
      'The B.Tech in CSE – Artificial Intelligence & Machine Learning, launched in 2020–21, is a specialisation programme designed to train engineers in cutting-edge AI and ML technologies. The curriculum blends the foundations of computer science with advanced topics in deep learning, natural language processing, computer vision, and intelligent system design. Partnerships with AWS and industry leaders provide students with hands-on cloud-based and real-world project experience.',
    highlights: [
      'Specialisation in AI, ML, Deep Learning, and NLP',
      'AWS Virtual Labs for cloud-based AI/ML training',
      'Industry-designed curriculum with real-world project focus',
      'Collaboration with AI research labs and tech companies',
      'Hands-on experience with TensorFlow, PyTorch, and Keras',
      'Exposure to generative AI and large language models',
      'Student projects in healthcare AI, computer vision, and NLP',
      'Strong placement record in AI/ML-focused roles',
    ],
    labs: [
      'AI & Machine Learning Lab',
      'Deep Learning Lab (GPU-enabled)',
      'Natural Language Processing Lab',
      'Computer Vision Lab',
      'AWS Cloud Lab',
      'Data Science & Analytics Lab',
      'Robotics & Autonomous Systems Lab',
    ],
    outcomes: [
      'Machine Learning Engineer',
      'AI Research Scientist',
      'Data Scientist',
      'NLP Engineer',
      'Computer Vision Engineer',
      'MLOps / AI Platform Engineer',
      'AI Product Manager',
      'Doctoral Research in AI',
    ],
    semesters: [
      { label: 'Semester I', subjects: ['Engineering Mathematics I', 'Programming for Problem Solving', 'Engineering Physics', 'English for Communication', 'Engineering Drawing'] },
      { label: 'Semester II', subjects: ['Engineering Mathematics II', 'Data Structures', 'Digital Logic Design', 'Statistics & Probability', 'Environmental Science'] },
      { label: 'Semester III', subjects: ['Discrete Mathematics', 'Object-Oriented Programming', 'Database Management Systems', 'Linear Algebra for ML', 'Python Programming'] },
      { label: 'Semester IV', subjects: ['Machine Learning Foundations', 'Computer Networks', 'Operating Systems', 'Data Mining & Warehousing', 'Web Technologies'] },
      { label: 'Semester V', subjects: ['Deep Learning', 'Natural Language Processing', 'Computer Vision', 'Cloud Computing (AWS)', 'Elective I'] },
      { label: 'Semester VI', subjects: ['Reinforcement Learning', 'AI Ethics & Responsible AI', 'Big Data Analytics', 'Elective II', 'Mini Project'] },
      { label: 'Semester VII', subjects: ['Generative AI & LLMs', 'MLOps & Model Deployment', 'Elective III', 'Elective IV', 'Project Phase I'] },
      { label: 'Semester VIII', subjects: ['Project Phase II', 'Internship / Industrial Training', 'Professional Ethics', 'Elective V'] },
    ],
  },
  {
    slug: 'ai-ds',
    name: 'CSE – Artificial Intelligence & Data Science',
    shortName: 'B.Tech AI & DS',
    icon: '📊',
    category: 'btech',
    intake: 120,
    established: '2020-21',
    accreditation: '—',
    hod: 'Dr. Pokkuluri Kiran Sree',
    heroImage: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1920&q=80',
    about:
      'The B.Tech in CSE – Artificial Intelligence & Data Science, introduced in 2020–21, prepares students to harness the power of data and intelligent algorithms to solve real-world problems. The programme offers in-depth training in statistical analysis, data engineering, machine learning, and business intelligence, equipping graduates to thrive in the data-driven industries of tomorrow. AWS Virtual Labs integrate cloud-scale data processing into the curriculum.',
    highlights: [
      'Specialisation in data analytics, AI, and business intelligence',
      'AWS Virtual Labs for cloud-scale data engineering',
      'Curriculum aligned with industry certifications (AWS, Tableau, Power BI)',
      'Hands-on capstone projects with real datasets',
      'Exposure to big data tools: Spark, Hadoop, and Kafka',
      'Industry partnerships for live data science internships',
      'Strong focus on visualisation, dashboarding, and storytelling with data',
      'Robust research output in data science and applied AI',
    ],
    labs: [
      'Data Science & Analytics Lab',
      'Big Data Processing Lab (Hadoop/Spark)',
      'AI & Machine Learning Lab',
      'AWS Cloud Data Lab',
      'Business Intelligence & Visualization Lab',
      'Statistical Computing Lab',
      'IoT Data Analytics Lab',
    ],
    outcomes: [
      'Data Scientist',
      'Data Engineer / Data Architect',
      'Business Intelligence Analyst',
      'AI/ML Engineer',
      'Analytics Consultant',
      'Research Analyst',
      'Cloud Data Engineer',
      'Doctoral Research in Data Science',
    ],
    semesters: [
      { label: 'Semester I', subjects: ['Engineering Mathematics I', 'Programming for Problem Solving', 'Engineering Physics', 'English for Communication', 'Engineering Drawing'] },
      { label: 'Semester II', subjects: ['Engineering Mathematics II', 'Statistics & Probability', 'Data Structures', 'Python for Data Science', 'Environmental Science'] },
      { label: 'Semester III', subjects: ['Linear Algebra & Calculus', 'Database Systems', 'Data Wrangling & EDA', 'Machine Learning I', 'Web Technologies'] },
      { label: 'Semester IV', subjects: ['Machine Learning II', 'Data Mining', 'Cloud Computing (AWS)', 'Big Data Technologies', 'Data Visualisation'] },
      { label: 'Semester V', subjects: ['Deep Learning', 'Natural Language Processing', 'Business Intelligence', 'Time Series Analysis', 'Elective I'] },
      { label: 'Semester VI', subjects: ['Recommender Systems', 'AI Ethics & Governance', 'Real-Time Analytics (Kafka)', 'Elective II', 'Mini Project'] },
      { label: 'Semester VII', subjects: ['Generative AI', 'MLOps & DataOps', 'Elective III', 'Elective IV', 'Project Phase I'] },
      { label: 'Semester VIII', subjects: ['Project Phase II', 'Industry Internship', 'Professional Ethics', 'Elective V'] },
    ],
  },
  {
    slug: 'cyber-security',
    name: 'CSE – Cyber Security',
    shortName: 'B.Tech Cyber Security',
    icon: '🔒',
    category: 'btech',
    intake: 60,
    established: '2021-22',
    accreditation: 'NBA Tier-I Accredited',
    hod: 'Dr. Pokkuluri Kiran Sree',
    heroImage: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=1920&q=80',
    about:
      'The B.Tech in CSE – Cyber Security equips students with advanced skills in protecting digital infrastructure, networks, and data from cyber threats. The programme covers ethical hacking, digital forensics, cryptography, network security, and security operations — preparing graduates for high-demand roles in the fast-growing cybersecurity domain. With NBA Tier-I accreditation and industry-standard labs, this programme is among the best in the region.',
    highlights: [
      'NBA Tier-I Accredited programme under CSE department',
      'Focus on ethical hacking, penetration testing, and digital forensics',
      'Industry-standard cybersecurity tools: Kali Linux, Wireshark, Metasploit',
      'Curriculum aligned with EC-Council and CompTIA certifications',
      'Dedicated Cyber Security Operations Centre (CSOC)',
      'Live vulnerability assessment and threat intelligence exercises',
      'Partnerships with cybersecurity firms and CERT-In',
      'Guest lectures from industry experts in information security',
    ],
    labs: [
      'Cyber Security Operations Centre (CSOC)',
      'Network Security Lab',
      'Digital Forensics Lab',
      'Ethical Hacking & Penetration Testing Lab',
      'Cryptography & Secure Protocols Lab',
      'Malware Analysis Lab',
      'Cloud Security Lab',
    ],
    outcomes: [
      'Cybersecurity Analyst',
      'Ethical Hacker / Penetration Tester',
      'Digital Forensic Investigator',
      'Security Operations Centre (SOC) Analyst',
      'Network Security Engineer',
      'Information Security Manager',
      'Cloud Security Specialist',
      'Security Consultant',
    ],
    semesters: [
      { label: 'Semester I', subjects: ['Engineering Mathematics I', 'Programming for Problem Solving', 'Engineering Physics', 'English for Communication', 'Engineering Drawing'] },
      { label: 'Semester II', subjects: ['Engineering Mathematics II', 'Data Structures', 'Digital Logic Design', 'Computer Networks Fundamentals', 'Environmental Science'] },
      { label: 'Semester III', subjects: ['Operating Systems', 'Object-Oriented Programming', 'Network Protocols & Architecture', 'Cryptography Foundations', 'Database Systems'] },
      { label: 'Semester IV', subjects: ['Network Security', 'Web Application Security', 'Linux Systems Administration', 'Python for Security', 'Cyber Laws & Ethics'] },
      { label: 'Semester V', subjects: ['Ethical Hacking & Pen Testing', 'Digital Forensics', 'Cloud Security', 'Malware Analysis', 'Elective I'] },
      { label: 'Semester VI', subjects: ['Security Operations Centre (SOC)', 'Intrusion Detection Systems', 'Incident Response', 'Elective II', 'Mini Project'] },
      { label: 'Semester VII', subjects: ['Advanced Threats & APT', 'Zero-Trust Architecture', 'Elective III', 'Elective IV', 'Project Phase I'] },
      { label: 'Semester VIII', subjects: ['Project Phase II', 'Industry Internship', 'Professional Ethics', 'Elective V'] },
    ],
  },
  {
    slug: 'it',
    name: 'Information Technology',
    shortName: 'B.Tech IT',
    icon: '🌐',
    category: 'btech',
    intake: 180,
    established: '2001-02',
    accreditation: 'NBA Tier-I Accredited (June 2019)',
    hod: 'Dr. D. Venkata Naga Raju',
    heroImage: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=1920&q=80',
    about:
      'The Department of Information Technology, established in 2001–02 and NBA Tier-I accredited since June 2019, delivers a comprehensive B.Tech programme focused on web technologies, cloud computing, software development, and networking. The department combines foundational IT education with emerging technologies, enabling graduates to thrive in both software development and IT management roles across industry.',
    highlights: [
      'NBA Tier-I Accredited since June 2019',
      'Established in 2001–02 with over two decades of excellence',
      'Strong focus on full-stack development, cloud, and networking',
      'Industry certifications: AWS, Azure, Google Cloud, Cisco',
      'Live project labs and hackathon participation',
      'Active placement record in IT services and product companies',
      'Collaborations with Microsoft, IBM, and Oracle for curriculum development',
      'Research projects in IoT, blockchain, and cloud-native applications',
    ],
    labs: [
      'Web Technologies & Full-Stack Lab',
      'Cloud Computing Lab (AWS/Azure)',
      'Networking & Cisco Lab',
      'Database Systems Lab',
      'Mobile Application Development Lab',
      'IoT & Embedded Systems Lab',
      'Software Testing & Automation Lab',
      'Blockchain & Distributed Systems Lab',
    ],
    outcomes: [
      'Full-Stack Web Developer',
      'Cloud Solutions Architect',
      'Network Administrator',
      'Software Development Engineer',
      'DevOps Engineer',
      'IT Consultant / Solutions Analyst',
      'Mobile Application Developer',
      'System Administrator',
    ],
    semesters: [
      { label: 'Semester I', subjects: ['Engineering Mathematics I', 'Programming for Problem Solving', 'Engineering Physics', 'English for Communication', 'Engineering Drawing'] },
      { label: 'Semester II', subjects: ['Engineering Mathematics II', 'Data Structures', 'Digital Systems', 'Computer Organisation', 'Environmental Science'] },
      { label: 'Semester III', subjects: ['Discrete Mathematics', 'Object-Oriented Programming', 'Database Management Systems', 'Operating Systems', 'Web Technologies I'] },
      { label: 'Semester IV', subjects: ['Design & Analysis of Algorithms', 'Computer Networks', 'Web Technologies II', 'Software Engineering', 'Linux & Open Source'] },
      { label: 'Semester V', subjects: ['Cloud Computing', 'Mobile Application Development', 'Network Security', 'DevOps & CI/CD', 'Elective I'] },
      { label: 'Semester VI', subjects: ['Microservices & Containerisation', 'IoT Systems', 'Blockchain Technology', 'Elective II', 'Mini Project'] },
      { label: 'Semester VII', subjects: ['Serverless Architecture', 'AI/ML for IT Systems', 'Elective III', 'Elective IV', 'Project Phase I'] },
      { label: 'Semester VIII', subjects: ['Project Phase II', 'Industry Internship', 'Professional Ethics', 'Elective V'] },
    ],
  },
  {
    slug: 'ece',
    name: 'Electronics & Communication Engineering',
    shortName: 'B.Tech ECE',
    icon: '📡',
    category: 'btech',
    intake: 120,
    established: '2001-02',
    accreditation: 'NBA Tier-I Accredited',
    hod: 'Dr. K. Padma Vasavi',
    heroImage: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=1920&q=80',
    about:
      'The Department of Electronics & Communication Engineering, established in 2001–02, offers an NBA Tier-I accredited 4-year B.Tech programme with an intake of 120 students. The curriculum covers analog and pulse circuits, digital communications, signals and systems, IC design, embedded systems, RF engineering, and wireless networks. Students apply electronics and communication concepts to solve real-world problems across 8 semesters of 16 weeks each, supported by state-of-the-art laboratories and expert faculty.',
    highlights: [
      'NBA Tier-I Accredited undergraduate programme',
      'Established in 2001–02 with over two decades of academic excellence',
      'Curriculum covers IC design, embedded systems, RF engineering, and wireless networks',
      'M.Tech (VLSI Design) postgraduate programme — NBA Tier-II Accredited',
      'Research in 5G communications, antenna design, and signal processing',
      'Industry tie-ups for live projects, internships, and placement support',
      'Active participation in national and international technical competitions',
      'Expert faculty publishing in IEEE Transactions, Elsevier, and Springer journals',
    ],
    labs: [
      'VLSI Design Lab',
      'Embedded Systems Lab',
      'Signal Processing Lab',
      'Microprocessors & Microcontrollers Lab',
      'Analog & Digital Communications Lab',
      'RF & Microwave Lab',
      'IoT & Sensor Networks Lab',
      'Advanced Electronics Lab',
    ],
    outcomes: [
      'VLSI / ASIC Design Engineer',
      'Embedded Systems Engineer',
      'RF & Communications Engineer',
      'IoT Solutions Developer',
      'Signal Processing Engineer',
      'Electronics Design Consultant',
      'Research Engineer / Doctoral Scholar',
      'Government R&D Engineer (DRDO, ISRO, BEL)',
    ],
    semesters: [
      { label: 'Semester I', subjects: ['Engineering Mathematics I', 'Engineering Physics', 'Programming for Problem Solving', 'Engineering Drawing', 'English for Communication'] },
      { label: 'Semester II', subjects: ['Engineering Mathematics II', 'Engineering Chemistry', 'Basic Electrical Engineering', 'Digital Logic Design', 'Environmental Science'] },
      { label: 'Semester III', subjects: ['Engineering Mathematics III', 'Electronic Devices & Circuits', 'Signals & Systems', 'Network Analysis', 'Object-Oriented Programming'] },
      { label: 'Semester IV', subjects: ['Analog Communications', 'Digital Communications', 'Analog & Pulse Circuits', 'Electromagnetic Waves & Transmission Lines', 'Control Systems'] },
      { label: 'Semester V', subjects: ['VLSI Design', 'Embedded Systems', 'Digital Signal Processing', 'Microprocessors & Microcontrollers', 'Elective I'] },
      { label: 'Semester VI', subjects: ['RF Engineering', 'Wireless Communications', 'IC Applications', 'Elective II', 'Mini Project'] },
      { label: 'Semester VII', subjects: ['5G & Advanced Communications', 'IoT Systems', 'Elective III', 'Elective IV', 'Project Phase I'] },
      { label: 'Semester VIII', subjects: ['Project Phase II', 'Industry Internship', 'Professional Ethics', 'Elective V'] },
    ],
  },
  {
    slug: 'eee',
    name: 'Electrical & Electronics Engineering',
    shortName: 'B.Tech EEE',
    icon: '⚡',
    category: 'btech',
    intake: 60,
    established: '2002',
    accreditation: 'NBA Tier-I Accredited',
    hod: 'Dr. S. M. Padmaja',
    heroImage: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=1920&q=80',
    about:
      'The Department of Electrical & Electronics Engineering, established in 2002, offers an NBA Tier-I accredited B.Tech programme with an annual intake of 60 students. The department is structured around experienced faculty and state-of-the-art laboratory facilities, equipping students with hands-on expertise in power systems, electrical machines, control systems, smart grids, renewable energy, electric vehicles, and industrial automation. An M.Tech in Power Electronics (NBA Tier-II, 9 seats) is also offered.',
    highlights: [
      'NBA Tier-I Accredited B.Tech programme',
      'M.Tech (Power Electronics) — NBA Tier-II Accredited, 9 seats',
      'Curriculum covers smart grids, EVs, renewable energy, and AI-based control',
      'Dedicated labs for power electronics, electric drives, and renewable energy',
      'Focus on electric vehicles, IoT-enabled systems, and battery management',
      'Industry internships with power utilities, EV companies, and automation firms',
      'Experienced faculty with cutting-edge research in FACTS and energy storage',
      'Hands-on training in industrial automation and robotics',
    ],
    labs: [
      'Power Systems Lab',
      'Electrical Machines Lab',
      'Power Electronics Lab',
      'Control Systems Lab',
      'Renewable Energy Systems Lab',
      'Measurements & Instrumentation Lab',
      'Electric Drives Lab',
      'Smart Grid & IoT Lab',
    ],
    outcomes: [
      'Power Systems Engineer',
      'Electrical Design Engineer',
      'Renewable Energy / Solar Systems Engineer',
      'Smart Grid & EV Engineer',
      'Industrial Automation Engineer',
      'Control Systems Engineer',
      'Government / PSU Engineer (APEPDCL, NTPC, BHEL)',
      'Research Engineer / Doctoral Scholar',
    ],
    semesters: [
      { label: 'Semester I', subjects: ['Engineering Mathematics I', 'Engineering Physics', 'Programming for Problem Solving', 'Engineering Drawing', 'English for Communication'] },
      { label: 'Semester II', subjects: ['Engineering Mathematics II', 'Engineering Chemistry', 'Basic Electronics', 'Digital Logic Design', 'Environmental Science'] },
      { label: 'Semester III', subjects: ['Engineering Mathematics III', 'Electrical Circuits', 'Electronic Devices & Circuits', 'Signals & Systems', 'Electrical Machines I'] },
      { label: 'Semester IV', subjects: ['Electrical Machines II', 'Control Systems', 'Power Systems I', 'Measurements & Instrumentation', 'Microprocessors & Microcontrollers'] },
      { label: 'Semester V', subjects: ['Power Systems II', 'Power Electronics', 'Electric Drives', 'Switchgear & Protection', 'Elective I'] },
      { label: 'Semester VI', subjects: ['Smart Grids', 'Renewable Energy Systems', 'Industrial Automation', 'Elective II', 'Mini Project'] },
      { label: 'Semester VII', subjects: ['Electric Vehicles & Charging Infrastructure', 'AI-based Control Systems', 'Elective III', 'Elective IV', 'Project Phase I'] },
      { label: 'Semester VIII', subjects: ['Project Phase II', 'Industry Internship', 'Professional Ethics', 'Elective V'] },
    ],
  },
  {
    slug: 'ce',
    name: 'Civil Engineering',
    shortName: 'B.Tech CE',
    icon: '🏗️',
    category: 'btech',
    intake: 60,
    established: '2009',
    accreditation: 'NBA Tier-I Accredited',
    hod: 'Dr. Pala Gireesh Kumar',
    heroImage: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=1920&q=80',
    about:
      'The Department of Civil Engineering, established in 2009, offers an NBA Tier-I accredited B.Tech programme with an annual intake of 60 students. The department specialises across structural engineering, environmental engineering, geotechnical engineering, remote sensing & GIS, transportation engineering, hydraulics & water resources, and surveying. With growing collaborations with national and international institutions, funded research projects, and patents, the department is committed to preparing the next generation of engineering innovators and leaders.',
    highlights: [
      'NBA Tier-I Accredited B.Tech programme',
      'Specialisations in structural, environmental, geotechnical, and transportation engineering',
      'Remote Sensing & GIS — a specialised focus area within the curriculum',
      'Unique facilities: Concrete Canoe Making Lab and Drone Technology Lab',
      'Three on-campus Sewage Treatment Plants for environmental engineering practicals',
      'Dream House Construction Laboratory for hands-on structural design',
      'Growing national and international institutional collaborations',
      'Active R&D with funded projects and patents',
    ],
    labs: [
      'Structural Engineering Lab',
      'Concrete Technology Lab (Dream House Construction Laboratory)',
      'Geotechnical Engineering Lab',
      'Environmental Engineering Lab & Sewage Treatment Plants',
      'Surveying Lab',
      'Transportation Engineering Lab',
      'Remote Sensing & GIS Lab',
      'Drone Technology Laboratory',
    ],
    outcomes: [
      'Structural Design Engineer',
      'Project / Site Engineer',
      'Construction Manager',
      'Geotechnical Engineer',
      'Environmental Engineer',
      'GIS & Remote Sensing Specialist',
      'Urban / Smart City Planner',
      'Government Engineer (NHAI, CPWD, Irrigation Dept.)',
    ],
    semesters: [
      { label: 'Semester I', subjects: ['Engineering Mathematics I', 'Engineering Physics', 'Programming for Problem Solving', 'Engineering Drawing', 'English for Communication'] },
      { label: 'Semester II', subjects: ['Engineering Mathematics II', 'Engineering Chemistry', 'Basic Electrical & Electronics', 'Mechanics of Solids', 'Environmental Science'] },
      { label: 'Semester III', subjects: ['Fluid Mechanics', 'Structural Analysis I', 'Building Materials & Construction', 'Surveying', 'Engineering Geology'] },
      { label: 'Semester IV', subjects: ['Structural Analysis II', 'Concrete Technology', 'Geotechnical Engineering I', 'Transportation Engineering I', 'Hydraulics & Water Resources I'] },
      { label: 'Semester V', subjects: ['Design of RC Structures', 'Geotechnical Engineering II', 'Environmental Engineering I', 'Transportation Engineering II', 'Elective I'] },
      { label: 'Semester VI', subjects: ['Design of Steel Structures', 'Environmental Engineering II', 'Remote Sensing & GIS', 'Elective II', 'Mini Project'] },
      { label: 'Semester VII', subjects: ['Estimation & Costing', 'Construction Management', 'Elective III', 'Elective IV', 'Project Phase I'] },
      { label: 'Semester VIII', subjects: ['Project Phase II', 'Industry Internship', 'Professional Ethics', 'Elective V'] },
    ],
  },
  {
    slug: 'me',
    name: 'Mechanical Engineering',
    shortName: 'B.Tech ME',
    icon: '⚙️',
    category: 'btech',
    intake: 60,
    established: '2009',
    accreditation: '—',
    hod: 'Dr. Ch. Hari Krishna',
    heroImage: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=1920&q=80',
    about:
      'The Department of Mechanical Engineering, established in 2009, equips students with a solid foundation in mathematics, physics, chemistry, and engineering sciences, alongside practical expertise in design, manufacturing, thermodynamics, and fluid mechanics. Faculty are organised into six specialised domains — CAD & Automation, Machine Design, Manufacturing Engineering, Thermal Engineering, Automobile Technology, and Fluid Mechanics — ensuring depth across all areas of the discipline. Student projects include robots, automated vehicles, solar-powered equipment, and alternative fuel systems.',
    highlights: [
      'Faculty expertise across 6 specialised domains: CAD, Design, Manufacturing, Thermal, Automobile, Fluid Mechanics',
      'Industry-standard CAD/CAE software: Solid Edge, AutoCAD, FEMAP, CAM Express, ANSYS',
      'Advanced materials lab with optical microscope, hardness tester, and heat treatment equipment',
      'Student projects in robotics, automated vehicles, solar equipment, and alternative fuels',
      'Emphasis on teamwork, leadership, and innovation in multidisciplinary environments',
      'Faculty active in research, seminars, conferences, and faculty development programmes',
      'Strong foundation in mathematics, physics, and core engineering sciences',
      'Industry internships with manufacturing, automotive, and energy companies',
    ],
    labs: [
      'CAD & Design Lab (Solid Edge, AutoCAD, FEMAP)',
      'CAM & Manufacturing Lab (CAM Express)',
      'FEA & Simulation Lab (ANSYS)',
      'Thermodynamics & Heat Transfer Lab',
      'Fluid Mechanics Lab',
      'Material Science Lab (Optical Microscope, Hardness Tester)',
      'Heat Treatment Lab (Quenching, Tempering, Induction Hardening)',
      'Metrology & Quality Control Lab',
    ],
    outcomes: [
      'Mechanical Design Engineer',
      'Manufacturing / Production Engineer',
      'Automotive Engineer',
      'Thermal / HVAC Systems Engineer',
      'Robotics & Automation Engineer',
      'CAD/CAE Engineer',
      'Project / Maintenance Engineer',
      'Research Engineer / Doctoral Scholar',
    ],
    semesters: [
      { label: 'Semester I', subjects: ['Engineering Mathematics I', 'Engineering Physics', 'Programming for Problem Solving', 'Engineering Drawing', 'English for Communication'] },
      { label: 'Semester II', subjects: ['Engineering Mathematics II', 'Engineering Chemistry', 'Basic Electrical & Electronics', 'Engineering Mechanics', 'Environmental Science'] },
      { label: 'Semester III', subjects: ['Engineering Mathematics III', 'Thermodynamics', 'Mechanics of Solids', 'Manufacturing Processes I', 'Material Science & Metallurgy'] },
      { label: 'Semester IV', subjects: ['Fluid Mechanics & Hydraulic Machines', 'Manufacturing Processes II', 'Machine Design I', 'Kinematics of Machinery', 'Metrology & Quality Control'] },
      { label: 'Semester V', subjects: ['Heat Transfer', 'Machine Design II', 'CAD/CAM', 'Dynamics of Machinery', 'Elective I'] },
      { label: 'Semester VI', subjects: ['Automobile Engineering', 'Industrial Engineering & Management', 'FEA using ANSYS', 'Elective II', 'Mini Project'] },
      { label: 'Semester VII', subjects: ['Robotics & Automation', 'Renewable Energy Systems', 'Elective III', 'Elective IV', 'Project Phase I'] },
      { label: 'Semester VIII', subjects: ['Project Phase II', 'Industry Internship', 'Professional Ethics', 'Elective V'] },
    ],
  },

  // ── M.Tech ──────────────────────────────────────────────────────────────
  {
    slug: 'mtech-cse',
    name: 'M.Tech – Computer Science & Engineering',
    shortName: 'M.Tech CSE',
    icon: '💻',
    category: 'mtech',
    intake: 18,
    established: '2008-09',
    accreditation: 'NBA Tier-II Accredited',
    hod: 'Dr. Pokkuluri Kiran Sree',
    heroImage: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1920&q=80',
    about:
      'The M.Tech in Computer Science & Engineering, offered under the NBA Tier-I accredited CSE Department (est. 2001–02), is a two-year postgraduate programme designed to develop advanced computing expertise, research aptitude, and industry leadership. The curriculum covers advanced algorithms, artificial intelligence, distributed computing, machine learning, and emerging areas of computer science, culminating in a research-oriented thesis and project. GATE-qualified students may pursue doctoral pathways after completion.',
    highlights: [
      'NBA Tier-II Accredited postgraduate programme under the CSE Department',
      'Advanced research in AI, ML, distributed systems, and cloud computing',
      'GATE-qualified students eligible for JRF and Ph.D. pathways',
      'Expert faculty with strong publication record in Scopus-indexed journals',
      'Full access to all CSE department state-of-the-art labs and computing resources',
      'Thesis-based curriculum with a strong industry project component',
      'Partnerships with TCS, Infosys, and leading IT product companies',
      'Active collaborations with national research institutions',
    ],
    labs: [
      'Advanced Computing Research Lab',
      'AI & Machine Learning Lab',
      'Distributed Systems & Cloud Computing Lab',
      'High-Performance Computing Lab',
      'Network Security Research Lab',
      'Data Science & Analytics Lab',
    ],
    outcomes: [
      'Senior Software Engineer / Architect',
      'Research Scientist / Principal Engineer',
      'Data Scientist / ML Engineer',
      'Ph.D. Scholar / Academic Researcher',
      'Technical Lead / Engineering Manager',
      'Cloud Solutions Architect',
    ],
  },
  {
    slug: 'mtech-vlsi',
    name: 'M.Tech – VLSI Design',
    shortName: 'M.Tech VLSI',
    icon: '🔬',
    category: 'mtech',
    intake: 18,
    established: '2009-10',
    accreditation: 'NBA Tier-II Accredited',
    hod: 'Dr. K. Padma Vasavi',
    heroImage: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=1920&q=80',
    about:
      'The M.Tech in VLSI Design, offered under the Department of Electronics & Communication Engineering (NBA Tier-II Accredited), provides comprehensive knowledge of VLSI circuits and systems essential for the electronics chip manufacturing industry. The programme covers system design, RF circuits, ASIC design, and FPGA-based systems, preparing graduates for careers in leading semiconductor companies and advanced research in microelectronics.',
    highlights: [
      'NBA Tier-II Accredited postgraduate programme under the ECE Department',
      'Comprehensive training in VLSI circuits, ASIC design, and FPGA-based systems',
      'Emphasis on RF circuits, system design, and chip manufacturing industry readiness',
      'Industry-standard EDA tools: Cadence, Synopsys, Mentor Graphics',
      'Research focus on low-power VLSI and advanced semiconductor technologies',
      'Access to all ECE department state-of-the-art research laboratories',
    ],
    labs: ['VLSI Design Lab', 'FPGA Prototyping Lab', 'RF & Mixed-Signal Design Lab', 'Semiconductor Devices Lab'],
    outcomes: [
      'VLSI / ASIC Design Engineer',
      'FPGA Engineer',
      'Semiconductor Research Scientist',
      'RF IC Design Engineer',
      'Embedded Hardware Engineer',
      'PhD Scholar in VLSI / Microelectronics',
    ],
  },
  {
    slug: 'mtech-power-electronics',
    name: 'M.Tech – Power Electronics',
    shortName: 'M.Tech Power Electronics',
    icon: '⚡',
    category: 'mtech',
    intake: 9,
    established: '2010-11',
    accreditation: 'NBA Tier-II Accredited',
    hod: 'Dr. S. M. Padmaja',
    heroImage: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=1920&q=80',
    about:
      'The M.Tech in Power Electronics, offered under the Department of Electrical & Electronics Engineering (NBA Tier-II Accredited, intake 9), provides advanced expertise in power semiconductor devices, converter design, control systems, and embedded applications. The programme equips graduates for leadership roles in the energy sector, EV industry, smart grid development, and industrial automation.',
    highlights: [
      'NBA Tier-II Accredited postgraduate programme under the EEE Department',
      'Advanced study in power semiconductor devices, converters, and control systems',
      'Focus on embedded applications, EV systems, and renewable energy integration',
      'MATLAB/Simulink and PSIM simulation-based training',
      'Access to dedicated power electronics, electric drives, and smart grid labs',
      'Industry partnerships with energy utilities, EV companies, and automation firms',
    ],
    labs: ['Power Electronics Lab', 'Electric Drives & Control Lab', 'Renewable Energy Systems Lab', 'Smart Grid & IoT Lab'],
    outcomes: [
      'Power Electronics Design Engineer',
      'EV Systems / Charging Infrastructure Engineer',
      'Renewable Energy Consultant',
      'Industrial Automation Engineer',
      'R&D Engineer in Power Systems',
      'PhD Scholar in Power Electronics',
    ],
  },
  {
    slug: 'mtech-software-engineering',
    name: 'M.Tech – Software Engineering',
    shortName: 'M.Tech Software Engg.',
    icon: '🌐',
    category: 'mtech',
    intake: 18,
    established: '2010-11',
    accreditation: 'NBA Tier-II Accredited',
    hod: 'Dr. Pokkuluri Kiran Sree',
    heroImage: 'https://images.unsplash.com/photo-1555952517-2e8e729e0b44?w=1920&q=80',
    about:
      'The M.Tech in Software Engineering, offered under the NBA-accredited CSE Department (est. 2001–02), provides advanced expertise in software architecture, formal methods, testing, project management, and enterprise system design. The programme is well-suited for working professionals and GATE scholars aiming to develop technical depth in software systems, DevOps practices, and large-scale software project leadership.',
    highlights: [
      'NBA Tier-II Accredited postgraduate programme under the CSE Department',
      'Advanced training in software architecture, design patterns, and formal methods',
      'Project management curriculum aligned with industry PMP standards',
      'Emphasis on DevOps, CI/CD pipelines, and agile development practices',
      'Research in distributed software systems, microservices, and cloud-native apps',
      'Industry internship and live project components with IT sector partners',
      'Access to all CSE department labs: cloud, networking, and AI computing resources',
      'Expert faculty with experience in large-scale enterprise software delivery',
    ],
    labs: [
      'Software Architecture & Design Lab',
      'Testing & QA Automation Lab',
      'DevOps & Cloud Lab',
      'Enterprise Systems & ERP Lab',
      'Agile Project Management Lab',
    ],
    outcomes: [
      'Software Architect',
      'Senior Software Engineer / Tech Lead',
      'QA Lead / Test Manager',
      'DevOps / Site Reliability Engineer',
      'Project Manager / Scrum Master',
      'Technology Consultant',
    ],
  },

  // ── MBA & Ph.D. ─────────────────────────────────────────────────────────
  {
    slug: 'mba',
    name: 'Master of Business Administration',
    shortName: 'MBA',
    icon: '💼',
    category: 'mba',
    intake: 60,
    established: '2008',
    accreditation: 'AICTE Approved | JNTU Kakinada Affiliated',
    heroImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1920&q=80',
    about:
      'The MBA programme, started in 2008 and affiliated to JNTU Kakinada, was established with the objective of training young women to effectively take up responsibility as management leaders, senior administrators, and executives in the industry. The two-year, 4-semester programme comprises 33 subjects including elective specialisation courses, an industry internship, and a structured project. The syllabus receives regular updates based on evolving industry needs, ensuring graduates are ready for today\'s dynamic business environment.',
    highlights: [
      'AICTE Approved | Affiliated to JNTU Kakinada',
      '2-year, 4-semester programme with 33 subjects including electives',
      'Industry internship resulting in a structured management project',
      'Frequent interaction with eminent professors, industry experts, and business leaders',
      'Social projects providing practical field experience and community impact',
      'Infrastructure and labs progressively developed to align with industry standards',
      'Regular syllabus updates driven by industry trends and employer feedback',
      'Focus on developing management leaders, senior administrators, and corporate executives',
    ],
    labs: [
      'Business Analytics Lab',
      'ERP & Management Information Systems Lab',
      'Department Library & Management Resource Centre',
      'Language & Presentation Skills Lab',
    ],
    outcomes: [
      'Business Analyst / Management Consultant',
      'Finance Manager / Investment Analyst',
      'Marketing Manager / Brand Strategist',
      'Human Resources Manager',
      'Operations Manager / Supply Chain Analyst',
      'Entrepreneur / Start-up Founder',
      'Senior Administrator / Corporate Executive',
    ],
    semesters: [
      { label: 'Semester I', subjects: ['Management & Organisational Behaviour', 'Managerial Economics', 'Financial Accounting', 'Business Statistics', 'Business Communication', 'IT for Managers'] },
      { label: 'Semester II', subjects: ['Marketing Management', 'Financial Management', 'Human Resource Management', 'Operations Management', 'Business Research Methods', 'Elective I'] },
      { label: 'Semester III', subjects: ['Strategic Management', 'Entrepreneurship Development', 'Elective II', 'Elective III', 'Elective IV', 'Industry Internship'] },
      { label: 'Semester IV', subjects: ['Project Management', 'Corporate Governance & Ethics', 'Elective V', 'Elective VI', 'Comprehensive Viva', 'Project Report & Presentation'] },
    ],
  },
  {
    slug: 'phd-cse',
    name: 'Ph.D. – Computer Science & Engineering',
    shortName: 'Ph.D. CSE',
    icon: '🎓',
    category: 'phd',
    intake: 10,
    established: '2012-13',
    accreditation: 'JNTUK-recognised Research Centre',
    hod: 'Dr. Pokkuluri Kiran Sree',
    heroImage: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1920&q=80',
    about:
      'VWU is a JNTUK-recognised research centre offering Ph.D. programmes in Computer Science & Engineering under the NBA Tier-I accredited CSE Department (est. 2001–02). Research scholars work on cutting-edge areas including artificial intelligence, machine learning, data science, cybersecurity, cloud computing, and IoT under the guidance of experienced faculty with strong publication records in Scopus-indexed and SCI journals. Both full-time and part-time modes are available.',
    highlights: [
      'JNTUK-recognised Ph.D. research centre under the NBA-accredited CSE Department',
      'Research areas: AI, ML, Data Science, Cybersecurity, Cloud Computing, IoT',
      'Scholars publish in Scopus-indexed, SCI, and SCIE-indexed journals',
      'Full-time and part-time (working professional) modes available',
      'Research funding through DST, AICTE, and institutional grants',
      'Access to GPU clusters, HPC computing, and advanced AI research labs',
      'Faculty research collaborations with national institutions and industry partners',
      'Interdisciplinary research encouraged across ECE, EEE, and IT domains',
    ],
    labs: [
      'AI & Deep Learning Research Lab',
      'High-Performance Computing Cluster (GPU)',
      'Data Science & Analytics Research Lab',
      'Cybersecurity & Network Research Lab',
      'Cloud Computing & IoT Research Lab',
    ],
    outcomes: [
      'Academic Researcher / Assistant Professor',
      'Senior Research Scientist',
      'Principal Engineer / R&D Lead',
      'Technology Policy Analyst',
      'Postdoctoral Researcher',
      'Government Research Scientist (C-DAC, NIC)',
    ],
  },
  {
    slug: 'phd-ece',
    name: 'Ph.D. – Electronics & Communication Engineering',
    shortName: 'Ph.D. ECE',
    icon: '📡',
    category: 'phd',
    intake: 6,
    established: '2012-13',
    accreditation: 'JNTUK-recognised Research Centre',
    hod: 'Dr. K. Padma Vasavi',
    heroImage: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=1920&q=80',
    about:
      'The Ph.D. programme in Electronics & Communication Engineering at VWU is offered under the NBA Tier-I accredited ECE Department (est. 2001–02). Research scholars conduct doctoral research in VLSI design, signal processing, wireless communications, antenna design, embedded systems, and RF engineering. Scholars contribute to fundamental and applied research, publishing in leading international journals, with access to industry-standard EDA tools and communication labs.',
    highlights: [
      'JNTUK-recognised doctoral research centre under the NBA-accredited ECE Department',
      'Research areas: VLSI, 5G Communications, Signal Processing, Antenna Design, RF Engineering',
      'Publications in IEEE Transactions, Elsevier, and Springer journals',
      'Research funding through DST, DRDO, and SERB grants',
      'Full-time and part-time modes available',
      'Access to VLSI, FPGA, RF, and embedded systems research labs',
      'Collaboration with national research institutions: ISRO, DRDO, BEL',
      'Industry-standard EDA tools: Cadence, Synopsys, and Mentor Graphics',
    ],
    labs: [
      'VLSI & ASIC Design Research Lab',
      'Antenna & Microwave Research Lab',
      'Signal Processing Research Lab',
      'Embedded Systems Research Lab',
      'RF & Wireless Communications Lab',
    ],
    outcomes: [
      'Academic Researcher / Assistant Professor',
      'Senior VLSI / RF Research Engineer',
      'R&D Scientist at ISRO / DRDO / BEL',
      'Postdoctoral Researcher',
      'Technology Consultant / Standards Expert',
    ],
  },
  {
    slug: 'phd-eee',
    name: 'Ph.D. – Electrical & Electronics Engineering',
    shortName: 'Ph.D. EEE',
    icon: '⚡',
    category: 'phd',
    intake: 6,
    established: '2013-14',
    accreditation: 'JNTUK-recognised Research Centre',
    hod: 'Dr. S. M. Padmaja',
    heroImage: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=1920&q=80',
    about:
      'The Ph.D. programme in Electrical & Electronics Engineering at VWU is conducted under the NBA Tier-I accredited EEE Department (est. 2002). Research scholars pursue doctoral research in power systems, smart grids, renewable energy, electric vehicles, AI-based control systems, IoT-enabled automation, and energy storage. Faculty publish in leading IEEE and Elsevier journals and lead nationally funded projects in the energy and EV domains.',
    highlights: [
      'JNTUK-recognised doctoral research centre under the NBA-accredited EEE Department',
      'Research areas: Power Systems, Smart Grids, Renewable Energy, EVs, AI Control, IoT',
      'Publications in IEEE Transactions, Elsevier, and Taylor & Francis journals',
      'Research funding from DST, MNRE, SERB, and AICTE',
      'Full-time and part-time modes available for working professionals',
      'Simulation tools: PSCAD, MATLAB/Simulink, PSIM, and ETAP',
      'Collaboration with power utilities, EV companies, and renewable energy firms',
      'Interdisciplinary research linking EEE with IoT, AI, and embedded systems',
    ],
    labs: [
      'Power Systems Research & Simulation Lab',
      'Renewable Energy Research Lab',
      'Smart Grid & IoT Research Lab',
      'Electric Vehicles & Battery Management Lab',
      'AI-based Control Systems Research Lab',
    ],
    outcomes: [
      'Academic Researcher / Assistant Professor',
      'Senior Power Systems Engineer',
      'R&D Scientist at NTPC / BHEL / NHPC',
      'Renewable Energy Research Consultant',
      'Postdoctoral Researcher',
      'EV Technology Lead / Energy Systems Architect',
    ],
  },
];

export function findProgramBySlug(slug: string): ProgramData | undefined {
  return programs.find((p) => p.slug === slug);
}
