export interface GovTableRow { [key: string]: string | number }

export interface GovItem {
  slug: string;
  title: string;
  category: 'governance' | 'committees' | 'iqac';
  icon: string;
  desc: string;
  intro?: string;
  about?: string;
  highlights?: string[];
  outcomes?: string[];
  tableData?: GovTableRow[];
  tableSections?: { title: string; rows: GovTableRow[] }[];
}

export const govItems: GovItem[] = [

  // ─── GOVERNANCE ────────────────────────────────────────────────────────────
  {
    slug: 'governing-body',
    title: 'Governing Body',
    category: 'governance',
    icon: '🏛️',
    desc: 'The apex body of VWU constituted as per AICTE norms, comprising representatives from management, faculty, industry, government, and regulatory bodies.',
    intro: 'The Governing Body is the highest decision-making authority of Vishnu Womens University. Constituted as per AICTE and UGC guidelines, it provides strategic direction, oversees institutional policy, approves budgets, and ensures compliance with regulatory norms.',
    about: 'The Governing Body meets at least twice a year and includes the Chairman of Sri Vishnu Educational Society, the Principal as Ex-Officio member, faculty representatives nominated by the Principal, nominees from the State Government, JNTUK, and UGC, and distinguished experts from industry and academia. It approves the annual budget, considers reports of the IQAC, and takes decisions on all major institutional matters.',
    highlights: [
      'Makes decisions on programme intake, additions, and discontinuation',
      'Approves annual financial budgets',
      'Reviews academic performance and recommends corrective actions',
      'Mobilises funding and optimises institutional resource utilisation',
      'Executes planning board recommendations',
      'Assesses stakeholder feedback and plans improvements',
      'Meetings held: 21.11.2025, 28.02.2025, 05.10.2024, 13.04.2024, 16.12.2023, 26.05.2023',
    ],
    tableData: [
      { 'S.No': 1,  Category: 'Management',               Nature: 'Trust representative, Chairperson', 'Member Name': 'Sri K.V. Vishnu Raju, Chairman, SVES' },
      { 'S.No': 2,  Category: 'Management',               Nature: 'Management nominee',               'Member Name': 'Sri Ravichandran Rajagopal, VC, SVES' },
      { 'S.No': 3,  Category: 'Management',               Nature: 'Management nominee',               'Member Name': 'Sri Aditya Vissam, Secretary, SVES' },
      { 'S.No': 4,  Category: 'Management',               Nature: 'Management nominee',               'Member Name': 'Sri K. Sai Sumant, Joint Secretary, SVES' },
      { 'S.No': 5,  Category: 'Management',               Nature: 'Management nominee',               'Member Name': 'Sri JVSSRD Prasada Raju, Director, SVES' },
      { 'S.No': 6,  Category: 'Teachers',                 Nature: 'Senior faculty nominee',           'Member Name': 'Prof. P. Venkata Rama Raju, Vice-Principal' },
      { 'S.No': 7,  Category: 'Teachers',                 Nature: 'Faculty nominee',                  'Member Name': 'Dr. S.M. Padmaja, Professor & Head, EEE' },
      { 'S.No': 8,  Category: 'Educationalist/Industrialist', Nature: 'Management nominee',          'Member Name': 'Dr. U. Chandra Sekhar, WIPRO, Bengaluru' },
      { 'S.No': 9,  Category: 'UGC Nominee',              Nature: 'External',                         'Member Name': 'Dr. Buddha Singh, JNU, New Delhi' },
      { 'S.No': 10, Category: 'State Government',         Nature: 'Higher education official',        'Member Name': 'Mr. J. Satyanarayana Murthy, RJD Technical Education' },
      { 'S.No': 11, Category: 'University Nominee',       Nature: 'External',                         'Member Name': 'Prof. GVR Prasada Raju, JNTUK, Kakinada' },
      { 'S.No': 12, Category: 'Principal',                Nature: 'Ex-Officio',                       'Member Name': 'Dr. G. Srinivasa Rao, Principal, SVECW' },
    ],
  },

  {
    slug: 'academic-council',
    title: 'Academic Council',
    category: 'governance',
    icon: '🎓',
    desc: 'The highest academic authority of VWU, chaired by the Principal, responsible for regulating and promoting all academic activities.',
    intro: 'The Academic Council is the supreme academic body of Vishnu Womens University. It is chaired by the Principal and is responsible for laying down policies on academic matters including curriculum, examination regulations, and the academic calendar.',
    about: 'The Academic Council comprises the Principal as Chairman, JNTUK university nominees, industry representatives, SVES Directors, the Vice-Principal, all Heads of Departments, and the Controller of Examinations. It reviews and approves syllabi recommended by the Boards of Studies, considers proposals for new programmes, and ensures academic standards are maintained across all departments.',
    highlights: [
      'Reviews academic matters on its own initiative or at the instance of Boards of Studies',
      'Exercises oversight on instructional methods and evaluation standards',
      'Establishes degree and diploma curriculum requirements',
      'Plans and conducts examinations per institutional bylaws',
      'Appoints examiners, moderators, and examination personnel',
      'Facilitates credential recognition with other institutions',
      'Meetings held: 10.06.2025, 03.07.2024, 18.10.2023, 24.02.2023, 17.09.2022, 10.03.2022',
    ],
    outcomes: [
      'Approved curriculum updates for 2020–24 and 2021–25 batches',
      'Introduced Choice Based Credit System (CBCS)',
      'Approved Minor and Honour specialisations across departments',
      'Recommended integration of industry certifications in curriculum',
    ],
    tableData: [
      { 'S.No': 1,  Name: 'Dr. G. Srinivasa Rao',          Designation: 'Principal, SVECW (Chairman)' },
      { 'S.No': 2,  Name: 'Prof. MHM Krishna Prasad',       Designation: 'Director – Academics, JNTUK (University Nominee)' },
      { 'S.No': 3,  Name: 'Prof. M. Sailaja',               Designation: 'Professor of ECE, UCEK, JNTUK (University Nominee)' },
      { 'S.No': 4,  Name: 'Prof. K. Meera Saheb',           Designation: 'Professor of ME, UCEK, JNTUK (University Nominee)' },
      { 'S.No': 5,  Name: 'Mr. K.A. Rama Krishnam Raju',   Designation: 'Project Manager, Tech Mahindra' },
      { 'S.No': 6,  Name: 'Sri J.V.S.S.R.D. Prasada Raju', Designation: 'Director (Admin.), SVES' },
      { 'S.No': 7,  Name: 'Dr. P. Srinivasa Raju',          Designation: 'Director – Student Affairs & Admin., SVES' },
      { 'S.No': 8,  Name: 'Prof. P. Venkata Rama Raju',     Designation: 'Vice-Principal, SVECW' },
      { 'S.No': 9,  Name: 'Dr. S.M. Padmaja',               Designation: 'Head of Department, EEE' },
      { 'S.No': 10, Name: 'Dr. K. Padma Vasavi',            Designation: 'Head of Department, ECE' },
      { 'S.No': 11, Name: 'Dr. P. Kiran Sree',              Designation: 'Head of Department, CSE' },
      { 'S.No': 12, Name: 'Dr. D.V. Naga Raju',             Designation: 'Head of Department, IT' },
      { 'S.No': 13, Name: 'Dr. Pala Gireesh Kumar',         Designation: 'Head of Department, Civil Engineering' },
      { 'S.No': 14, Name: 'Dr. Ch. Hari Krishna',           Designation: 'Head of Department, Mechanical Engineering' },
      { 'S.No': 15, Name: 'Dr. A. Sri Krishna',             Designation: 'Head of Department, CSE (AI Specialisations)' },
      { 'S.No': 16, Name: 'Dr. T.S.R. Murthy',              Designation: 'Head of Department, Mathematics & Physics' },
      { 'S.No': 17, Name: 'Dr. D. Ravi Kiran',              Designation: 'Head of Department, Chemistry & English' },
      { 'S.No': 18, Name: 'Dr. G. Subbaraju',               Designation: 'Head of Department, MBA' },
      { 'S.No': 19, Name: 'Mrs. P. Prashanti',              Designation: 'Assistant Professor, English' },
      { 'S.No': 20, Name: 'Mrs. P. Lavanya',                Designation: 'Assistant Professor, Civil Engineering' },
      { 'S.No': 21, Name: 'Dr. K.S.N. Raju',               Designation: 'Controller of Examinations, SVECW (Member Secretary)' },
    ],
  },

  {
    slug: 'board-of-studies',
    title: 'Board of Studies',
    category: 'governance',
    icon: '📚',
    desc: 'Department-wise academic bodies that design and recommend curriculum, syllabi, and teaching methodologies to the Academic Council.',
    intro: 'Each department of Vishnu Womens University has a Board of Studies (BoS) constituted to ensure curriculum relevance and academic excellence. The Board recommends courses of study, syllabi, and reference materials for each programme offered by the department.',
    about: 'Each Board of Studies is chaired by the Head of Department and includes university nominees from JNTUK/IITs/NITs, subject experts from academia, industry experts, and alumni representatives. Boards meet at least once per academic year to review and update curricula in line with industry trends, technological advancements, and AICTE/UGC guidelines. Recommendations are forwarded to the Academic Council for approval.',
    highlights: [
      'Constituted separately for each of the 14 programmes',
      'Chaired by the Head of Department',
      'Includes JNTUK/IIT/NIT university nominees',
      'Industry experts and alumni on every Board',
      'Meets at least once per academic year',
      'Recommends syllabus revisions, new electives, and emerging-tech integration',
    ],
    outcomes: [
      'Introduced 100+ new electives across departments since 2018',
      'Integrated Python, ML, IoT, and Cloud Computing into core curricula',
      'Added mandatory industry certification modules across all branches',
      'Aligned syllabi with NASSCOM, Microsoft, Amazon, and TCS frameworks',
    ],
    tableSections: [
      {
        title: 'Computer Science & Engineering',
        rows: [
          { 'S.No': 1, Name: 'Dr. P. Kiran Sree',                    Designation: 'Chairman' },
          { 'S.No': 2, Name: 'Dr. A.S.N. Chakravarthy',              Designation: 'University Nominee (JNTUK)' },
          { 'S.No': 3, Name: 'Dr. Madhu Mutyam',                     Designation: 'Subject Expert' },
          { 'S.No': 4, Name: 'Dr. M.V. Panduranga Rao',              Designation: 'Subject Expert' },
          { 'S.No': 5, Name: 'Sri. Siva Rama Sowri Varanasi',        Designation: 'Industry Expert' },
          { 'S.No': 6, Name: 'Dr. M. Sandhya',                       Designation: 'Graduate Meritorious Alumni' },
          { 'S.No': 7, Name: 'Ms. G. Geetha',                        Designation: 'PG Meritorious Alumni' },
          { 'S.No': 8, Name: 'Faculty Members of CSE, SVECW',        Designation: 'Members' },
        ],
      },
      {
        title: 'CSE [Cyber Security]',
        rows: [
          { 'S.No': 1, Name: 'Dr. P. Kiran Sree',                    Designation: 'Chairman' },
          { 'S.No': 2, Name: 'Dr. P. Radha Krishna',                  Designation: 'University Nominee (JNTUK)' },
          { 'S.No': 3, Name: 'Dr. M.V. Panduranga Rao',              Designation: 'Subject Expert' },
          { 'S.No': 4, Name: 'Dr. Manju Khari',                       Designation: 'Subject Expert' },
          { 'S.No': 5, Name: 'Sri. Siva Rama Sowri Varanasi',        Designation: 'Industry Expert' },
          { 'S.No': 6, Name: 'Dr. M. Sandhya',                       Designation: 'Graduate Meritorious Alumni' },
          { 'S.No': 7, Name: 'Ms. N V S K Vijaya Lakshmi K',         Designation: 'PG Meritorious Alumni' },
          { 'S.No': 8, Name: 'Faculty Members of CSE [CS], SVECW',   Designation: 'Members' },
        ],
      },
      {
        title: 'CSE [Artificial Intelligence & Data Science]',
        rows: [
          { 'S.No': 1, Name: 'Dr. A. Sri Krishna',                   Designation: 'Chairman' },
          { 'S.No': 2, Name: 'Dr. G. Jaya Suma',                     Designation: 'University Nominee' },
          { 'S.No': 3, Name: 'Dr. P. Radha Krishna',                  Designation: 'Subject Expert' },
          { 'S.No': 4, Name: 'Dr. K. Venkata Ramana',                Designation: 'Subject Expert' },
          { 'S.No': 5, Name: 'Mr. Snehith Allamraju',                Designation: 'Industry Expert' },
          { 'S.No': 6, Name: 'Mrs. Nimmala Srihitha Guna Priya',     Designation: 'Alumnus' },
          { 'S.No': 7, Name: 'Faculty Members of CSE [AI&DS], SVECW', Designation: 'Members' },
        ],
      },
      {
        title: 'CSE [Artificial Intelligence & Machine Learning]',
        rows: [
          { 'S.No': 1, Name: 'Dr. A. Sri Krishna',                   Designation: 'Chairman' },
          { 'S.No': 2, Name: 'Dr. G. Jaya Suma',                     Designation: 'University Nominee' },
          { 'S.No': 3, Name: 'Dr. P. Radha Krishna',                  Designation: 'Subject Expert' },
          { 'S.No': 4, Name: 'Dr. V. Valli Kumari',                   Designation: 'Subject Expert' },
          { 'S.No': 5, Name: 'Mr. G. Prasanna Murthy',               Designation: 'Industry Expert' },
          { 'S.No': 6, Name: 'Miss. G. Durga Bhargavi',              Designation: 'Alumnus' },
          { 'S.No': 7, Name: 'Faculty Members of CSE [AI&ML], SVECW', Designation: 'Members' },
        ],
      },
      {
        title: 'Information Technology',
        rows: [
          { 'S.No': 1, Name: 'Dr. D.V. Naga Raju',                   Designation: 'Chairman' },
          { 'S.No': 2, Name: 'Dr. M.V. Panduranga Rao',              Designation: 'Dept. of CSE, IIT Hyderabad' },
          { 'S.No': 3, Name: 'Dr. P. Radha Krishna',                  Designation: 'Subject Expert' },
          { 'S.No': 4, Name: 'Dr. MHM Krishna Prasad',               Designation: 'University Nominee' },
          { 'S.No': 5, Name: 'Mr. Pankaj Diwan',                     Designation: 'Industry Expert' },
          { 'S.No': 6, Name: 'Mrs. G. Bindu Madhavi',                Designation: 'Alumnus' },
          { 'S.No': 7, Name: 'Faculty Members of IT, SVECW',         Designation: 'Members' },
        ],
      },
      {
        title: 'Electronics & Communication Engineering',
        rows: [
          { 'S.No': 1,  Name: 'Dr. K. Padma Vasavi',                 Designation: 'Chairman' },
          { 'S.No': 2,  Name: 'Dr. U. Ratna Kumari',                 Designation: 'University Nominee' },
          { 'S.No': 3,  Name: 'Dr. N.V.S.N. Sarma',                  Designation: 'Academic Expert' },
          { 'S.No': 4,  Name: 'Dr. Sudeb Das Gupta',                  Designation: 'Academic Expert' },
          { 'S.No': 5,  Name: 'Dr. V. Anil Kumar',                    Designation: 'Academic Expert' },
          { 'S.No': 6,  Name: 'Dr. R. Nakkeran',                      Designation: 'Academic Expert' },
          { 'S.No': 7,  Name: 'Dr. Y. Avinash',                       Designation: 'Industry Expert' },
          { 'S.No': 8,  Name: 'Ms. T. Silpa',                         Designation: 'Industry Expert' },
          { 'S.No': 9,  Name: 'Mrs. Padma Neela Nallani',            Designation: 'UG Alumnus' },
          { 'S.No': 10, Name: 'Mrs. B. Sujitha',                      Designation: 'PG Alumnus' },
          { 'S.No': 11, Name: 'Faculty members of ECE, SVECW',       Designation: 'Members' },
        ],
      },
      {
        title: 'Electrical & Electronics Engineering',
        rows: [
          { 'S.No': 1, Name: 'Dr. S.M. Padmaja',                     Designation: 'Chairman BOS' },
          { 'S.No': 2, Name: 'Dr. N. Sumathi',                        Designation: 'University Nominee' },
          { 'S.No': 3, Name: 'Dr. Y. Pradeep Kumar',                  Designation: 'Academic Expert' },
          { 'S.No': 4, Name: 'Dr. G. Siva Kumar',                     Designation: 'Academic Expert' },
          { 'S.No': 5, Name: 'Mr. K.N.D. Anil Krishna',              Designation: 'Industry Expert' },
          { 'S.No': 6, Name: 'Ms. R. Sri Manvitha Reddy',            Designation: 'Alumnus' },
          { 'S.No': 7, Name: 'Faculty members of EEE, SVECW',        Designation: 'Members' },
        ],
      },
      {
        title: 'Civil Engineering',
        rows: [
          { 'S.No': 1, Name: 'Dr. Pala Gireesh Kumar',               Designation: 'BOS Chairman' },
          { 'S.No': 2, Name: 'Dr. M. Swaroopa Rani',                  Designation: 'University Nominee' },
          { 'S.No': 3, Name: 'Dr. D.S.R. Murthy',                    Designation: 'Subject Expert' },
          { 'S.No': 4, Name: 'Dr. D. Rama Seshu',                     Designation: 'Subject Expert' },
          { 'S.No': 5, Name: 'Er. K.B. Rathnakara Reddy',            Designation: 'Industry Expert' },
          { 'S.No': 6, Name: 'Ms. T. Nirmala Devi',                   Designation: 'Alumnus' },
          { 'S.No': 7, Name: 'Faculty Members of CE, SVECW',         Designation: 'Member' },
        ],
      },
      {
        title: 'Mechanical Engineering',
        rows: [
          { 'S.No': 1, Name: 'Dr. Ch. Hari Krishna',                  Designation: 'Chairman' },
          { 'S.No': 2, Name: 'Dr. V.V. Subba Rao',                    Designation: 'Subject Expert' },
          { 'S.No': 3, Name: 'Dr. P. Bangaru Babu',                   Designation: 'Subject Expert' },
          { 'S.No': 4, Name: 'Dr. B. Bala Krishna',                   Designation: 'Subject Expert' },
          { 'S.No': 5, Name: 'Mr. K.A. Rama Krishna Raju',           Designation: 'Industry Expert' },
          { 'S.No': 6, Name: 'MS S. Lakshmi Alekya',                  Designation: 'Alumnus' },
          { 'S.No': 7, Name: 'Mr. A. Surya Ganapathi',               Designation: 'Parent' },
          { 'S.No': 8, Name: 'Faculty Members of ME, SVECW',         Designation: 'Member' },
        ],
      },
      {
        title: 'First Year – Mathematics',
        rows: [
          { 'S.No': 1, Name: 'Dr. T.S.R. Murthy',                    Designation: 'Chairman-BoS' },
          { 'S.No': 2, Name: 'Prof. Sk. Kalesha Vali',               Designation: 'University Nominee' },
          { 'S.No': 3, Name: 'Prof. A. Chandrasekhar',               Designation: 'Subject Expert' },
          { 'S.No': 4, Name: 'Mr. V. Venkateswara Rao',              Designation: 'Industry Expert' },
          { 'S.No': 5, Name: 'Ms. B. Jyostna Sripriya',              Designation: 'Alumnus' },
          { 'S.No': 6, Name: 'Faculty Members of Mathematics, SVECW', Designation: 'Member' },
        ],
      },
      {
        title: 'First Year – Physics',
        rows: [
          { 'S.No': 1, Name: 'Dr. T.S.R. Murthy',                    Designation: 'Chairman-BoS' },
          { 'S.No': 2, Name: 'Dr. D. Haranath',                       Designation: 'University Nominee' },
          { 'S.No': 3, Name: 'Dr. R.V.S.S.N. Ravi Kumar',            Designation: 'Subject Expert' },
          { 'S.No': 4, Name: 'Mr. V. Venkateswara Rao',              Designation: 'Industry Expert' },
          { 'S.No': 5, Name: 'Ms. B. Jyostna Sripriya',              Designation: 'Alumnus' },
          { 'S.No': 6, Name: 'Faculty Members of Physics, SVECW',    Designation: 'Member' },
        ],
      },
      {
        title: 'First Year – Chemistry',
        rows: [
          { 'S.No': 1, Name: 'Dr. D. Ravi Kiran',                    Designation: 'Chairman-BoS' },
          { 'S.No': 2, Name: 'Dr. S. Satya Veni',                     Designation: 'University Nominee' },
          { 'S.No': 3, Name: 'Prof. N. Annapurna',                    Designation: 'Subject Expert' },
          { 'S.No': 4, Name: 'Mr. V. Venkateswara Rao',              Designation: 'Industry Expert' },
          { 'S.No': 5, Name: 'Faculty Members of Chemistry, SVECW',  Designation: 'Member' },
        ],
      },
      {
        title: 'First Year – English',
        rows: [
          { 'S.No': 1, Name: 'Dr. D. Ravi Kiran',                    Designation: 'Chairman-BoS' },
          { 'S.No': 2, Name: 'Dr. T. Ashok',                          Designation: 'University Nominee' },
          { 'S.No': 3, Name: 'Dr. P. Rajendra Karmarkar',            Designation: 'Subject Expert' },
          { 'S.No': 4, Name: 'Mr. V. Venkateswara Rao',              Designation: 'Industry Expert' },
          { 'S.No': 5, Name: 'Faculty Members of English, SVECW',    Designation: 'Members' },
        ],
      },
      {
        title: 'Master of Business Administration (MBA)',
        rows: [
          { 'S.No': 1, Name: 'Dr. G. Subbaraju',                     Designation: 'Chairman BOS' },
          { 'S.No': 2, Name: 'Dr. P. Vijaya Kumar',                   Designation: 'University Nominee' },
          { 'S.No': 3, Name: 'Dr. V. Sri Hari',                       Designation: 'Member Nominated by Council' },
          { 'S.No': 4, Name: 'Dr. I. Bangararaju',                    Designation: 'Member Nominated by Council' },
          { 'S.No': 5, Name: 'Mr. N. Ratnam Chowdhary',              Designation: 'Industry Expert' },
          { 'S.No': 6, Name: 'Mrs. K.A. Gowthami',                   Designation: 'Alumnus' },
          { 'S.No': 7, Name: 'Faculty Members of MBA, SVECW',        Designation: 'Member' },
        ],
      },
    ],
  },

  {
    slug: 'finance-committee',
    title: 'Finance Committee',
    category: 'governance',
    icon: '💰',
    desc: 'The statutory financial oversight committee of VWU responsible for budget preparation, financial planning, and expenditure approval.',
    intro: 'The Finance Committee of Vishnu Womens University is a statutory body responsible for examining the annual budget, advising on financial matters, and ensuring prudent financial management of institutional resources.',
    about: 'The Finance Committee ensures that the financial elements of the institution are in accord with its vision, mission, values, and strategic planning. It develops and oversees both annual and long-range budgets, reviews capital expenditure proposals, monitors revenues and expenditures, and prepares for statutory audits. The Committee is chaired by the Principal and includes the Vice-Principal, senior faculty, the Administrative Officer, and the Finance Manager.',
    highlights: [
      'Ensures finances align with institutional vision, mission, and strategic planning',
      'Develops and oversees annual and long-range budgets',
      'Reviews and approves capital expenditure proposals',
      'Manages asset maintenance and inventory across facilities',
      'Monitors revenue, expenditure, and balance sheet',
      'Identifies and reports irregular or unethical financial dealings',
      'Meetings held: 17.02.2025, 16.12.2024, 19.02.2024, 05.12.2023, 22.02.2023',
    ],
    outcomes: [
      'Consistent unqualified audit reports year-on-year',
      'Timely disbursement of SC/ST/BC government scholarships',
      'Approved infrastructure investments across campus development',
      'Transparent banking procedures and record-keeping compliance maintained',
    ],
    tableData: [
      { 'S.No': 1, Name: 'Dr. G. Srinivasa Rao, Principal',           Designation: 'Chairman' },
      { 'S.No': 2, Name: 'Prof. P. Venkata Rama Raju, Vice Principal', Designation: 'Member' },
      { 'S.No': 3, Name: 'Dr. V. Purushothama Raju, Professor, CSE',  Designation: 'Member' },
      { 'S.No': 4, Name: 'Dr. V.V.R. Maheswara Rao, IQAC Coordinator', Designation: 'Member' },
      { 'S.No': 5, Name: 'Mr. Md. Siddiq, A.O.',                      Designation: 'Member' },
      { 'S.No': 6, Name: 'Mr. S.S.S. Varma, Finance Manager',         Designation: 'Coordinator' },
    ],
  },

  {
    slug: 'idp',
    title: 'Institutional Development Plan',
    category: 'governance',
    icon: '📈',
    desc: 'VWU\'s strategic roadmap (IDP 2025–2035) outlining 8 strategic enablers for academic excellence, research, global outreach, and community impact.',
    intro: "VWU's Institutional Development Plan (IDP) 2025–2035 is a comprehensive strategic document that charts the university's growth across 8 strategic enablers, with short (0–2 yr), medium (2–5 yr), and long-term (5–10 yr) goals and action plans.",
    about: "The IDP was developed through a SWOC analysis and covers VWU's institutional profile: 29 student clubs, Radio Vishnu community radio, 9 UG + 5 PG programmes, and 1,074 student intake. The plan is aligned with the National Education Policy 2020, AICTE guidelines, and NAAC/NBA accreditation criteria. It is reviewed annually by the IQAC and presented to the Governing Body.",
    highlights: [
      '8 Strategic Enablers with short/medium/long-term goals',
      'Based on SWOC Analysis: 10 Strengths, 8 Weaknesses, 9 Opportunities, 3 Challenges',
      'Vision: Transform society through excellence in Education, Community empowerment, and Environmental protection',
      'Covers 9 UG + 5 PG programmes with 1,074 intake capacity',
      'Aligned with NEP 2020, AICTE, NAAC, and NBA requirements',
      'Reviewed annually by IQAC and Governing Body',
    ],
    outcomes: [
      'Enabler 1: Academic Excellence — curriculum innovation, OBE, industry-integrated learning',
      'Enabler 2: Research & Innovation — funded projects, publications, patents, incubation centre',
      'Enabler 3: Faculty Development — awards, FDPs, higher qualifications, research grants',
      'Enabler 4: Placements & Higher Education — metropolitan liaison, CRT, GSAC study-abroad',
      'Enabler 5: Infrastructure & Technology — smart classrooms, green campus, digital library',
      'Enabler 6: Student Development — 29 clubs, NSS, sports, cultural events, mentoring',
      'Enabler 7: International & Global Outreach — MoUs, student exchanges, global certifications',
      'Enabler 8: Community Engagement — Radio Vishnu, extension activities, social impact programmes',
    ],
  },

  // ─── COMMITTEES ────────────────────────────────────────────────────────────
  {
    slug: 'college-academic-committee',
    title: 'College Academic Committee',
    category: 'committees',
    icon: '🏫',
    desc: 'The primary academic monitoring committee of VWU, overseeing academic standards, teaching quality, and student performance across all departments.',
    intro: 'The College Academic Committee (CAC) coordinates all academic, administrative, research, and placement activities across departments. Chaired by the Principal, it includes all Heads of Departments, Deans, the Librarian, Physical Director, and Controller of Examinations.',
    about: 'The Committee conducts regular meetings on academic matters, establishes teaching schedules, forms administrative sub-committees, and facilitates academic planning. It promotes industrial engagement, student counselling, extracurricular initiatives, and research endeavours while maintaining alumni connections and overseeing faculty performance evaluations.',
    highlights: [
      'Chaired by the Principal; includes all Heads of Departments',
      'Conducts regular meetings on academic matters and planning',
      'Establishes teaching schedules and administrative sub-committees',
      'Promotes industrial engagement and research activities',
      'Facilitates student counselling and placement activities',
      'Oversees extracurricular initiatives and alumni relations',
    ],
    tableData: [
      { 'S.No': 1,  Name: 'Dr. G. Srinivasa Rao',            Position: 'Principal (Chairman)' },
      { 'S.No': 2,  Name: 'Prof. P. Venkata Rama Raju',       Position: 'Vice-Principal' },
      { 'S.No': 3,  Name: 'Dr. G.R.L.V.N. Srinivasa Raju',   Position: 'Dean R&D' },
      { 'S.No': 4,  Name: 'Dr. V. Purushothama Raju',         Position: 'Dean Academics' },
      { 'S.No': 5,  Name: 'Dr. V.V.R. Maheswara Rao',         Position: 'Dean Statutory Bodies' },
      { 'S.No': 6,  Name: 'Dr. S.M. Padmaja',                 Position: 'HOD – EEE' },
      { 'S.No': 7,  Name: 'Dr. K. Padma Vasavi',              Position: 'HOD – ECE' },
      { 'S.No': 8,  Name: 'Dr. P. Kiran Sree',                Position: 'HOD – CSE' },
      { 'S.No': 9,  Name: 'Dr. D.V. Naga Raju',               Position: 'HOD – IT' },
      { 'S.No': 10, Name: 'Dr. P. Girish Kumar',              Position: 'HOD – Civil Engineering' },
      { 'S.No': 11, Name: 'Dr. Ch. Hari Krishna',             Position: 'HOD – ME' },
      { 'S.No': 12, Name: 'Dr. A. Sri Krishna',               Position: 'HOD – AI & DS' },
      { 'S.No': 13, Name: 'Dr. T.S.R. Murthy',                Position: 'HOD – Mathematics' },
      { 'S.No': 14, Name: 'Dr. J.V. Srinivas',                Position: 'HOD – Physics' },
      { 'S.No': 15, Name: 'Dr. K. Jagadeesh',                 Position: 'HOD – Chemistry' },
      { 'S.No': 16, Name: 'Dr. P. Srihari Raju',              Position: 'HOD – English' },
      { 'S.No': 17, Name: 'Dr. K.V. Rama Murthy',             Position: 'HOD – MBA' },
      { 'S.No': 18, Name: 'Dr. A. Kaladhar',                  Position: 'Librarian' },
      { 'S.No': 19, Name: 'Dr. G. Suneetha',                  Position: 'Physical Director' },
      { 'S.No': 20, Name: 'Dr. K.S.N. Raju',                  Position: 'Controller of Examinations' },
    ],
  },

  {
    slug: 'internal-quality-assurance-cell',
    title: 'Internal Quality Assurance Cell',
    category: 'committees',
    icon: '✅',
    desc: 'The IQAC coordinates quality assurance activities across the institution, maintains records for NAAC accreditation, and drives continuous improvement initiatives.',
    intro: "VWU's Internal Quality Assurance Cell (IQAC) was established as per UGC and NAAC guidelines to develop and apply mechanisms that ensure quality and relevance in all academic, administrative, and outreach activities.",
    about: "The IQAC prepares the Annual Quality Assurance Report (AQAR), coordinates quality benchmarking, collects stakeholder feedback, and disseminates information on higher education standards. The Cell is chaired by the Principal and includes management representatives, Deans, administrative staff, industry, parents, alumni, and student representatives.",
    highlights: [
      'Develops and applies quality benchmarks for all academic and administrative activities',
      'Establishes learner-centred environments supporting educational quality',
      'Collects and analyses stakeholder feedback on institutional quality',
      'Organises workshops addressing quality improvement themes',
      'Prepares Annual Quality Assurance Report (AQAR) per NAAC guidelines',
      'Maintains institutional databases through management information systems',
    ],
    tableData: [
      { 'S.No': 1,  Name: 'Dr. G. Srinivasa Rao',            Designation: 'Principal',                    Position: 'Chairman' },
      { 'S.No': 2,  Name: 'Sri. J.V.S.S. Prasad Raju',       Designation: 'Director-Admin, SVES',         Position: 'Member' },
      { 'S.No': 3,  Name: 'Prof. P. Venkata Rama Raju',       Designation: 'Vice Principal',               Position: 'Member' },
      { 'S.No': 4,  Name: 'Dr. G.R.L.V.N.S. Raju',           Designation: 'Dean R&D',                     Position: 'Member' },
      { 'S.No': 5,  Name: 'Dr. V. Purushothama Raju',         Designation: 'Dean Academics',               Position: 'Member' },
      { 'S.No': 6,  Name: 'Mr. Md. Siddiq',                   Designation: 'Administrative Officer',       Position: 'Member' },
      { 'S.No': 7,  Name: 'Mr. S.S.S. Varma',                 Designation: 'Finance Manager, SVES',        Position: 'Member' },
      { 'S.No': 8,  Name: 'Faculty Members (9)',              Designation: 'Professors & Asst. Professors', Position: 'Members' },
      { 'S.No': 18, Name: 'Sri. G.V.M. Raju',                 Designation: 'Village President, Kovvada',   Position: 'Member (Local Society)' },
      { 'S.No': 19, Name: 'Mr. A.S. Narayana Varma',          Designation: 'DGM Productions',              Position: 'Member (Employer)' },
      { 'S.No': 20, Name: 'Mr. M.S. Vara Prasad',             Designation: 'Parent',                       Position: 'Member' },
      { 'S.No': 21, Name: 'Ms. V. Vaishalini',                Designation: 'Software Engineer, VISA',      Position: 'Member (Alumni)' },
      { 'S.No': 22, Name: 'Student Representatives (3)',      Designation: 'B.Tech., M.Tech., M.B.A.',     Position: 'Members' },
      { 'S.No': 25, Name: 'Dr. V.V.R. Maheswara Rao',         Designation: 'Dean Statutory Bodies',        Position: 'Coordinator' },
    ],
  },

  {
    slug: 'academic-administrative-audit',
    title: 'Academic and Administrative Audit Committee',
    category: 'committees',
    icon: '🔍',
    desc: 'Conducts periodic audits of academic and administrative processes to identify gaps, ensure compliance, and recommend improvements.',
    intro: 'The Academic and Administrative Audit Committee (AAAC) of VWU conducts systematic evaluations of teaching records, research output, course outcomes, and student accomplishments to identify strengths and gaps across all departments.',
    about: "Following departmental submissions, the Committee reviews institutional records, identifies strengths and deficiencies, and prepares a consolidated report for leadership review. Departments subsequently submit compliance reports addressing identified gaps. The Committee is chaired by the Dean of Academics and includes faculty representatives from every department.",
    highlights: [
      'Chaired by the Dean of Academics',
      'Audits teaching records and course documentation',
      'Reviews faculty research output and publications',
      'Assesses course outcome achievement and result analysis',
      'Evaluates documented student accomplishments',
      'Departments submit compliance reports after each audit cycle',
    ],
    tableData: [
      { 'S.No': 1,  Name: 'Dr. V. Purushothama Raju',  Designation: 'Dean – Academics (Chairman)' },
      { 'S.No': 2,  Name: 'Dr. T. Sudheer Kumar',       Designation: 'ECE Dept.' },
      { 'S.No': 3,  Name: 'Dr. S. Dileep Kumar Varma',  Designation: 'EEE Dept.' },
      { 'S.No': 4,  Name: 'Dr. Ratikanta Sahoo',         Designation: 'ECE Dept.' },
      { 'S.No': 5,  Name: 'Dr. T. Gayathri',             Designation: 'CSE Dept.' },
      { 'S.No': 6,  Name: 'Dr. S. Ravi Kumar',           Designation: 'IT Dept.' },
      { 'S.No': 7,  Name: 'Mrs. T. Madhavi',             Designation: 'AI Dept.' },
      { 'S.No': 8,  Name: 'Mr. U.D.S. Pratap Varma',    Designation: 'ME Dept.' },
      { 'S.No': 9,  Name: 'Mr. B. Venkatesh',            Designation: 'CE Dept.' },
      { 'S.No': 10, Name: 'Mr. D.B.N. Suresh Varma',    Designation: 'Chemistry Dept.' },
      { 'S.No': 11, Name: 'Dr. R. Vasu Babu',            Designation: 'Mathematics Dept.' },
      { 'S.No': 12, Name: 'Mrs. P. Prasanthi',           Designation: 'English Dept.' },
      { 'S.No': 13, Name: 'Mr. J.V. Krishna Kumar',      Designation: 'Member' },
      { 'S.No': 14, Name: 'Mr. Ch. Anudeep',             Designation: 'Member' },
    ],
  },

  {
    slug: 'freshmen-committee',
    title: 'Freshmen Committee',
    category: 'committees',
    icon: '🌱',
    desc: 'Dedicated committee ensuring a smooth, supportive transition for first-year students into university life through orientation, counselling, and monitoring.',
    intro: "VWU's Freshmen Committee is constituted to facilitate the successful academic and social integration of first-year (I B.Tech) students, focusing on confidence building, relationship awareness, social consciousness, and skill development.",
    about: "The Committee is chaired by the Principal and has a dedicated Senior Assistant Professor in-charge for I B.Tech students. It coordinates orientation programmes, assigns faculty mentors, and conducts monitoring reviews. It works closely with the Counselling & Monitoring Committee for students who need additional guidance.",
    highlights: [
      'Confidence Building: developing self-assurance in newly enrolled students',
      'Relationship Awareness: educating on appropriate senior-junior dynamics',
      'Social Consciousness: fostering awareness of contemporary societal issues',
      'Skill Development: supporting academic, professional, and personal growth',
      'Dedicated Senior Assistant Professor in-charge for I B.Tech students',
      'Coordinates with Counselling & Monitoring Committee for at-risk students',
    ],
    tableData: [
      { 'S.No': 1, Name: 'Dr. G. Srinivasa Rao',        Position: 'Principal – Chairperson' },
      { 'S.No': 2, Name: 'Prof. P. Venkata Rama Raju',   Position: 'Vice-Principal' },
      { 'S.No': 3, Name: 'Dr. P. Purushothama Raju',     Position: 'Dean Academics' },
      { 'S.No': 4, Name: 'Dr. K. Jagadeesh',             Position: 'HOD – Chemistry' },
      { 'S.No': 5, Name: 'Mr. J.V. Krishna Kumar',       Position: 'Sr. Asst. Professor, In-charge I B.Tech (Coordinator)' },
      { 'S.No': 6, Name: 'Dr. G.J.V. Prasad',            Position: 'Asst. Professor – Member' },
      { 'S.No': 7, Name: 'Dr. P.L.R. Kameswari',         Position: 'Asst. Professor – Member' },
    ],
  },

  {
    slug: 'infrastructure-management',
    title: 'Infrastructure Management Committee',
    category: 'committees',
    icon: '🏗️',
    desc: 'Oversees the planning, development, maintenance, and optimal utilisation of all physical infrastructure and facilities at VWU.',
    intro: "VWU's Infrastructure Management Committee is responsible for identifying, developing, maintaining, and reviewing all infrastructure facilities and services — including laboratories, ICT tools, Centres of Excellence, furniture, and environmental hygiene.",
    about: "The Committee includes the Principal as Chairman, all Deans, all Heads of Departments, the Librarian, Physical Director, Controller of Examinations, Purchase Officer, and Administrative Officer. It ensures all infrastructure requirements are assessed, prioritised, and addressed in a timely manner with proper coordination.",
    highlights: [
      'Oversees planning and development of new built-up areas and laboratories',
      'Reviews and maintains ICT teaching tools and digital infrastructure',
      'Assesses requirements for Centres of Excellence',
      'Manages furniture procurement and maintenance',
      'Oversees lab maintenance, electrical work, and building hygiene',
      'Coordinates Purchase Officer and Administrative Officer for procurements',
    ],
    tableData: [
      { 'S.No': 1,  Name: 'Dr. G. Srinivasa Rao',            Designation: 'Chairman (Principal)' },
      { 'S.No': 2,  Name: 'Prof. P. Venkata Rama Raju',       Designation: 'Vice-Principal' },
      { 'S.No': 3,  Name: 'Dr. G.R.L.V.N. Srinivasa Raju',   Designation: 'Dean R&D' },
      { 'S.No': 4,  Name: 'Dr. V. Purushothama Raju',         Designation: 'Dean Academics' },
      { 'S.No': 5,  Name: 'Dr. V.V.R. Maheswara Rao',         Designation: 'Dean Statutory Bodies' },
      { 'S.No': 6,  Name: 'Dr. P. Kiran Sree',                Designation: 'HOD – CSE' },
      { 'S.No': 7,  Name: 'Dr. K. Padma Vasavi',              Designation: 'HOD – ECE' },
      { 'S.No': 8,  Name: 'Dr. S.M. Padmaja',                 Designation: 'HOD – EEE' },
      { 'S.No': 9,  Name: 'Dr. D.V. Naga Raju',               Designation: 'HOD – IT' },
      { 'S.No': 10, Name: 'Dr. P. Girish Kumar',              Designation: 'HOD – Civil Engineering' },
      { 'S.No': 11, Name: 'Dr. Ch. Hari Krishna',             Designation: 'HOD – ME' },
      { 'S.No': 12, Name: 'Dr. A. Sri Krishna',               Designation: 'HOD – AI' },
      { 'S.No': 13, Name: 'Dr. T.S.R. Murthy',                Designation: 'HOD – Mathematics' },
      { 'S.No': 14, Name: 'Dr. J.V. Srinivas',                Designation: 'HOD – Physics' },
      { 'S.No': 15, Name: 'Dr. K. Jagadeesh',                 Designation: 'HOD – Chemistry' },
      { 'S.No': 16, Name: 'Dr. P. Srihari Raju',              Designation: 'HOD – English' },
      { 'S.No': 17, Name: 'Dr. K.V. Rama Murthy',             Designation: 'HOD – MBA' },
      { 'S.No': 18, Name: 'Dr. A. Kaladhar',                  Designation: 'Librarian' },
      { 'S.No': 19, Name: 'Dr. G. Suneetha',                  Designation: 'Physical Director' },
      { 'S.No': 20, Name: 'Dr. K.S.N. Raju',                  Designation: 'Controller of Examinations' },
      { 'S.No': 21, Name: 'Mr. P. Vijay Babu',                Designation: 'Purchase Officer' },
      { 'S.No': 22, Name: 'Mr. Md. Siddiq',                   Designation: 'Administrative Officer' },
    ],
  },

  {
    slug: 'faculty-grievance',
    title: 'Faculty Grievance Redressal Committee',
    category: 'committees',
    icon: '🤝',
    desc: 'Provides a formal, confidential mechanism for faculty members to raise and resolve service-related grievances in a fair and time-bound manner.',
    intro: "VWU's Faculty Grievance Redressal Committee ensures that all faculty members have access to a transparent, confidential, and time-bound mechanism for raising service-related grievances, ensuring a healthy and supportive work environment.",
    about: "The Committee receives and examines grievances from faculty regarding academic, administrative, or service matters. It gathers evidence, allows all concerned parties to present their perspectives, and recommends solutions to institutional management within a reasonable time frame. All complaints and resolutions are fully documented.",
    highlights: [
      'Receives and examines grievances on academic, administrative, or service matters',
      'Ensures a fair, transparent, and confidential investigation process',
      'Gathers evidence and allows all concerned parties to be heard',
      'Recommends solutions to institutional management',
      'Resolves grievances within a reasonable time frame',
      'Maintains full documentation of all complaints and resolutions',
    ],
    tableData: [
      { 'S.No': 1, Name: 'Dr. G. Srinivasa Rao',          Position: 'Principal',               Role: 'Chairperson' },
      { 'S.No': 2, Name: 'Prof. P. Venkata Rama Raju',     Position: 'Vice-Principal',          Role: 'Member' },
      { 'S.No': 3, Name: 'Dr. V.V.R. Maheswara Rao',       Position: 'IQAC Coordinator',        Role: 'Member' },
      { 'S.No': 4, Name: 'Dr. K.S.N. Raju',                Position: 'Associate Professor, CoE', Role: 'Member' },
      { 'S.No': 5, Name: 'Dr. N. Silpa',                   Position: 'Asst. Professor, CSE',    Role: 'Member' },
      { 'S.No': 6, Name: 'Mr. V. Rama Raju',               Position: 'Operator, Office',        Role: 'Member' },
      { 'S.No': 7, Name: 'Dr. K. Padma Vasavi',            Position: 'Professor, HOD – ECE',    Role: 'Member Secretary' },
    ],
  },

  {
    slug: 'student-grievance',
    title: 'Student Grievance Redressal Committee',
    category: 'committees',
    icon: '📣',
    desc: 'Ensures every student has access to a fair, time-bound grievance mechanism for academic, administrative, and campus life concerns.',
    intro: "VWU's Student Grievance Redressal Committee (SGRC) is constituted as per UGC regulations to provide students with a fair, transparent, and timely mechanism to address academic and non-academic grievances.",
    about: "The Committee receives grievances related to academic, administrative, or campus issues. It investigates by gathering information and consulting all involved parties, provides students opportunity to present concerns impartially, and recommends corrective measures. Student representatives are included to ensure a student-friendly process.",
    highlights: [
      'Receives grievances on academic, administrative, and campus-related issues',
      'Ensures a fair, transparent, and timely resolution process',
      'Investigates by gathering information and consulting all parties',
      'Provides students the opportunity to present concerns impartially',
      'Recommends corrective measures to appropriate authorities',
      'Raises awareness among students about available grievance mechanisms',
    ],
    tableData: [
      { Position: 'Principal (Chairman)',    Member: 'Dr. G. Srinivasa Rao' },
      { Position: 'Vice Principal',          Member: 'Prof. P. Venkata Rama Raju' },
      { Position: 'Senior Faculty Member',   Member: 'Dr. S.M. Padmaja' },
      { Position: 'Senior Faculty Member',   Member: 'Dr. K. Ganesh Kadiyala' },
      { Position: 'Senior Faculty Member',   Member: 'Dr. N. Silpa' },
      { Position: 'Student Coordinator',     Member: 'Student Representative – 1' },
      { Position: 'Student Coordinator',     Member: 'Student Representative – 2' },
    ],
  },

  {
    slug: 'central-purchase',
    title: 'Central Purchase Committee',
    category: 'committees',
    icon: '🛒',
    desc: 'Ensures transparent, competitive, and value-for-money procurement of equipment, materials, and services across all departments.',
    intro: "VWU's Central Purchase Committee is responsible for the transparent and efficient procurement of academic equipment, laboratory instruments, consumables, software licences, and other institutional supplies.",
    about: 'The Committee follows a structured procurement process including requirement assessment, vendor empanelment, competitive quotation/tender, technical evaluation, and financial approval. It ensures all purchases align with the approved budget, deliver value for money, and meet quality specifications. The Committee maintains vendor records and manages warranty and AMC obligations for critical equipment.',
    highlights: [
      'Structured procurement process with competitive quotations',
      'Transparent vendor empanelment and evaluation criteria',
      'All purchases aligned with the approved annual budget',
      'Maintains records of warranties and AMC contracts',
      'Compliant with government procurement guidelines',
      'Coordinates with departmental technical teams for specifications',
    ],
  },

  {
    slug: 'counselling-monitoring',
    title: 'Counselling & Monitoring Committee',
    category: 'committees',
    icon: '💬',
    desc: 'Provides academic and personal counselling support to students, with regular monitoring to ensure holistic student well-being and academic progress.',
    intro: "VWU's Counselling & Monitoring Committee tracks attendance, mid-term performance, and pending coursework for assigned students, providing regular guidance and submitting weekly counselling reports to ensure timely intervention.",
    about: "Faculty counsellors are assigned to students across all departments. They maintain organised records, prepare semester-end evaluations, address irregular attendance, and report academic concerns to department heads. Department coordinators compile weekly reports for submission to the college counselling lead, coordinated by the Dean of Academics.",
    highlights: [
      'Tracks student attendance, mid-term performance, and pending coursework',
      'Maintains organised records using prescribed formats',
      'Submits weekly counselling reports through department coordinators',
      'Prepares semester-end evaluations for each assigned student',
      'Addresses irregular attendance through targeted counselling sessions',
      'Reports academic concerns to department heads for timely intervention',
    ],
    tableData: [
      { 'S.No': 1,  Name: 'Dr. G. Srinivasa Rao',      Department: 'Administration', Role: 'Chairman' },
      { 'S.No': 2,  Name: 'Mrs. K. Ratna Kumari',       Department: 'CSE',            Role: 'Member' },
      { 'S.No': 3,  Name: 'Mr. K. Omkar',               Department: 'EEE',            Role: 'Member' },
      { 'S.No': 4,  Name: 'Mr. K. Murthy Raju',         Department: 'ECE',            Role: 'Member' },
      { 'S.No': 5,  Name: 'Mrs. M. Manasa',             Department: 'CE',             Role: 'Member' },
      { 'S.No': 6,  Name: 'Mrs. T. Suma Bharathi',      Department: 'IT',             Role: 'Member' },
      { 'S.No': 7,  Name: 'Mr. N. Srinivasa Rao',       Department: 'ME',             Role: 'Member' },
      { 'S.No': 8,  Name: 'Dr. A. Sri Krishna',         Department: 'AI',             Role: 'Member' },
      { 'S.No': 9,  Name: 'Mr. A. Khan',                Department: 'English',        Role: 'Member' },
      { 'S.No': 10, Name: 'Mr. Ch. Anudeep',            Department: 'MBA',            Role: 'Member' },
      { 'S.No': 11, Name: 'Dr. V. Purushothama Raju',   Department: 'Academics',      Role: 'Coordinator' },
    ],
  },

  {
    slug: 'anti-ragging',
    title: 'Anti Ragging Committee',
    category: 'committees',
    icon: '🛡️',
    desc: 'Ensures a ragging-free campus environment through awareness, prevention, monitoring, and strict enforcement as per UGC Anti-Ragging Regulations.',
    intro: "VWU maintains a zero-tolerance policy against ragging. The Anti Ragging Committee is constituted as per UGC Anti-Ragging Regulations 2009 and is responsible for prevention, monitoring, and redressal of any ragging-related incidents on campus.",
    about: "The Committee conducts awareness programmes for students and parents at the start of each academic year. Vigilance squads conduct surprise inspections during initial months, and staggered class schedules keep freshers separated from seniors for two months. All students submit anti-ragging undertakings and are oriented about anti-ragging laws during induction.",
    highlights: [
      'Zero-tolerance anti-ragging policy across all campus areas',
      'Vigilance squad with surprise inspections during initial months',
      'Anti-ragging informational notices displayed institution-wide',
      'All students submit undertakings acknowledging anti-ragging laws',
      'Orientation sessions for freshers and parents at start of each year',
      'Staggered schedules separating first-year and senior students for two months',
    ],
    tableData: [
      { 'S.No': 1,  Name: 'Dr. G. Srinivasa Rao',         Position: 'Principal',            Role: 'Chair' },
      { 'S.No': 2,  Name: 'Prof. P. Venkata Rama Raju',    Position: 'Vice-Principal',       Role: 'Member' },
      { 'S.No': 3,  Name: 'Dr. S.M. Padmaja',              Position: 'HOD – EEE',            Role: 'Member' },
      { 'S.No': 4,  Name: 'Dr. K. Padma Vasavi',           Position: 'HOD – ECE',            Role: 'Member' },
      { 'S.No': 5,  Name: 'Dr. P. Kiran Sree',             Position: 'HOD – CSE',            Role: 'Member' },
      { 'S.No': 6,  Name: 'Dr. D.V. Naga Raju',            Position: 'HOD – IT',             Role: 'Member' },
      { 'S.No': 7,  Name: 'Dr. P. Girish Kumar',           Position: 'HOD – CE',             Role: 'Member' },
      { 'S.No': 8,  Name: 'Dr. Ch. Hari Krishna',          Position: 'HOD – ME',             Role: 'Member' },
      { 'S.No': 9,  Name: 'Dr. A. Sri Krishna',            Position: 'HOD – AI & DS',        Role: 'Member' },
      { 'S.No': 10, Name: 'Dr. J.V. Srinivas',             Position: 'HOD – Physics',        Role: 'Member' },
      { 'S.No': 11, Name: 'Dr. K. Jagadeesh',              Position: 'HOD – Chemistry',      Role: 'Member' },
      { 'S.No': 12, Name: 'Dr. P. Srihari Raju',           Position: 'HOD – English',        Role: 'Member' },
      { 'S.No': 13, Name: 'Dr. K.V. Rama Murthy',          Position: 'HOD – MBA',            Role: 'Member' },
      { 'S.No': 14, Name: 'Dr. G. Sunitha',                Position: 'Physical Director',    Role: 'Member' },
      { 'S.No': 15, Name: 'Dr. A. Kaladhar',               Position: 'Librarian',            Role: 'Member' },
      { 'S.No': 16, Name: 'All CRs of II Year Students',   Position: 'Student Representatives', Role: 'Members' },
      { 'S.No': 17, Name: 'Dr. T.S.R. Murthy',             Position: 'Professor, Mathematics', Role: 'Coordinator' },
      { 'S.No': 18, Name: 'Mrs. P. Prasanthi',             Position: 'Asst. Prof., English', Role: 'Coordinator' },
    ],
  },

  {
    slug: 'internal-committee',
    title: 'Internal Committee',
    category: 'committees',
    icon: '⚖️',
    desc: 'Statutory committee under the POSH Act ensuring a safe and dignified campus environment for all women students, faculty, and staff.',
    intro: "VWU's Internal Committee (IC) is constituted as per the Sexual Harassment of Women at Workplace (Prevention, Prohibition and Redressal) Act, 2013. It ensures a safe, respectful, and dignified environment for all on campus.",
    about: "The Committee is presided by a senior woman faculty member (Dr. S.M. Padmaja) and includes internal faculty, exam cell staff, an on-campus psychologist, an external senior advocate, and an NGO director. It supports complaints filed with police, conducts gender sensitisation workshops, offers counselling services, and ensures adequate campus infrastructure with proper lighting, security, and transport.",
    highlights: [
      'Constituted under the POSH Act, 2013',
      'Presided by Dr. S.M. Padmaja, senior woman faculty member',
      'Includes external advocate and NGO director as required by statute',
      'Supports complaints filed with police and legal processes',
      'Conducts gender sensitisation and sexual harassment awareness workshops',
      'Provides counselling through on-campus psychologist (Ms. Devika Babu)',
    ],
    tableData: [
      { 'S.No': 1, Role: 'Presiding Officer', 'Name & Designation': 'Dr. S.M. Padmaja, Professor, EEE Dept.',      Type: 'Internal' },
      { 'S.No': 2, Role: 'Member',            'Name & Designation': 'Dr. N. Silpa, Asst. Professor, CSE Dept.',    Type: 'Internal' },
      { 'S.No': 3, Role: 'Member',            'Name & Designation': 'Mrs. A. Durga, Exam Cell',                     Type: 'Internal' },
      { 'S.No': 4, Role: 'Member',            'Name & Designation': 'Ms. Devika Babu, Psychologist',                Type: 'Internal' },
      { 'S.No': 5, Role: 'Member',            'Name & Designation': 'Mr. A. Venkateswara Raju, Senior Advocate',    Type: 'External' },
      { 'S.No': 6, Role: 'Member',            'Name & Designation': 'Ms. Ch. Aruna Devi, NGO Director',             Type: 'External' },
    ],
  },

  {
    slug: 'sc-st-cell',
    title: 'SC/ST Cell',
    category: 'committees',
    icon: '🤲',
    desc: 'Provides dedicated support, grievance redressal, and welfare facilitation for SC/ST students and staff in accordance with UGC guidelines.',
    intro: "VWU's SC/ST Cell is constituted as per UGC guidelines to elevate the academic performance of SC/ST students, address concerns of SC/ST members among students and staff, and facilitate access to government scholarships and welfare schemes.",
    about: "The Cell works to bring SC/ST students up to the general academic level, disseminates information about government scholarships and institutional resources, and provides a dedicated grievance mechanism. Student members are included to provide direct community voice. Meeting minutes have been maintained from July 2020.",
    highlights: [
      'Elevates academic performance of SC/ST students to the general level',
      'Addresses concerns affecting SC/ST students, faculty, and staff',
      'Disseminates information on government scholarships and welfare schemes',
      'Encourages utilisation of institutional resources for personal advancement',
      'Student representatives included for direct community representation',
      'Meetings documented: July 2020 through November 2023',
    ],
    tableData: [
      { 'S.No': 1, Name: 'Dr. V. Purushothama Raju',       Role: 'Chairperson' },
      { 'S.No': 2, Name: 'Dr. P. Ravi Kumar',               Role: 'Member' },
      { 'S.No': 3, Name: 'Dr. B. Ramu',                     Role: 'Member' },
      { 'S.No': 4, Name: 'Mrs. J. Swarna Jyothi',           Role: 'Member' },
      { 'S.No': 5, Name: 'Mrs. R. Lalitha Kumari',          Role: 'Member' },
      { 'S.No': 6, Name: 'Ms. B. Sujana (24B01A0107)',      Role: 'Student Member' },
      { 'S.No': 7, Name: 'Ms. K. Keerthana (23B01A1281)',   Role: 'Student Member' },
      { 'S.No': 8, Name: 'Ms. A. Anusha (22B01A0401)',      Role: 'Student Member' },
      { 'S.No': 9, Name: 'Dr. M. Prema Kumar',              Role: 'Coordinator' },
    ],
  },

  {
    slug: 'rd-committee',
    title: 'R&D Committee',
    category: 'committees',
    icon: '🔬',
    desc: 'Promotes and coordinates research and development activities across VWU, facilitating funded projects, publications, patents, and industry collaborations.',
    intro: "VWU's Research & Development Committee is chaired by the Principal and convened by the Dean R&D. It monitors funded projects, facilitates technical paper publications, coordinates consultancy work, oversees CII activities, and manages student project seed money.",
    about: "The Committee reviews and submits project proposals from the institute, monitors ongoing R&D and externally funded projects, mentors faculty for publication, explores consultancy opportunities, oversees professional body engagements, arranges industry expert visits and visiting faculty lectures, manages R&D budgets, and conducts IPR awareness programmes.",
    highlights: [
      'Monitors ongoing R&D and externally/internally funded projects',
      'Reviews and submits project proposals from the institute',
      'Mentors faculty for technical paper publication',
      'Explores and executes institute-level consultancy works',
      'Arranges industry expert visits and visiting faculty lectures',
      'Manages students\' project seed money and R&D budgets',
      'Conducts Intellectual Property Rights awareness programmes',
    ],
    tableData: [
      { 'S.No': 1, Name: 'Dr. G. Srinivasa Rao',            Designation: 'Chairman (Principal)' },
      { 'S.No': 2, Name: 'Prof. P. Venkata Rama Raju',       Designation: 'Vice Principal – Member' },
      { 'S.No': 3, Name: 'Dr. S.M. Padmaja',                 Designation: 'Professor, EEE Dept. – Member' },
      { 'S.No': 4, Name: 'Dr. T.S.R. Murthy',                Designation: 'Professor, BS Dept. – Member' },
      { 'S.No': 5, Name: 'Dr. G.R.L.V.N. Srinivasa Raju',   Designation: 'Dean R&D – Convener' },
    ],
  },

  // ─── IQAC ──────────────────────────────────────────────────────────────────
  {
    slug: 'about-iqac',
    title: 'About IQAC',
    category: 'iqac',
    icon: '🏅',
    desc: 'VWU\'s Internal Quality Assurance Cell — established to institutionalise a culture of quality in all academic and administrative activities and maintain NAAC accreditation standards.',
    intro: "VWU's Internal Quality Assurance Cell (IQAC) was established in compliance with NAAC guidelines to develop and apply mechanisms to ensure quality and relevance in all academic, administrative, and outreach activities of the institution.",
    about: "The IQAC functions as a nodal agency for quality-related activities at VWU. It promotes conscious and consistent improvement in the performance and functioning of the institution. The Cell is headed by the Principal as Chairperson, with a senior faculty member as Director/Coordinator, and includes Heads of Departments, administrative officers, and external stakeholders from industry and alumni. The IQAC prepares Annual Quality Assurance Reports (AQAR), coordinates NAAC activities, and drives continuous improvement across all NAAC criteria.",
    highlights: [
      'Established as per NAAC guidelines',
      'Chaired by the Principal; coordinated by senior faculty',
      'Includes HoDs, admin staff, industry, and alumni members',
      'Prepares Annual Quality Assurance Reports (AQAR)',
      'Coordinates all NAAC accreditation activities',
      'Drives continuous improvement in teaching, research, and governance',
    ],
  },

  {
    slug: 'iqac-worksystem',
    title: 'IQAC Worksystem',
    category: 'iqac',
    icon: '⚙️',
    desc: 'The structured workflow, processes, and responsibilities that govern how the IQAC plans, monitors, reports, and continuously improves institutional quality.',
    intro: "The IQAC Worksystem at VWU defines the systematic processes, responsibilities, and timelines through which the Cell plans quality activities, collects and analyses data, coordinates audits, and drives institutional improvement across all NAAC criteria.",
    about: "The worksystem operates on an annual cycle aligned with the academic year. At the start of each year, the IQAC prepares a Quality Improvement Plan (QIP) in consultation with all departments. Throughout the year, it collects data, monitors progress, conducts mid-year reviews, and coordinates internal academic audits. At year-end, the IQAC compiles the AQAR for submission to NAAC, conducts feedback analysis, and shares findings with the Governing Body. Best practices are documented and disseminated institution-wide.",
    highlights: [
      'Annual Quality Improvement Plan (QIP) prepared each year',
      'Continuous data collection and progress monitoring',
      'Mid-year and end-year review cycles',
      'Coordinates internal academic audits each semester',
      'Annual AQAR submitted to NAAC',
      'Best practices documented and shared across departments',
    ],
  },

  {
    slug: 'quality-parameters',
    title: 'Quality Parameters',
    category: 'iqac',
    icon: '📊',
    desc: 'The key quality benchmarks and performance indicators tracked by VWU\'s IQAC across NAAC\'s seven criteria for institutional excellence.',
    intro: "VWU's IQAC monitors institutional quality using a comprehensive set of parameters aligned with NAAC's seven criteria: Curricular Aspects, Teaching-Learning & Evaluation, Research & Outreach, Infrastructure, Student Support, Governance, and Institutional Values.",
    about: "Each parameter has defined targets and is reviewed quarterly. Key metrics include student-to-faculty ratio, pass rates, research publications per faculty, funded projects, placement rates, student satisfaction scores, and infrastructure utilisation. The IQAC uses a data-driven approach to identify underperforming areas and implement targeted improvements. All parameters are reported in the AQAR and benchmarked against peer institutions.",
    highlights: [
      'Aligned with NAAC seven criteria framework',
      'Quarterly review of all quality metrics',
      'Benchmarked against peer institutions nationally',
      'Tracks publications, funded projects, and placements',
      'Student satisfaction surveys conducted twice per year',
      'Data reported in AQAR and reviewed by Governing Body',
    ],
    outcomes: [
      'Criterion 1 (Curricular): 100% programmes with updated syllabi every 2 years',
      'Criterion 2 (Teaching-Learning): 90%+ results in university examinations',
      'Criterion 3 (Research): 200+ publications annually; 10+ funded projects active',
      'Criterion 4 (Infrastructure): 99% lab utilisation; 1 Gbps internet connectivity',
      'Criterion 5 (Student Support): 95%+ placement rate; 100+ scholarships disbursed',
      'Criterion 6 (Governance): All statutory committees functional; 2 Governing Body meetings/year',
    ],
  },

  {
    slug: 'iqac-committee',
    title: 'IQAC Committee',
    category: 'iqac',
    icon: '👥',
    desc: 'The composition and roles of the IQAC Committee members who drive quality assurance at VWU.',
    intro: "The IQAC Committee at VWU comprises senior faculty, administrative staff, external industry experts, and alumni representatives — collectively responsible for planning, coordinating, and reviewing quality assurance activities across the institution.",
    about: "The Committee is constituted as per NAAC guidelines and includes: the Principal as Chairperson, the IQAC Director/Coordinator (senior faculty), one senior administrative officer, at least three Heads of Departments on rotation, two external members from industry or notable alumni, and one student representative. The Committee meets quarterly and its decisions are binding on all academic and administrative units for quality-related matters.",
    highlights: [
      'Constituted as per NAAC guidelines',
      'Principal serves as Chairperson',
      'Includes industry and alumni external members',
      'Student representative included in committee',
      'Quarterly meetings with recorded decisions',
      'Decisions binding on all departments for quality matters',
    ],
    tableData: [
      { Role: 'Chairperson',          Profile: 'Principal, VWU' },
      { Role: 'Director / Coordinator', Profile: 'Senior Professor (nominated by Principal)' },
      { Role: 'Administrative Officer', Profile: 'Senior Admin Staff' },
      { Role: 'HoD Member 1',          Profile: 'Head of Department (rotation)' },
      { Role: 'HoD Member 2',          Profile: 'Head of Department (rotation)' },
      { Role: 'HoD Member 3',          Profile: 'Head of Department (rotation)' },
      { Role: 'External Expert',        Profile: 'Industry / Corporate Representative' },
      { Role: 'Alumni Representative',  Profile: 'Distinguished VWU Alumna' },
      { Role: 'Student Representative', Profile: 'Elected student representative' },
    ],
  },

  {
    slug: 'policies-procedures',
    title: 'Policies & Procedures',
    category: 'iqac',
    icon: '📋',
    desc: 'The institutional policies and standard operating procedures established by VWU\'s IQAC for academic, administrative, and quality management functions.',
    intro: "VWU has established a comprehensive set of policies and standard operating procedures (SOPs) covering all major academic and administrative functions, developed and maintained by the IQAC in collaboration with the relevant committees and departments.",
    about: "Key policies include the Teaching and Learning Policy, Examination and Evaluation Policy, Research and Publication Policy, Student Grievance Policy, Anti-Ragging Policy, POSH Policy, Procurement Policy, and Green Campus Policy. Each policy document includes objectives, scope, responsibilities, procedures, and review mechanisms. All policies are reviewed annually by the IQAC and updated as required to reflect changes in regulatory guidelines, best practices, or institutional context.",
    highlights: [
      'Comprehensive policy framework covering all functions',
      'Teaching, Examination, Research, and Grievance policies',
      'POSH, Anti-Ragging, and Procurement policies in place',
      'Each policy includes clear objectives and responsibilities',
      'Annual review by IQAC and relevant committees',
      'All policies available to staff and students in the intranet',
    ],
  },

  {
    slug: 'annual-reports',
    title: 'Annual Reports & Reforms',
    category: 'iqac',
    icon: '📰',
    desc: 'Annual Quality Assurance Reports (AQAR) submitted to NAAC, along with key institutional reforms initiated in each academic year.',
    intro: "VWU's IQAC prepares and submits the Annual Quality Assurance Report (AQAR) to NAAC every year, documenting the institution's academic achievements, quality initiatives, best practices, and improvement actions taken during the year.",
    about: "The AQAR captures data across all seven NAAC criteria and includes qualitative write-ups on best practices, institutional achievements, student performance, research output, and governance milestones. Annual reforms documented in recent AQARs include the introduction of the Choice Based Credit System, blended learning models, NEP-aligned programme structures, and expanded industry partnerships. The reports are reviewed by the Governing Body and serve as the foundation for NAAC re-accreditation.",
    highlights: [
      'Annual AQAR submitted to NAAC for each academic year',
      'Covers all seven NAAC criteria with data and analysis',
      'Documents best practices and institutional achievements',
      'Reviewed by Governing Body each year',
      'Foundation for NAAC re-accreditation preparation',
      'Recent reforms: CBCS, blended learning, NEP alignment',
    ],
    outcomes: [
      'NAAC Accreditation maintained with consistent quality',
      'CBCS introduced across all UG and PG programmes',
      'Blended learning infrastructure set up for hybrid delivery',
      'NEP-compliant programme structures introduced from 2022-23',
      'Industry certification integrated as credit-bearing courses',
    ],
  },

  {
    slug: 'nirf-reports',
    title: 'MHRD NIRF Reports',
    category: 'iqac',
    icon: '🇮🇳',
    desc: 'VWU\'s submissions and rankings under the Ministry of Education\'s National Institutional Ranking Framework (NIRF), reporting key performance metrics nationally.',
    intro: "VWU participates in the Ministry of Education's National Institutional Ranking Framework (NIRF) annually, submitting detailed data across five parameters: Teaching, Learning & Resources; Research & Professional Practice; Graduation Outcomes; Outreach & Inclusivity; and Perception.",
    about: "The NIRF submission is coordinated by the IQAC and involves data collection from all departments on faculty qualifications, research publications, funded projects, student outcomes, placements, and diversity indicators. VWU's NIRF ranking reflects its strong placement record, industry engagement, and research activity. The data submitted for NIRF also informs strategic planning and benchmarking against peer institutions.",
    highlights: [
      'Annual NIRF submission coordinated by IQAC',
      'Covers five parameters: TLR, RP, GO, OI, and Perception',
      'Data collected from all departments and the TPO Cell',
      'Used for benchmarking against peer institutions',
      'Reflects strong placement, research, and diversity performance',
      'Submission reviewed and approved by Principal before submission',
    ],
  },

  {
    slug: 'nba-data',
    title: 'NBA – Data Capturing Points',
    category: 'iqac',
    icon: '🏆',
    desc: 'Programme-level quality documentation maintained for NBA (National Board of Accreditation) accreditation across VWU\'s engineering programmes.',
    intro: "VWU maintains comprehensive NBA accreditation documentation for its engineering programmes. The NBA Data Capturing Points (DCP) system ensures that all programme outcomes (POs), course outcomes (COs), and programme educational objectives (PEOs) are defined, assessed, and attainment is measured systematically.",
    about: "NBA accreditation is outcome-based and requires extensive data on curriculum mapping, CO-PO attainment levels, student exit surveys, employer surveys, and alumni feedback. VWU's departments maintain semester-wise DCP files documenting CO attainment for each course, PO attainment at programme level, and actions taken to bridge attainment gaps. The IQAC reviews DCP files annually and coordinates NBA submission for eligible programmes.",
    highlights: [
      'Outcome-Based Education (OBE) framework implemented',
      'Programme Outcomes (POs) defined for all UG programmes',
      'Course Outcomes (COs) mapped to POs for all courses',
      'CO and PO attainment measured every semester',
      'Student, employer, and alumni surveys conducted annually',
      'IQAC coordinates NBA documentation and submission',
    ],
    outcomes: [
      'Multiple programmes NBA accredited across CSE, ECE, EEE, and Mechanical Engineering',
      'CO attainment targets set and achieved annually',
      'OBE framework adopted across all departments from 2018',
      'Annual gap analysis leads to targeted curriculum improvements',
    ],
  },
];

export const govCategories = [
  {
    key: 'governance' as const,
    label: 'Governance',
    icon: '🏛️',
    desc: 'Apex statutory bodies governing the academic, financial, and strategic direction of VWU.',
  },
  {
    key: 'committees' as const,
    label: 'Committees',
    icon: '🏫',
    desc: 'Standing committees ensuring quality, welfare, compliance, and transparency across all institutional functions.',
  },
  {
    key: 'iqac' as const,
    label: 'IQAC',
    icon: '✅',
    desc: 'Internal Quality Assurance Cell — driving continuous quality improvement and NAAC accreditation at VWU.',
  },
];

export function findGovItemBySlug(slug: string): GovItem | null {
  return govItems.find(i => i.slug === slug) ?? null;
}
